# Generated by Django 4.0.7 on 2022-09-12 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0005_alter_deal_country_alter_deal_created_by_and_more'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='landmatrix.country'),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='user',
            name='information',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.IntegerField(choices=[(0, '---------'), (1, 'Editor'), (2, 'Reporter'), (3, 'Administrator')], default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='landmatrix.region'),
        ),
    ]
