# Generated by Django 4.0.7 on 2022-09-12 13:20

from django.db import migrations

LEVELMAP = {
    "Administrators": 3,
    "Editors": 2,
    "Reporters": 1,
}


def forwards_func(apps, schema_editor):
    UserRegionalInfo = apps.get_model("editor", "UserRegionalInfo")
    User = apps.get_model("accounts", "User")
    for user in User.objects.all():
        user.full_name = (
            f"{user.first_name} {user.last_name}".strip()
            if (user.first_name or user.last_name)
            else ""
        )

        level = 0
        for group in user.groups.all():
            if match := LEVELMAP.get(group.name):
                level = max(level, match)
        user.level = level

        if hasattr(user, "userregionalinfo"):
            uri = user.userregionalinfo
            user.phone = uri.phone or ""
            user.information = uri.information or ""
            user.country_id = uri.country_id
            user.region_id = uri.region_id

        user.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0002_user_country_user_full_name_user_information_and_more'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),

    ]
