# Generated by Django 4.0.7 on 2022-09-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_update_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.IntegerField(choices=[(0, '---------'), (1, 'Reporter'), (2, 'Editor'), (3, 'Administrator')], default=0),
        ),
    ]
