# Generated by Django 4.0.7 on 2022-09-14 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_email_confirmed_alter_user_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='level',
            new_name='role',
        ),
    ]
