# Generated by Django 5.0.7 on 2024-08-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_full_name_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(0, '---------'), (1, 'Reporter'), (2, 'Editor'), (3, 'Administrator')], default=1),
        ),
    ]
