repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-ast
    - id: check-yaml
    - id: check-added-large-files
    - id: fix-encoding-pragma
      args: ['--remove']
-   repo: https://github.com/psf/black
    rev: 21.10b0
    hooks:
    - id: black
