[local]
#skip_migrate_on_resetdb = false

[production]
host = "landmatrix.org"
user = "landmatrix"
dbname = "landmatrix"
dbuser = "landmatrix"


[staging]
host = "dev.landmatrix.org"
user = "landmatrix"
dbname = "landmatrix"
dbuser = "landmatrix"