[tool.poetry]
name = "landmatrix"
version = "0.1.0"
license = "AGPL-3.0+"
authors = ["sinnwerkstatt Medienagentur GmbH <support@sinnwerkstatt.com>"]
readme = 'README.md'
description = "Land Matrix"

[tool.poetry.dependencies]
python = "^3.8"
Django = "<4"
wagtail = "<2.16"
psycopg2-binary = "*"

django-cors-headers = "*"
django-environ = "*"
django-impersonate = "*"
django-modeltranslation = "*"

wagtail-font-awesome-svg = "*"
wagtail-modeltranslation = ">=0.11rc3"
wagtail-orderable = "*"

ariadne = ">=0.14"
ariadne_django = "*"
fastjsonschema = "*"
geojson-rewind = "*"
nanoid = "*"
openpyxl = "*"
polib = "*"  # for PO to JSON
python-dateutil = "*"
simplejson = "*"
tweepy = "*"
unicodecsv = "*"

#plumbing
doit = "*"
sentry_sdk = "*"
gunicorn = "*"

[tool.poetry.dev-dependencies]
ipdb = "*"
pre-commit = "*"
black = "*"
mypy = "*"
django-livereload = "*"
django-extensions = "*"
pytest-django = "*"
pytest-cov = "*"
pylint = "*"
pylint-django = "*"
#pydot = "*"
pygments = "*"
mkdocs = "*"
pydot = "^1.4.1"
tqdm = "^4.64.0"


[tool.black]
line-length = 88
target-version = ['py36', 'py37', 'py38']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | migrations
  | static-collected
  | node_modules
)/
'''
force-exclude = '''
/(
    \.eggs
  | \.git
  | migrations
  | static-collected
  | node_modules
)/
'''

#
[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = false
line_length = 88
known_first_party = 'apps'
known_django = 'django,wagtail'
default_section = 'THIRDPARTY'
sections = 'FUTURE,STDLIB,THIRDPARTY,DJANGO,FIRSTPARTY,LOCALFOLDER'
no_lines_before = 'LOCALFOLDER,DJANGO'
