[tool.poetry]
name = "landmatrix"
version = "0.1.0"
license = "AGPL-3.0+"
authors = ["sinnwerkstatt Medienagentur GmbH <support@sinnwerkstatt.com>"]
readme = 'README.md'
description = "Land Matrix"

[tool.poetry.dependencies]
python = "^3.8"
Django = "*"
wagtail = "*"
psycopg2-binary = "*"

django-cors-headers = "*"
django-environ = "*"
django-impersonate = "*"
django-modeltranslation = "*"

wagtail-font-awesome-svg = "*"
wagtail-modeltranslation = ">=0.12rc2"
wagtail-orderable = "*"
wagtail-headless-preview = "*"

ariadne = "*"
ariadne_django = "*"
fastjsonschema = "*"
geojson-rewind = "*"
nanoid = "*"
openpyxl = "*"
polib = "*"  # for PO to JSON
python-dateutil = "*"
simplejson = "*"
tweepy = "*"
unicodecsv = "*"

#plumbing
doit = "*"
sentry_sdk = "*"
gunicorn = "*"
tzdata = "*"
python-memcached = "^1.59"

[tool.poetry.dev-dependencies]
ipdb = "*"
pre-commit = "*"
black = "*"
mypy = "*"
django-livereload = "*"
django-extensions = "*"
pytest-django = "*"
pytest-cov = "*"
pylint = "*"
pylint-django = "*"
#pydot = "*"
pygments = "*"
mkdocs = "*"
pydot = "^1.4.1"
tqdm = "^4.64.0"


[tool.black]
line-length = 88
target-version = ['py38', 'py39', 'py310']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | migrations
  | static-collected
  | node_modules
  | frontend
  | newfront
)/
'''
force-exclude = '''
/(
    \.eggs
  | \.git
  | migrations
  | static-collected
  | node_modules
  | frontend
  | newfront
)/
'''
