[tool.poetry]
name = "landmatrix"
version = "0.1.0"
license = "AGPL-3.0+"
authors = ["sinnwerkstatt Medienagentur GmbH <support@sinnwerkstatt.com>"]
readme = 'README.md'
description = "Land Matrix"

[tool.poetry.dependencies]
python = "^3.8"
Django = "*"
wagtail = "*"
psycopg2-binary = "*"

django-cors-headers = "*"
django-environ = "*"
django-impersonate = "*"
django-modeltranslation = "*"

wagtail-font-awesome-svg = "*"
wagtail-modeltranslation = ">=0.12rc2"
wagtail-orderable = "*"
wagtail-headless-preview = "*"

ariadne = "*"
ariadne_django = "*"
fastjsonschema = "*"
nanoid = "*"
openpyxl = "*"
polib = "*"  # for PO to JSON
python-dateutil = "*"
simplejson = "*"
tweepy = "*"
unicodecsv = "*"

#plumbing
doit = "*"
sentry_sdk = "*"
gunicorn = "*"
tzdata = "*"
python-memcached = "^1.59"
ramda = "^0.7.6"

[tool.poetry.group.dev.dependencies]
ipdb = "*"
pre-commit = "*"
black = "*"
mypy = "*"
django-livereload = "*"
django-extensions = "*"
pytest-django = "*"
pytest-cov = "*"
pytest-watch = "^4.2.0"
pylint = "*"
pylint-django = "*"
pygments = "*"
mkdocs = "*"
pydot = "^1.4.1"
tqdm = "^4.64.0"
isort = "^5.12.0"
termtables = "^0.2.4"

# stubs
django-stubs = {extras = ["compatible-mypy"], version = "^1.14.0"}
djangorestframework-stubs = {extras = ["compatible-mypy"], version = "^1.8.0"}

# types
types-pytz = "^2022.7.1.0"
types-openpyxl = "^3.0.4.5"
types-markdown = "^3.4.2.5"
types-pygments = "^2.14.0.6"
types-psycopg2 = "^2.9.21.8"
types-colorama = "^0.4.15.8"
types-polib = "^1.2.0.0"
types-simplejson = "^3.18.0.1"
types-tqdm = "^4.65.0.0"


[tool.black]
line-length = 88
target-version = ['py38', 'py39', 'py310']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | migrations
  | static-collected
  | node_modules
  | frontend
)/
'''
force-exclude = '''
/(
    \.eggs
  | \.git
  | migrations
  | static-collected
  | node_modules
  | frontend
)/
'''

[tool.isort]
profile = "black"
extend_skip_glob = ["*/migrations/*.py"]
known_django = ["django", "wagtail", "rest_framework", "wagtail_headless_preview", "modelcluster"]
known_first_party = ["apps"]
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "DJANGO", "FIRSTPARTY", "LOCALFOLDER"]


# https://mypy.readthedocs.io/en/latest/config_file.html#using-a-pyproject-toml-file
[tool.mypy]
plugins = ["mypy_django_plugin.main"]
exclude = ['migrations']
strict_equality = true
check_untyped_defs = true

[[tool.mypy.overrides]]
module = [
  "wagtail.*",
  "wagtail_headless_preview.*",
  "modelcluster.*",
  "modeltranslation.*"
]
ignore_missing_imports = true


[tool.django-stubs]
django_settings_module = "config.settings.dev"
