[tool.poetry]
name = "landmatrix"
version = "0.1.0"
license = "AGPL-3.0+"
authors = [
  "Simon Liedtke <simon.liedtke@gmail.com>",
  "Andreas Nüßlein <andreas@nuessle.in>",
]
readme = 'README.md'
description = "LandMatrix"

[tool.poetry.dependencies]
python = "^3.8"
Django = "<4"
djangorestframework = "<4"
wagtail = "<2.15"
psycopg2-binary = "*"

fastjsonschema = "*"
pyelasticsearch = {git = "https://github.com/sinnwerkstatt/pyelasticsearch", branch = "batteriesincluded" }

# greennewdeal
geojson-rewind = "^0.2.0"
ariadne = ">=0.12"
django-redis = "^4.12.1"
wagtail-orderable = ">=1.0.3"


redis = "*"
python-memcached = "*"


djangorestframework-gis = "<0.16"
drf-yasg = "*"
packaging = "*"
#django-rest-swagger = "*"
django-crispy-forms = "*"
django-environ = "*"
django-file-resubmit = "*"

django-modeltranslation = "*"
django-contrib-comments = "*"
django-threadedcomments = "*"
django-bootstrap3-datetimepicker-2 = "*"
django-impersonate = "*"
django-multiselectfield = "*"
django-recaptcha = "*"
django-registration = "*"
django-simple-history = "*"
django-wkhtmltopdf = "*"

#wagtail-blog = "*"
wagtail-modeltranslation = "*"

geojson = "<2"
unicodecsv = "*"
openpyxl = "*"
tweepy = "*"
country-bounding-boxes = "*"
python-dateutil = "*"


#plumbing
doit = "*"
celery = "*"
libsass = "*"
gunicorn = { version = "*", optional = true }
sentry_sdk = { version = "*", optional = true }
termtables = "^0.2.4"


[tool.poetry.dev-dependencies]
ipdb = "*"
pre-commit = "*"
black = { version = "*", allow-prereleases = true }
mypy = "*"
django-livereload = "*"
django-extensions = "*"
pytest-django = "*"
pytest-cov = "*"
pylint = "<2.5.0"
pylint-django = "*"
#pydot = "*"
pygments = "*"
mkdocs = "*"
pydot = "^1.4.1"

[tool.poetry.extras]
production = ["gunicorn", "sentry_sdk"]


[tool.black]
line-length = 88
target-version = ['py36', 'py37', 'py38']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | migrations
  | static-collected
  | node_modules
)/
'''
force-exclude = '''
/(
    \.eggs
  | \.git
  | migrations
  | static-collected
  | node_modules
)/
'''

#
[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = false
line_length = 88
known_first_party = 'apps'
known_django = 'celery,django,django_registration,wagtail'
default_section = 'THIRDPARTY'
sections = 'FUTURE,STDLIB,THIRDPARTY,DJANGO,FIRSTPARTY,LOCALFOLDER'
no_lines_before = 'LOCALFOLDER,DJANGO'
