# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-21 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregionalinfo',
            name='information',
            field=models.TextField(blank=True, null=True),
        ),
    ]
