# Generated by Django 3.2.13 on 2022-06-29 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('editor', '0001_initial'), ('editor', '0002_userregionalinfo_information'), ('editor', '0003_auto_20190425_0004'), ('editor', '0004_auto_20220617_1731'), ('editor', '0005_auto_20220617_2213')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('landmatrix', '0001_squashed_0057_auto_20220617_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegionalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('information', models.TextField(blank=True, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='landmatrix.country')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='landmatrix.region')),
            ],
            options={
                'permissions': (('editor', 'Editor'), ('editor_filter', 'Filter dashboard')),
            },
        ),
    ]
