# Generated by Django 4.0.7 on 2022-09-11 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0005_alter_deal_country_alter_deal_created_by_and_more'),
        ('editor', '0001_squashed_0005_auto_20220617_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregionalinfo',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='landmatrix.country'),
        ),
        migrations.AlterField(
            model_name='userregionalinfo',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='landmatrix.region'),
        ),
    ]
