# Generated by Django 4.0.7 on 2023-02-18 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_alter_userregionalinfo_country_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRegionalInfo',
        ),
    ]
