# Generated by Django 3.2.13 on 2022-06-17 15:31

from django.db import migrations, models
import django.db.models.deletion


def forward_func(apps, schema_editor):
    userreginfo = apps.get_model("editor", "UserRegionalInfo").objects.all()
    for uri in userreginfo:
        if countries := uri.country.all():
            uri.country_fk = countries[0]
        if regions := uri.region.all():
            uri.region_fk = regions[0]
        uri.save()


def backward_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0056_alter_deal_current_negotiation_status'),
        ('editor', '0003_auto_20190425_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregionalinfo',
            name='super_user',
        ),
        migrations.AddField(
            model_name='userregionalinfo',
            name='country_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='landmatrix.country'),
        ),
        migrations.AddField(
            model_name='userregionalinfo',
            name='region_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='landmatrix.region'),
        ),
        migrations.AlterField(
            model_name='userregionalinfo',
            name='country',
            field=models.ManyToManyField(blank=True, related_name='_editor_userregionalinfo_country_+', to='landmatrix.Country'),
        ),
        migrations.AlterField(
            model_name='userregionalinfo',
            name='region',
            field=models.ManyToManyField(blank=True, related_name='_editor_userregionalinfo_region_+', to='landmatrix.Region'),
        ),
        migrations.RunPython(forward_func, backward_func)

    ]
