# Generated by Django 3.2.13 on 2022-06-17 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0004_auto_20220617_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregionalinfo',
            name='country',
        ),
        migrations.RemoveField(
            model_name='userregionalinfo',
            name='region',
        ),
        migrations.RenameField(
            model_name='userregionalinfo',
            old_name='country_fk',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='userregionalinfo',
            old_name='region_fk',
            new_name='region',
        ),
    ]
