# Generated by Django 5.0.4 on 2024-07-10 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('landmatrix', '0020_area_nid'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealScore',
            fields=[
                ('test', models.CharField(max_length=30)),
                ('deal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='landmatrix.dealhull')),
            ],
        ),
    ]
