# Generated by Django 5.0.4 on 2024-08-22 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountability', '0001_initial'),
        ('landmatrix', '0020_area_nid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealscore',
            name='deal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='accountability_score_hull', serialize=False, to='landmatrix.dealhull'),
        ),
    ]
