# Generated by Django 5.0.4 on 2024-07-10 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountability', '0002_vggtchapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='VggtArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=500)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountability.vggtchapter')),
            ],
        ),
    ]
