# Generated by Django 5.0.4 on 2024-08-27 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountability', '0002_alter_dealscore_deal'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vggtarticle',
            unique_together={('chapter', 'article')},
        ),
    ]
