# Generated by Django 5.0.4 on 2024-07-31 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountability', '0002_alter_bookmark_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
