# Generated by Django 5.0.4 on 2024-08-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountability', '0003_alter_vggtarticle_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealscoreversion',
            name='status',
            field=models.CharField(choices=[('TO_SCORE', 'To score'), ('WAITING', 'Waiting'), ('VALIDATED', 'Validated')], default='TO_SCORE', max_length=10),
        ),
    ]
