# Generated by Django 5.0.4 on 2024-07-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountability', '0003_vggtarticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vggtarticle',
            name='description',
            field=models.CharField(max_length=2000),
        ),
    ]
