# Generated by Django 5.0.4 on 2024-07-11 06:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountability', '0004_alter_vggtarticle_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='VggtVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('landmatrixFields', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=50)),
                ('landmatrixAdditionalFields', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=50)),
                ('scoringHelp', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2000), size=20)),
            ],
        ),
    ]
