# Generated by Django 5.0.4 on 2024-09-02 07:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountability', '0004_dealscoreversion_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vggtvariable',
            name='landmatrix_fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, choices=[('NO_DATA', 'Insufficient data'), ('NO_VIOLATIONS', 'No violation'), ('PARTIAL_VIOLATIONS', 'Violations'), ('SEVERE_VIOLATIONS', 'Severe violations')], null=True, size=50),
        ),
    ]
