# Generated by Django 5.0.4 on 2024-07-11 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountability', '0005_vggtvariable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='vggtvariable',
            old_name='landmatrixAdditionalFields',
            new_name='landmatrix_additional_fields',
        ),
        migrations.RenameField(
            model_name='vggtvariable',
            old_name='landmatrixFields',
            new_name='landmatrix_fields',
        ),
        migrations.RenameField(
            model_name='vggtvariable',
            old_name='scoringHelp',
            new_name='scoring_help',
        ),
        migrations.CreateModel(
            name='DealVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('TO_SCORE', 'To score'), ('WAITING', 'Waiting'), ('VALIDATED', 'Validated')], max_length=10)),
                ('score', models.CharField(choices=[('NO_DATA', 'Insufficient data'), ('NO_VIOLATIONS', 'No violation'), ('PARTIAL_VIOLATIONS', 'Violations'), ('SEVERE_VIOLATIONS', 'Severe violations')], max_length=20)),
                ('scored_at', models.DateTimeField(verbose_name='Created at')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignee', to=settings.AUTH_USER_MODEL)),
                ('deal_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountability.dealscore')),
                ('score_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vggt_variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountability.vggtvariable')),
            ],
        ),
    ]
