# Generated by Django 5.0.4 on 2024-08-02 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountability', '0005_remove_project_animals_remove_project_area_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filters',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='accountability.project'),
        ),
    ]
