# Generated by Django 5.0.4 on 2024-09-02 07:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountability', '0005_alter_vggtvariable_landmatrix_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vggtvariable',
            name='landmatrix_fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=50),
        ),
    ]
