# Generated by Django 5.0.4 on 2024-07-15 07:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountability', '0006_rename_landmatrixadditionalfields_vggtvariable_landmatrix_additional_fields_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vggtvariable',
            name='landmatrix_additional_fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=50),
        ),
        migrations.AlterField(
            model_name='vggtvariable',
            name='landmatrix_fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=50),
        ),
        migrations.AlterField(
            model_name='vggtvariable',
            name='scoring_help',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2000), blank=True, null=True, size=20),
        ),
    ]
