# Generated by Django 5.0.4 on 2024-09-02 08:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountability', '0006_alter_vggtvariable_landmatrix_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='vggtvariable',
            name='score_options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('NO_DATA', 'Insufficient data'), ('NO_VIOLATIONS', 'No violation'), ('PARTIAL_VIOLATIONS', 'Violations'), ('SEVERE_VIOLATIONS', 'Severe violations')], max_length=20), blank=True, null=True, size=4),
        ),
    ]
