# Generated by Django 5.0.4 on 2024-07-15 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountability', '0007_alter_vggtvariable_landmatrix_additional_fields_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dealscore',
            options={'ordering': ['deal']},
        ),
        migrations.AlterModelOptions(
            name='dealvariable',
            options={'ordering': ['deal_score', 'vggt_variable']},
        ),
        migrations.AlterUniqueTogether(
            name='dealvariable',
            unique_together={('deal_score', 'vggt_variable')},
        ),
    ]
