# Generated by Django 5.0.4 on 2024-09-02 08:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountability', '0007_vggtvariable_score_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealvariable',
            name='score',
            field=models.CharField(choices=[('NO_SCORE', 'No score'), ('NO_DATA', 'Insufficient data'), ('SEVERE_VIOLATIONS', 'Severe violations'), ('PARTIAL_VIOLATIONS', 'Violations'), ('NO_VIOLATIONS', 'No violation')], default='NO_SCORE', max_length=20),
        ),
        migrations.AlterField(
            model_name='vggtvariable',
            name='score_options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('NO_DATA', 'Insufficient data'), ('SEVERE_VIOLATIONS', 'Severe violations'), ('PARTIAL_VIOLATIONS', 'Violations'), ('NO_VIOLATIONS', 'No violation')], max_length=20), blank=True, default=['NO_DATA', 'SEVERE_VIOLATIONS', 'PARTIAL_VIOLATIONS', 'NO_VIOLATIONS'], null=True, size=4),
        ),
    ]
