# Generated by Django 5.0.4 on 2024-09-02 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountability', '0008_alter_dealvariable_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vggtvariable',
            name='score_options',
        ),
    ]
