# Generated by Django 5.0.4 on 2024-07-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountability', '0008_alter_dealscore_options_alter_dealvariable_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealvariable',
            name='score',
            field=models.CharField(choices=[('', 'No score'), ('NO_DATA', 'Insufficient data'), ('NO_VIOLATIONS', 'No violation'), ('PARTIAL_VIOLATIONS', 'Violations'), ('SEVERE_VIOLATIONS', 'Severe violations')], max_length=20),
        ),
    ]
