# Generated by Django 5.0.4 on 2024-07-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountability', '0009_alter_dealvariable_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealvariable',
            name='score',
            field=models.CharField(choices=[('NO_SCORE', 'No score'), ('NO_DATA', 'Insufficient data'), ('NO_VIOLATIONS', 'No violation'), ('PARTIAL_VIOLATIONS', 'Violations'), ('SEVERE_VIOLATIONS', 'Severe violations')], max_length=20),
        ),
        migrations.AlterField(
            model_name='dealvariable',
            name='scored_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Created at'),
        ),
    ]
