# Generated by Django 5.0.4 on 2024-09-04 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountability', '0011_vggtvariable_articles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vggtvariable',
            name='scoring_help',
        ),
    ]
