# Generated by Django 5.0.9 on 2024-12-05 11:40

import apps.accountability.models
import apps.landmatrix.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountability', '0012_remove_vggtvariable_scoring_help'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vggtvariable',
            name='score_options',
            field=apps.landmatrix.models.fields.ChoiceArrayField(base_field=models.CharField(choices=[('NO_DATA', 'Insufficient data'), ('SEVERE_VIOLATIONS', 'Severe violations'), ('PARTIAL_VIOLATIONS', 'Violations'), ('NO_VIOLATIONS', 'No violation')]), blank=True, default=apps.accountability.models.get_default_score_options, size=None),
        ),
    ]
