# Generated by Django 5.0.4 on 2024-07-29 16:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountability', '0014_remove_project_editors_project_editors'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='editors',
            field=models.ManyToManyField(blank=True, related_name='editable_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
