# Generated by Django 5.0.4 on 2024-07-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountability', '0015_alter_project_editors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='modified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Modified at'),
        ),
    ]
