# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-25 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='fully_updated',
        ),
        migrations.AddField(
            model_name='activity',
            name='fully_updated',
            field=models.DateField(blank=True, null=True, verbose_name='Fully updated'),
        ),
    ]
