# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-08 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0003_auto_20170531_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='top_investors',
            field=models.ManyToManyField(blank=True, null=True, to='landmatrix.Investor', verbose_name='Top investors'),
        ),
    ]
