# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-30 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0010_auto_20180729_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investoractivitysize',
            name='fk_activity',
        ),
        migrations.RemoveField(
            model_name='investoractivitysize',
            name='fk_investor',
        ),
        migrations.AlterField(
            model_name='activity',
            name='is_public',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is public'),
        ),
        migrations.AlterField(
            model_name='filtercondition',
            name='operator',
            field=models.CharField(choices=[('is', 'is'), ('in', 'in'), ('not_in', 'not_in'), ('gte', 'gte'), ('gt', 'gt'), ('lte', 'lte'), ('lt', 'lt'), ('contains', 'contains'), ('not_contains', 'not_contains'), ('is_empty', 'is_empty'), ('excludes', 'excludes')], max_length=20, verbose_name='Operator'),
        ),
        migrations.AlterField(
            model_name='historicalinvestoractivityinvolvement',
            name='fk_activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='involvements', to='landmatrix.HistoricalActivity', verbose_name='Activity'),
        ),
        migrations.AlterField(
            model_name='historicalinvestoractivityinvolvement',
            name='fk_investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='involvements', to='landmatrix.HistoricalInvestor', verbose_name='Investor'),
        ),
        migrations.AlterField(
            model_name='investoractivityinvolvement',
            name='fk_activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='involvements', to='landmatrix.Activity', verbose_name='Activity'),
        ),
        migrations.AlterField(
            model_name='investoractivityinvolvement',
            name='fk_investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='involvements', to='landmatrix.Investor', verbose_name='Investor'),
        ),
        migrations.DeleteModel(
            name='InvestorActivitySize',
        ),
    ]
