# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-07 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0011_auto_20180730_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='forest_concession',
            field=models.BooleanField(default=False, verbose_name='Forest concession'),
        ),
    ]
