# Generated by Django 2.1.8 on 2019-04-24 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0015_auto_20190207_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='fk_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='landmatrix.Status', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='activityattribute',
            name='fk_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='landmatrix.ActivityAttributeGroup', verbose_name='Activity Attribute Group'),
        ),
        migrations.AlterField(
            model_name='activityattribute',
            name='fk_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='landmatrix.Language', verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='activityattribute',
            name='is_current',
            field=models.BooleanField(blank=True, default=False, verbose_name='Is current'),
        ),
        migrations.AlterField(
            model_name='activitychangeset',
            name='fk_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='landmatrix.Country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='activitychangeset',
            name='fk_review_decision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='landmatrix.ReviewDecision', verbose_name='Review decision'),
        ),
        migrations.AlterField(
            model_name='activitychangeset',
            name='fk_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='activityfeedback',
            name='fk_user_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_assigned', to=settings.AUTH_USER_MODEL, verbose_name='User assigned'),
        ),
        migrations.AlterField(
            model_name='activityfeedback',
            name='fk_user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_created', to=settings.AUTH_USER_MODEL, verbose_name='User created'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='fk_activity_attribute_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='landmatrix.ActivityAttributeGroup', verbose_name='Activity attribute group'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='fk_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='country',
            name='fk_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='landmatrix.Region', verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='fk_agricultural_produce',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='landmatrix.AgriculturalProduce', verbose_name='Agricultural produce'),
        ),
        migrations.AlterField(
            model_name='filterpreset',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filter_presets', to='landmatrix.FilterPresetGroup'),
        ),
        migrations.AlterField(
            model_name='historicalactivity',
            name='fk_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='landmatrix.Status', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalactivity',
            name='history_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalactivityattribute',
            name='fk_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='landmatrix.ActivityAttributeGroup', verbose_name='Activity Attribute Group'),
        ),
        migrations.AlterField(
            model_name='historicalactivityattribute',
            name='fk_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='landmatrix.Language', verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='historicalactivityattribute',
            name='is_current',
            field=models.BooleanField(blank=True, default=False, verbose_name='Is current'),
        ),
        migrations.AlterField(
            model_name='historicalinvestor',
            name='action_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='historicalinvestor',
            name='fk_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='landmatrix.Country', verbose_name='Country of registration/origin'),
        ),
        migrations.AlterField(
            model_name='historicalinvestor',
            name='fk_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='landmatrix.Status', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalinvestor',
            name='history_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalinvestoractivityinvolvement',
            name='fk_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='landmatrix.Status', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalinvestorventureinvolvement',
            name='fk_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='landmatrix.Status', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalinvestorventureinvolvement',
            name='loans_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='landmatrix.Currency', verbose_name='Loan currency'),
        ),
        migrations.AlterField(
            model_name='investor',
            name='fk_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='landmatrix.Country', verbose_name='Country of registration/origin'),
        ),
        migrations.AlterField(
            model_name='investor',
            name='fk_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='landmatrix.Status', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='investoractivityinvolvement',
            name='fk_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='landmatrix.Status', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='investorventureinvolvement',
            name='fk_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='landmatrix.Status', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='investorventureinvolvement',
            name='loans_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='landmatrix.Currency', verbose_name='Loan currency'),
        ),
    ]
