# Generated by Django 4.0.7 on 2023-02-17 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpagetag_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='name_en',
            field=models.CharField(max_length=80, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='name_es',
            field=models.CharField(max_length=80, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='name_fr',
            field=models.CharField(max_length=80, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='name_ru',
            field=models.CharField(max_length=80, null=True, unique=True, verbose_name='Category Name'),
        ),
    ]
