# Generated by Django 4.2.1 on 2023-06-29 08:27

import apps.wagtailcms.blocks
from django.db import migrations
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpagetag_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('paragraph', apps.wagtailcms.blocks.RichTextBlock(features=['bold', 'italic', 'h2', 'h3', 'ol', 'ul', 'hr', 'link', 'image', 'document-link'])), ('link', wagtail.blocks.StructBlock([('cls', wagtail.blocks.ChoiceBlock(choices=[('btn', 'Button'), ('btn btn-with-space', 'Button (with space)')], label='Type', required=False)), ('url', wagtail.blocks.URLBlock(label='URL')), ('text', wagtail.blocks.CharBlock())], icon='link')), ('anchor', wagtail.blocks.StructBlock([('slug', wagtail.blocks.CharBlock())], icon='link')), ('image', apps.wagtailcms.blocks.ImageBlock()), ('linked_image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('url', wagtail.blocks.URLBlock(label='URL', required=False)), ('caption', apps.wagtailcms.blocks.RichTextBlock(required=False)), ('lightbox', wagtail.blocks.BooleanBlock(default=False, help_text='When selected, this image becomes clickable to show a maximized version.<br/>Beware: combining this with the URL will not work.', required=False))])), ('media', wagtail.embeds.blocks.EmbedBlock(icon='media')), ('gallery', wagtail.blocks.StructBlock([('columns', wagtail.blocks.ChoiceBlock(choices=[(1, '1 column'), (2, '2 columns'), (3, '3 columns'), (4, '4 columns'), (5, '5 columns'), (6, '6 columns')], icon='fa-columns')), ('images', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('url', wagtail.blocks.URLBlock(label='URL', required=False)), ('caption', apps.wagtailcms.blocks.RichTextBlock(required=False)), ('lightbox', wagtail.blocks.BooleanBlock(default=False, help_text='When selected, this image becomes clickable to show a maximized version.<br/>Beware: combining this with the URL will not work.', required=False))])))])), ('slider', wagtail.blocks.StructBlock([('images', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('url', wagtail.blocks.URLBlock(label='URL', required=False)), ('caption', apps.wagtailcms.blocks.RichTextBlock(required=False)), ('lightbox', wagtail.blocks.BooleanBlock(default=False, help_text='When selected, this image becomes clickable to show a maximized version.<br/>Beware: combining this with the URL will not work.', required=False))])))])), ('section_divider', wagtail.blocks.StructBlock([])), ('faqs_block', wagtail.blocks.StructBlock([('faqs', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('slug', wagtail.blocks.CharBlock()), ('question', wagtail.blocks.CharBlock()), ('answer', apps.wagtailcms.blocks.RichTextBlock())])))]))], blank=True, use_json_field=True, verbose_name='body'),
        ),
    ]
