# Generated by Django 4.2.7 on 2024-03-05 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogpage_body_en_blogpage_body_es_blogpage_body_fr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='body_en',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='body_es',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='body_fr',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='body_ru',
        ),
    ]
