# Generated by Django 5.0.3 on 2024-04-25 11:20

import apps.wagtailcms.blocks
import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogcategory_name_en_blogcategory_name_es_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='documents',
            field=wagtail.fields.StreamField([('document', apps.wagtailcms.blocks.MyDocumentChooserBlock()), ('text', wagtail.blocks.CharBlock())], blank=True, null=True, use_json_field=True),
        ),
    ]
