# Generated by Django 2.2.10 on 2020-02-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greennewdeal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorventureinvolvement',
            name='old_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investorventureinvolvement',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='people_affected_comment',
            field=models.TextField(blank=True, verbose_name='Comment on communities / indigenous peoples affected'),
        ),
    ]
