# Generated by Django 2.2.10 on 2020-02-17 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greennewdeal', '0002_auto_20200217_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='status',
            field=models.IntegerField(choices=[(1, 'Draft'), (2, 'Live'), (3, 'Live + Draft'), (4, 'Deleted'), (5, 'Rejected'), (6, 'To Delete?')], default=1),
        ),
    ]
