# Generated by Django 2.2.12 on 2020-05-15 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greennewdeal', '0002_auto_20200420_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deal',
            old_name='private',
            new_name='confidential',
        ),
        migrations.RenameField(
            model_name='deal',
            old_name='private_comment',
            new_name='confidential_comment',
        ),
        migrations.RenameField(
            model_name='deal',
            old_name='private_reason',
            new_name='confidential_reason',
        ),
    ]
