# Generated by Django 2.2.10 on 2020-02-18 18:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('greennewdeal', '0003_deal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorventureinvolvement',
            name='status',
            field=models.IntegerField(choices=[(1, 'Draft'), (2, 'Live'), (3, 'Live + Draft'), (4, 'Deleted'), (5, 'Rejected'), (6, 'To Delete?')], default=1),
        ),
        migrations.AlterField(
            model_name='deal',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='investor',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='investorventureinvolvement',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
