# Generated by Django 2.2.12 on 2020-06-01 11:53

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greennewdeal', '0003_auto_20200515_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='contract_area',
        ),
        migrations.RemoveField(
            model_name='location',
            name='intended_area',
        ),
        migrations.RemoveField(
            model_name='location',
            name='production_area',
        ),
        migrations.AddField(
            model_name='location',
            name='geojson',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='type',
            field=models.CharField(blank=True, choices=[('MEDIA_REPORT', 'Media report'), ('RESEARCH_PAPER_OR_POLICY_REPORT', 'Research Paper / Policy Report'), ('GOVERNMENT_SOURCES', 'Government sources'), ('COMPANY_SOURCES', 'Company sources'), ('CONTRACT', 'Contract'), ('CONTRACT_FARMING_AGREEMENT', 'Contract (contract farming agreement)'), ('PERSONAL_INFORMATION', 'Personal information'), ('CROWDSOURCING', 'Crowdsourcing'), ('OTHER', 'Other (Please specify in comment field)')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='annual_leasing_fee_type',
            field=models.CharField(blank=True, choices=[('PER_HA', 'per ha'), ('PER_AREA', 'for specified area')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='community_consultation',
            field=models.CharField(blank=True, choices=[('NOT_CONSULTED', 'Not consulted'), ('LIMITED_CONSULTATION', 'Limited consultation'), ('FPIC', 'Free, Prior and Informed Consent (FPIC)'), ('OTHER', 'Other')], max_length=100, null=True, verbose_name='Community consultation'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='community_reaction',
            field=models.CharField(blank=True, choices=[('CONSENT', 'Consent'), ('MIXED_REACTION', 'Mixed reaction'), ('REJECTION', 'Rejection')], max_length=100, null=True, verbose_name='Community reaction'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='confidential_reason',
            field=models.CharField(blank=True, choices=[('TEMPORARY_REMOVAL', 'Temporary removal from PI after criticism'), ('RESEARCH_IN_PROGRESS', 'Research in progress'), ('LAND_OBSERVATORY_IMPORT', 'Land Observatory Import')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='current_implementation_status',
            field=models.CharField(blank=True, choices=[('PROJECT_NOT_STARTED', 'Project not started'), ('STARTUP_PHASE', 'Startup phase (no production)'), ('IN_OPERATION', 'In operation (production)'), ('PROJECT_ABANDONED', 'Project abandoned')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='current_negotiation_status',
            field=models.CharField(blank=True, choices=[('EXPRESSION_OF_INTEREST', 'Expression of interest'), ('UNDER_NEGOTIATION', 'Under negotiation'), ('MEMORANDUM_OF_UNDERSTANDING', 'Memorandum of understanding'), ('ORAL_AGREEMENT', 'Oral agreement'), ('CONTRACT_SIGNED', 'Contract signed'), ('NEGOTIATIONS_FAILED', 'Negotiations failed'), ('CONTRACT_CANCELED', 'Contract canceled'), ('CONTRACT_EXPIRED', 'Contract expired'), ('CHANGE_OF_OWNERSHIP', 'Change of ownership')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='former_land_cover',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('CROPLAND', 'Cropland'), ('FOREST_LAND', 'Forest land'), ('PASTURE', 'Pasture'), ('RANGELAND', 'Shrub land/Grassland (Rangeland)'), ('MARGINAL_LAND', 'Marginal land'), ('WETLAND', 'Wetland'), ('OTHER_LAND', 'Other land (e.g. developed land – specify in comment field)')], max_length=100, verbose_name='Former land cover'), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='deal',
            name='former_land_owner',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('STATE', 'State'), ('PRIVATE_SMALLHOLDERS', 'Private (smallholders)'), ('PRIVATE_LARGE_SCALE', 'Private (large-scale farm)'), ('COMMUNITY', 'Community'), ('INDIGENOUS_PEOPLE', 'Indigenous people'), ('OTHER', 'Other')], max_length=100, verbose_name='Former land owner'), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='deal',
            name='former_land_use',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('COMMERCIAL_AGRICULTURE', 'Commercial (large-scale) agriculture'), ('SMALLHOLDER_AGRICULTURE', 'Smallholder agriculture'), ('SHIFTING_CULTIVATION', 'Shifting cultivation'), ('PASTORALISM', 'Pastoralism'), ('HUNTING_GATHERING', 'Hunting/Gathering'), ('FORESTRY', 'Forestry'), ('CONSERVATION', 'Conservation'), ('OTHER', 'Other')], max_length=100, verbose_name='Former land use'), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='deal',
            name='materialized_benefits',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('HEALTH', 'Health'), ('EDUCATION', 'Education'), ('PRODUCTIVE_INFRASTRUCTURE', 'Productive infrastructure (e.g. irrigation, tractors, machinery...)'), ('ROADS', 'Roads'), ('CAPACITY_BUILDING', 'Capacity Building'), ('FINANCIAL_SUPPORT', 'Financial Support'), ('COMMUNITY_SHARES', 'Community shares in the investment project'), ('OTHER', 'Other')], max_length=100, verbose_name='Promised benefits for local communities'), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='deal',
            name='nature_of_deal',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('OUTRIGHT_PURCHASE', 'Outright Purchase'), ('LEASE', 'Lease'), ('CONCESSION', 'Concession'), ('EXPLOITATION_PERMIT', 'Exploitation permit / license / concession (for mineral resources)'), ('PURE_CONTRACT_FARMING', 'Pure contract farming')], max_length=100, verbose_name='Nature of the deal'), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='deal',
            name='negative_impacts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('ENVIRONMENTAL_DEGRADATION', 'Environmental degradation'), ('SOCIO_ECONOMIC', 'Socio-economic'), ('CULTURAL_LOSS', 'Cultural loss'), ('EVICTION', 'Eviction'), ('DISPLACEMENT', 'Displacement'), ('VIOLENCE', 'Violence'), ('OTHER', 'Other')], max_length=100, verbose_name='Negative impacts for local communities'), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='deal',
            name='prai_applied',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('PARTIALLY', 'Partially'), ('NO', 'No')], max_length=100, null=True, verbose_name='Application of Principles for Responsible Agricultural Investments (PRAI)'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='promised_benefits',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('HEALTH', 'Health'), ('EDUCATION', 'Education'), ('PRODUCTIVE_INFRASTRUCTURE', 'Productive infrastructure (e.g. irrigation, tractors, machinery...)'), ('ROADS', 'Roads'), ('CAPACITY_BUILDING', 'Capacity Building'), ('FINANCIAL_SUPPORT', 'Financial Support'), ('COMMUNITY_SHARES', 'Community shares in the investment project'), ('OTHER', 'Other')], max_length=100, verbose_name='Promised benefits for local communities'), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='deal',
            name='purchase_price_type',
            field=models.CharField(blank=True, choices=[('PER_HA', 'per ha'), ('PER_AREA', 'for specified area')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='recognition_status',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('INDIGENOUS_RIGHTS_RECOGNIZED', 'Indigenous Peoples traditional or customary rights recognized by government'), ('INDIGENOUS_RIGHTS_NOT_RECOGNIZED', 'Indigenous Peoples traditional or customary rights not recognized by government'), ('COMMUNITY_RIGHTS_RECOGNIZED', 'Community traditional or customary rights recognized by government'), ('COMMUNITY_RIGHTS_NOT_RECOGNIZED', 'Community traditional or customary rights not recognized by government')], max_length=100, verbose_name='Name of community'), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='deal',
            name='source_of_water_extraction',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('GROUNDWATER', 'Groundwater'), ('SURFACE_WATER', 'Surface water'), ('RIVER', 'River'), ('LAKE', 'Lake')], max_length=100, verbose_name='Source of water extraction'), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='deal',
            name='vggt_applied',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('PARTIALLY', 'Partially'), ('NO', 'No')], max_length=100, null=True, verbose_name='Application of Voluntary Guidelines on the Responsible Governance of Tenure (VGGT)'),
        ),
        migrations.AlterField(
            model_name='investor',
            name='classification',
            field=models.CharField(blank=True, choices=[('PRIVATE_COMPANY', 'Private company'), ('STOCK_EXCHANGE_LISTED_COMPANY', 'Stock-exchange listed company'), ('INDIVIDUAL_ENTREPRENEUR', 'Individual entrepreneur'), ('INVESTMENT_FUND', 'Investment fund'), ('SEMI_STATE_OWNED_COMPANY', 'Semi state-owned company'), ('STATE_OWNED_COMPANY', 'State-/government (owned) company'), ('OTHER', 'Other (please specify in comment field)'), ('GOVERNMENT', 'Government'), ('GOVERNMENT_INSTITUTION', 'Government institution'), ('MULTILATERAL_DEVELOPMENT_BANK', 'Multilateral Development Bank (MDB)'), ('BILATERAL_DEVELOPMENT_BANK', 'Bilateral Development Bank / Development Finance Institution'), ('COMMERCIAL_BANK', 'Commercial Bank'), ('INVESTMENT_BANK', 'Investment Bank'), ('INSURANCE_FIRM', 'Insurance firm'), ('PRIVATE_EQUITY_FIRM', 'Private equity firm'), ('ASSET_MANAGEMENT_FIRM', 'Asset management firm'), ('NON_PROFIT', 'Non - Profit organization (e.g. Church, University etc.)')], max_length=100, null=True, verbose_name='Classification'),
        ),
        migrations.AlterField(
            model_name='investorventureinvolvement',
            name='investment_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('EQUITY', 'Shares/Equity'), ('DEBT_FINANCING', 'Debt financing')], max_length=100, verbose_name='Investment type'), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='investorventureinvolvement',
            name='loans_date',
            field=models.CharField(blank=True, max_length=20, verbose_name='Loan date'),
        ),
        migrations.AlterField(
            model_name='investorventureinvolvement',
            name='parent_relation',
            field=models.CharField(blank=True, choices=[('SUBSIDIARY', 'Subsidiary of parent company'), ('LOCAL_BRANCH', 'Local branch of parent company'), ('JOINT_VENTURE', 'Joint venture of parent companies')], max_length=100, null=True, verbose_name='Parent relation'),
        ),
        migrations.AlterField(
            model_name='investorventureinvolvement',
            name='role',
            field=models.CharField(choices=[('STAKEHOLDER', 'Parent company'), ('INVESTOR', 'Tertiary investor/lender')], max_length=100, verbose_name='Relation type'),
        ),
        migrations.AlterField(
            model_name='location',
            name='level_of_accuracy',
            field=models.CharField(blank=True, choices=[('COUNTRY', 'Country'), ('ADMINISTRATIVE_REGION', 'Administrative region'), ('APPROXIMATE_LOCATION', 'Approximate location'), ('EXACT_LOCATION', 'Exact location'), ('COORDINATES', 'Coordinates')], max_length=100, null=True),
        ),
    ]
