# Generated by Django 2.2.10 on 2020-03-02 15:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('greennewdeal', '0004_auto_20200218_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='file',
            field=models.FileField(blank=True, help_text='Maximum file size: 10MB', max_length=5000, null=True, upload_to='uploads', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='publication_title',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='url',
            field=models.URLField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='location',
            name='facility_name',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='location',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
