# Generated by Django 2.2.10 on 2020-03-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greennewdeal', '0005_auto_20200302_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='company',
            field=models.CharField(blank=True, max_length=500, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='name',
            field=models.CharField(blank=True, max_length=500, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='open_land_contracts_id',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='phone',
            field=models.CharField(blank=True, max_length=500, verbose_name='Phone'),
        ),
    ]
