# Generated by Django 2.2.12 on 2020-06-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greennewdeal', '0005_auto_20200603_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorventureinvolvement',
            name='draft_status',
            field=models.IntegerField(blank=True, choices=[(1, 'Draft'), (2, 'Review'), (3, 'Activation')], null=True),
        ),
        migrations.AlterField(
            model_name='investorventureinvolvement',
            name='status',
            field=models.IntegerField(choices=[(1, 'Draft'), (2, 'Live'), (3, 'Updated'), (4, 'Deleted'), (5, 'Rejected'), (6, 'To Delete?')], default=1),
        ),
    ]
