# Generated by Django 2.2.12 on 2020-06-05 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('greennewdeal', '0006_auto_20200604_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='operating_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='greennewdeal.Investor'),
        ),
        migrations.AlterField(
            model_name='investor',
            name='name',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Name'),
        ),
    ]
