# Generated by Django 2.2.13 on 2020-06-13 17:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('greennewdeal', '0007_auto_20200605_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='animals_export',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='animals_yield',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='crops_export',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='crops_yield',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='resources_export',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='resources_yield',
        ),
        migrations.AddField(
            model_name='investor',
            name='old_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='greennewdeal.Deal'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasources', to='greennewdeal.Deal'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='animals',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Livestock'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='crops',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Crops'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='resources',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Resources'),
        ),
        migrations.AlterField(
            model_name='investor',
            name='classification',
            field=models.CharField(blank=True, choices=[('GOVERNMENT', 'Government'), ('GOVERNMENT_INSTITUTION', 'Government institution'), ('STATE_OWNED_COMPANY', 'State-/government (owned) company'), ('SEMI_STATE_OWNED_COMPANY', 'Semi state-owned company'), ('ASSET_MANAGEMENT_FIRM', 'Asset management firm'), ('BILATERAL_DEVELOPMENT_BANK', 'Bilateral Development Bank / Development Finance Institution'), ('STOCK_EXCHANGE_LISTED_COMPANY', 'Stock-exchange listed company'), ('COMMERCIAL_BANK', 'Commercial Bank'), ('INSURANCE_FIRM', 'Insurance firm'), ('INVESTMENT_BANK', 'Investment Bank'), ('INVESTMENT_FUND', 'Investment fund'), ('MULTILATERAL_DEVELOPMENT_BANK', 'Multilateral Development Bank (MDB)'), ('PRIVATE_COMPANY', 'Private company'), ('PRIVATE_EQUITY_FIRM', 'Private equity firm'), ('INDIVIDUAL_ENTREPRENEUR', 'Individual entrepreneur'), ('NON_PROFIT', 'Non - Profit organization (e.g. Church, University etc.)'), ('OTHER', 'Other (please specify in comment field)')], max_length=100, null=True, verbose_name='Classification'),
        ),
        migrations.AlterField(
            model_name='investor',
            name='name',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='investorventureinvolvement',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventures', to='greennewdeal.Investor', verbose_name='Investor'),
        ),
        migrations.AlterField(
            model_name='location',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='greennewdeal.Deal'),
        ),
    ]
