# Generated by Django 2.2.13 on 2020-06-19 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greennewdeal', '0008_auto_20200613_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='fk_region',
            new_name='region',
        ),
    ]
