# Generated by Django 2.2.13 on 2020-06-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greennewdeal', '0010_auto_20200619_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='is_actually_unknown',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='investor',
            name='name',
            field=models.CharField(max_length=1024, verbose_name='Name'),
        ),
    ]
