# Generated by Django 2.2.13 on 2020-07-06 10:31

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('greennewdeal', '0012_auto_20200627_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='export',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Export'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='animals',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Livestock area/yield/export'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='animals_comment',
            field=models.TextField(blank=True, verbose_name='Comment on livestock'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='annual_leasing_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Annual leasing fee'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='annual_leasing_fee_comment',
            field=models.TextField(blank=True, verbose_name='Comment on leasing fee'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='annual_leasing_fee_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deal_annual_leasing_fee', to='greennewdeal.Currency', verbose_name='Annual leasing fee currency'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='annual_leasing_fee_type',
            field=models.CharField(blank=True, choices=[('PER_HA', 'per ha'), ('PER_AREA', 'for specified area')], max_length=100, null=True, verbose_name='Annual leasing fee area type'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='greennewdeal.Country', verbose_name='Target Country'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='crops',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Crops area/yield/export'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='crops_comment',
            field=models.TextField(blank=True, verbose_name='Comment on crops'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='current_negotiation_status',
            field=models.CharField(blank=True, choices=[('Intended', (('EXPRESSION_OF_INTEREST', 'Expression of interest'), ('UNDER_NEGOTIATION', 'Under negotiation'), ('MEMORANDUM_OF_UNDERSTANDING', 'Memorandum of understanding'))), ('Concluded', (('ORAL_AGREEMENT', 'Oral agreement'), ('CONTRACT_SIGNED', 'Contract signed'))), ('Failed', (('NEGOTIATIONS_FAILED', 'Negotiations failed'), ('CONTRACT_CANCELED', 'Contract canceled'))), ('CONTRACT_EXPIRED', 'Contract expired'), ('CHANGE_OF_OWNERSHIP', 'Change of ownership')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='displacement_of_people_comment',
            field=models.TextField(blank=True, verbose_name='Comment on displacement of people'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='domestic_use',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Domestic use'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='export_country1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='greennewdeal.Country', verbose_name='Country 1'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='export_country2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='greennewdeal.Country', verbose_name='Country 2'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='export_country3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='greennewdeal.Country', verbose_name='Country 3'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='former_land_cover',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, choices=[('CROPLAND', 'Cropland'), ('FOREST_LAND', 'Forest land'), ('PASTURE', 'Pasture'), ('RANGELAND', 'Shrub land/Grassland (Rangeland)'), ('MARGINAL_LAND', 'Marginal land'), ('WETLAND', 'Wetland'), ('OTHER_LAND', 'Other land (e.g. developed land – specify in comment field)')], null=True, size=None, verbose_name='Former land cover'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='former_land_owner',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, choices=[('STATE', 'State'), ('PRIVATE_SMALLHOLDERS', 'Private (smallholders)'), ('PRIVATE_LARGE_SCALE', 'Private (large-scale farm)'), ('COMMUNITY', 'Community'), ('INDIGENOUS_PEOPLE', 'Indigenous people'), ('OTHER', 'Other')], null=True, size=None, verbose_name='Former land owner'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='former_land_use',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, choices=[('COMMERCIAL_AGRICULTURE', 'Commercial (large-scale) agriculture'), ('SMALLHOLDER_AGRICULTURE', 'Smallholder agriculture'), ('SHIFTING_CULTIVATION', 'Shifting cultivation'), ('PASTORALISM', 'Pastoralism'), ('HUNTING_GATHERING', 'Hunting/Gathering'), ('FORESTRY', 'Forestry'), ('CONSERVATION', 'Conservation'), ('OTHER', 'Other')], null=True, size=None, verbose_name='Former land use'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='gender_related_information',
            field=models.TextField(blank=True, verbose_name='Comment on gender-related info'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='implementation_status',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, choices=[('PROJECT_NOT_STARTED', 'Project not started'), ('STARTUP_PHASE', 'Startup phase (no production)'), ('IN_OPERATION', 'In operation (production)'), ('PROJECT_ABANDONED', 'Project abandoned')], null=True, verbose_name='Implementation status'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='intended_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='ha', max_digits=12, null=True, verbose_name='Intended size (in ha)'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='intention_of_investment',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, choices=[('Agriculture', (('BIOFUELS', 'Biofuels'), ('FOOD_CROPS', 'Food crops'), ('FODDER', 'Fodder'), ('LIVESTOCK', 'Livestock'), ('NON_FOOD_AGRICULTURE', 'Non-food agricultural commodities'), ('AGRICULTURE_UNSPECIFIED', 'Agriculture unspecified'))), ('Forestry', (('TIMBER_PLANTATION', 'Timber plantation'), ('FOREST_LOGGING', 'Forest logging / management'), ('CARBON', 'For carbon sequestration/REDD'), ('FORESTRY_UNSPECIFIED', 'Forestry unspecified'))), ('Other', (('MINING', 'Mining'), ('OIL_GAS_EXTRACTION', 'Oil / Gas extraction'), ('TOURISM', 'Tourism'), ('INDUSTRY', 'Industry'), ('CONVERSATION', 'Conservation'), ('LAND_SPECULATION', 'Land speculation'), ('RENEWABLE_ENERGY', 'Renewable Energy'), ('OTHER', 'Other')))], null=True, verbose_name='Intention of investment'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='intention_of_investment_comment',
            field=models.TextField(blank=True, verbose_name='Comment on intention of investment'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='land_area_comment',
            field=models.TextField(blank=True, verbose_name='Comment on land area'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='materialized_benefits',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, verbose_name='Materialized benefits for local communities'), blank=True, choices=[('HEALTH', 'Health'), ('EDUCATION', 'Education'), ('PRODUCTIVE_INFRASTRUCTURE', 'Productive infrastructure (e.g. irrigation, tractors, machinery...)'), ('ROADS', 'Roads'), ('CAPACITY_BUILDING', 'Capacity Building'), ('FINANCIAL_SUPPORT', 'Financial Support'), ('COMMUNITY_SHARES', 'Community shares in the investment project'), ('OTHER', 'Other')], null=True, size=None),
        ),
        migrations.AlterField(
            model_name='deal',
            name='materialized_benefits_comment',
            field=models.TextField(blank=True, verbose_name='Comment on materialized benefits for local communities'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='nature_of_deal',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, verbose_name='Nature of the deal'), blank=True, choices=[('OUTRIGHT_PURCHASE', 'Outright Purchase'), ('LEASE', 'Lease'), ('CONCESSION', 'Concession'), ('EXPLOITATION_PERMIT', 'Exploitation permit / license / concession (for mineral resources)'), ('PURE_CONTRACT_FARMING', 'Pure contract farming')], null=True, size=None),
        ),
        migrations.AlterField(
            model_name='deal',
            name='negative_impacts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, verbose_name='Negative impacts for local communities'), blank=True, choices=[('ENVIRONMENTAL_DEGRADATION', 'Environmental degradation'), ('SOCIO_ECONOMIC', 'Socio-economic'), ('CULTURAL_LOSS', 'Cultural loss'), ('EVICTION', 'Eviction'), ('DISPLACEMENT', 'Displacement'), ('VIOLENCE', 'Violence'), ('OTHER', 'Other')], null=True, size=None),
        ),
        migrations.AlterField(
            model_name='deal',
            name='negotiation_status',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, choices=[('Intended', (('EXPRESSION_OF_INTEREST', 'Expression of interest'), ('UNDER_NEGOTIATION', 'Under negotiation'), ('MEMORANDUM_OF_UNDERSTANDING', 'Memorandum of understanding'))), ('Concluded', (('ORAL_AGREEMENT', 'Oral agreement'), ('CONTRACT_SIGNED', 'Contract signed'))), ('Failed', (('NEGOTIATIONS_FAILED', 'Negotiations failed'), ('CONTRACT_CANCELED', 'Contract canceled'))), ('CONTRACT_EXPIRED', 'Contract expired'), ('CHANGE_OF_OWNERSHIP', 'Change of ownership')], null=True, verbose_name='Negotiation status'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='off_the_lease_farmers',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='farmers', null=True, verbose_name='Not on leased / purchased farmers (out-grower)'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='off_the_lease_households',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='households', null=True, verbose_name='Not on leased / purchased households (out-grower)'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='on_the_lease_farmers',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='farmers', null=True, verbose_name='On leased / purchased farmers'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='on_the_lease_households',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='households', null=True, verbose_name='On leased / purchased households'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='project_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name of investment project'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='promised_benefits',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, verbose_name='Promised benefits for local communities'), blank=True, choices=[('HEALTH', 'Health'), ('EDUCATION', 'Education'), ('PRODUCTIVE_INFRASTRUCTURE', 'Productive infrastructure (e.g. irrigation, tractors, machinery...)'), ('ROADS', 'Roads'), ('CAPACITY_BUILDING', 'Capacity Building'), ('FINANCIAL_SUPPORT', 'Financial Support'), ('COMMUNITY_SHARES', 'Community shares in the investment project'), ('OTHER', 'Other')], null=True, size=None),
        ),
        migrations.AlterField(
            model_name='deal',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Purchase price'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='purchase_price_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deal_purchase_price', to='greennewdeal.Currency', verbose_name='Purchase price currency'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='purchase_price_type',
            field=models.CharField(blank=True, choices=[('PER_HA', 'per ha'), ('PER_AREA', 'for specified area')], max_length=100, null=True, verbose_name='Purchase price area type'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='recognition_status',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, verbose_name='Recognition status of community land tenure'), blank=True, choices=[('INDIGENOUS_RIGHTS_RECOGNIZED', 'Indigenous Peoples traditional or customary rights recognized by government'), ('INDIGENOUS_RIGHTS_NOT_RECOGNIZED', 'Indigenous Peoples traditional or customary rights not recognized by government'), ('COMMUNITY_RIGHTS_RECOGNIZED', 'Community traditional or customary rights recognized by government'), ('COMMUNITY_RIGHTS_NOT_RECOGNIZED', 'Community traditional or customary rights not recognized by government')], null=True, size=None),
        ),
        migrations.AlterField(
            model_name='deal',
            name='recognition_status_comment',
            field=models.TextField(blank=True, verbose_name='Comment on recognition status of community land tenure'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='resources',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Resources area/yield/export'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='resources_comment',
            field=models.TextField(blank=True, verbose_name='Comment on resources'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='source_of_water_extraction',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, choices=[('GROUNDWATER', 'Groundwater'), ('SURFACE_WATER', 'Surface water'), ('RIVER', 'River'), ('LAKE', 'Lake')], null=True, size=None, verbose_name='Source of water extraction'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='use_of_produce_comment',
            field=models.TextField(blank=True, verbose_name='Comment on use of produce'),
        ),
        migrations.AlterField(
            model_name='location',
            name='level_of_accuracy',
            field=models.CharField(blank=True, choices=[('COUNTRY', 'Country'), ('ADMINISTRATIVE_REGION', 'Administrative region'), ('APPROXIMATE_LOCATION', 'Approximate location'), ('EXACT_LOCATION', 'Exact location'), ('COORDINATES', 'Coordinates')], max_length=100, null=True, verbose_name='Spatial accuracy level'),
        ),
    ]
