# Generated by Django 4.2.7 on 2023-12-04 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='new_model.location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='dealversion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='new_model.dealversion2'),
        ),
    ]
