# Generated by Django 4.2.7 on 2023-11-16 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0013_alter_country_name_alter_currency_name_and_more'),
        ('new_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealhull',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='newModel_dealHulls', to='landmatrix.country', verbose_name='Target country'),
        ),
    ]
