# Generated by Django 4.2.7 on 2023-11-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealversion2',
            name='created_at',
            field=models.DateTimeField(blank=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='dealversion2',
            name='modified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Modified at'),
        ),
        migrations.AlterField(
            model_name='investorversion2',
            name='created_at',
            field=models.DateTimeField(blank=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='investorversion2',
            name='modified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Modified at'),
        ),
    ]
