# Generated by Django 4.2.7 on 2023-11-16 17:27

import apps.landmatrix.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_model', '0002_alter_dealhull_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorDataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nid', apps.landmatrix.models.fields.NanoIDField(db_index=True, max_length=15, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('MEDIA_REPORT', 'Media report'), ('RESEARCH_PAPER_OR_POLICY_REPORT', 'Research Paper / Policy Report'), ('GOVERNMENT_SOURCES', 'Government sources'), ('COMPANY_SOURCES', 'Company sources'), ('CONTRACT', 'Contract'), ('CONTRACT_FARMING_AGREEMENT', 'Contract (contract farming agreement)'), ('PERSONAL_INFORMATION', 'Personal information'), ('CROWDSOURCING', 'Crowdsourcing'), ('OTHER', 'Other (Please specify in comment field)')], verbose_name='Type')),
                ('url', models.URLField(blank=True, max_length=1000, verbose_name='Url')),
                ('file', models.FileField(blank=True, max_length=1000, null=True, upload_to='', verbose_name='File')),
                ('file_not_public', models.BooleanField(default=False, verbose_name='Keep PDF not public')),
                ('publication_title', models.CharField(blank=True, verbose_name='Publication title')),
                ('date', apps.landmatrix.models.fields.LooseDateField(blank=True, max_length=10, null=True, verbose_name='Date')),
                ('name', models.CharField(blank=True, verbose_name='Name')),
                ('company', models.CharField(blank=True, verbose_name='Organisation')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, verbose_name='Phone')),
                ('includes_in_country_verified_information', models.BooleanField(blank=True, null=True, verbose_name='Includes in-country-verified information')),
                ('open_land_contracts_id', models.CharField(blank=True, verbose_name='Open Contracting ID')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
            ],
        ),
        migrations.RenameModel(
            old_name='DataSource',
            new_name='DealDataSource',
        ),
        migrations.RenameIndex(
            model_name='dealdatasource',
            new_name='new_model_d_dealver_e212e3_idx',
            old_name='new_model_d_dealver_8782d3_idx',
        ),
        migrations.AlterField(
            model_name='investorversion2',
            name='name',
            field=models.CharField(blank=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='investordatasource',
            name='investorversion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='datasources', to='new_model.investorversion2'),
        ),
        migrations.AddIndex(
            model_name='investordatasource',
            index=models.Index(fields=['investorversion', 'nid'], name='new_model_i_investo_454271_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='investordatasource',
            unique_together={('investorversion', 'nid')},
        ),
    ]
