# Generated by Django 4.2.7 on 2023-11-21 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_model', '0002_alter_dealversion2_created_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='area',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='dealversion2',
            name='operating_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealversions', to='new_model.investorversion2'),
        ),
    ]
