# Generated by Django 4.2.7 on 2023-12-04 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_model', '0002_alter_area_location_alter_location_dealversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='dealversion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='new_model.dealversion2'),
        ),
        migrations.AlterField(
            model_name='dealdatasource',
            name='dealversion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasources', to='new_model.dealversion2'),
        ),
    ]
