# Generated by Django 4.2.7 on 2023-12-16 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0014_alter_deal_country_alter_deal_operating_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('new_model', '0003_alter_contract_dealversion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealhull',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='landmatrix.country', verbose_name='Target country'),
        ),
        migrations.CreateModel(
            name='InvestorWorkflowInfo2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_before', models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('REVIEW', 'Review'), ('ACTIVATION', 'Activation'), ('ACTIVATED', 'Activated'), ('REJECTED', 'OLD: Rejected'), ('TO_DELETE', 'OLD: To Delete')], null=True)),
                ('status_after', models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('REVIEW', 'Review'), ('ACTIVATION', 'Activation'), ('ACTIVATED', 'Activated'), ('REJECTED', 'OLD: Rejected'), ('TO_DELETE', 'OLD: To Delete')], null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.TextField(blank=True)),
                ('replies', models.JSONField(default=list, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflowinfos', to='new_model.investorhull')),
                ('investor_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflowinfos', to='new_model.investorversion2')),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DealWorkflowInfo2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_before', models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('REVIEW', 'Review'), ('ACTIVATION', 'Activation'), ('ACTIVATED', 'Activated'), ('REJECTED', 'OLD: Rejected'), ('TO_DELETE', 'OLD: To Delete')], null=True)),
                ('status_after', models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('REVIEW', 'Review'), ('ACTIVATION', 'Activation'), ('ACTIVATED', 'Activated'), ('REJECTED', 'OLD: Rejected'), ('TO_DELETE', 'OLD: To Delete')], null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.TextField(blank=True)),
                ('replies', models.JSONField(default=list, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflowinfos', to='new_model.dealhull')),
                ('deal_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflowinfos', to='new_model.dealversion2')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
