# Generated by Django 4.2.7 on 2023-12-16 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_model', '0004_alter_dealhull_country_investorworkflowinfo2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealversion2',
            old_name='reviewed_at',
            new_name='sent_to_activation_at',
        ),
        migrations.RenameField(
            model_name='dealversion2',
            old_name='reviewed_by',
            new_name='sent_to_activation_by',
        ),
        migrations.RenameField(
            model_name='investorversion2',
            old_name='reviewed_at',
            new_name='sent_to_activation_at',
        ),
        migrations.RenameField(
            model_name='investorversion2',
            old_name='reviewed_by',
            new_name='sent_to_activation_by',
        ),
    ]
