# Generated by Django 3.2.13 on 2022-06-29 15:17

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    replaces = [('message', '0001_initial'), ('message', '0002_auto_20201208_0931'), ('message', '0003_auto_20201208_1423'), ('message', '0004_message_sort_order'), ('message', '0005_auto_20201208_1522'), ('message', '0006_auto_20201209_1312')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('text', wagtail.fields.RichTextField(verbose_name='Text')),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=10, verbose_name='Level')),
                ('is_active', models.BooleanField(verbose_name='Is active')),
                ('expires_at', models.DateField(blank=True, help_text='After this date the message will not be displayed anymore', null=True, verbose_name='Expiration date')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('allow_users_to_hide', models.BooleanField(default=False, help_text='Store check off in cookie (expires in 365 days) so that users can choose to not display the messagea again.', verbose_name='Allow users to hide message')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['sort_order'],
            },
        ),
    ]
