# Generated by Django 2.2.17 on 2020-12-08 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='expires_at',
            field=models.DateField(blank=True, help_text='After this date the message will not be displayed anymore', null=True, verbose_name='Expiration date'),
        ),
        migrations.AddField(
            model_name='message',
            name='show_one_time_only',
            field=models.BooleanField(default=False, help_text='Store check off in cookie so that users only get to see this message one time', verbose_name='Show one time only'),
        ),
    ]
