# Generated by Django 2.2.17 on 2020-12-08 13:23

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20201208_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=wagtail.core.fields.RichTextField(verbose_name='Text'),
        ),
    ]
