# Generated by Django 2.2.17 on 2020-12-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_auto_20201208_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
