# Generated by Django 2.2.17 on 2020-12-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_message_sort_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['sort_order'], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.RemoveField(
            model_name='message',
            name='show_one_time_only',
        ),
        migrations.AddField(
            model_name='message',
            name='allow_users_to_hide',
            field=models.BooleanField(default=False, help_text='Store check off in cookie (expires in 365 days) so that users can choose to not display the messagea again.', verbose_name='Show one time only'),
        ),
    ]
