# Generated by Django 2.2.17 on 2020-12-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_auto_20201208_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='allow_users_to_hide',
            field=models.BooleanField(default=False, help_text='Store check off in cookie (expires in 365 days) so that users can choose to not display the messagea again.', verbose_name='Allow users to hide message'),
        ),
    ]
