# Generated by Django 4.2.7 on 2023-11-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_squashed_0006_auto_20201209_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='level',
            field=models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], default='info', verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(blank=True, null=True, verbose_name='Title'),
        ),
    ]
