# Generated by Django 5.0.4 on 2024-07-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0007_alter_message_level_alter_message_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='logged_in_only',
            field=models.BooleanField(default=False, verbose_name='Only display message to logged in users'),
        ),
    ]
