# Generated by Django 5.0.7 on 2024-09-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0008_message_logged_in_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='allow_users_to_hide',
            field=models.BooleanField(default=False, help_text='Store check off in cookie (expires in 365 days) so that users can choose to not display the message again.', verbose_name='Allow users to hide message'),
        ),
        migrations.AlterField(
            model_name='message',
            name='logged_in_only',
            field=models.BooleanField(default=False, verbose_name='Only display message to logged-in users'),
        ),
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(verbose_name='Title'),
        ),
    ]
