
export function mapValues(investor) {
  console.log(investor);
  return {
    id: "I36759",
    type: "investor",
    name: "Black River Asset Management",
    status: "overwritten",
    is_root: true,
    identifier: 36759,
    country: "Colombia",
    country_code: "CO",
    classification: "Private company",
    homepage: null,
    opencorporates_link: null,
    comment: null,
    url: "/investor/36759/",
    investors: [
      {
        id: "I146",
        type: "investor",
        name: "Cargill",
        status: "active",
        is_root: false,
        identifier: 146,
        country: "United States of America",
        country_code: "US",
        classification: "Private company",
        homepage: null,
        opencorporates_link: null,
        comment:
          "36 societies were created between 2010 and 2012 (with the same legal responsible) but were bought by Cargill in 2012. This strategy were built for the same lawyer buffet to avoid the farm land grabbing to Ripaila S.A",
        url: "/investor/146/",
        investors: [
          {
            id: "I36841",
            type: "investor",
            name: "PT Harapan Sawit Lestari",
            status: "active",
            is_root: false,
            identifier: 36841,
            country: "Indonesia",
            country_code: "ID",
            classification: "Private company",
            homepage: null,
            opencorporates_link: null,
            comment: null,
            url: "/investor/36841/",
            investors: [],
            deals: [
              {
                id: "D3497",
                type: "deal",
                name: "3497",
                status: "overwritten",
                identifier: 3497,
                country: "Indonesia",
                country_code: "ID",
                intention: "Agriculture unspecified",
                nature: "Concession",
                negotiation_status: "Contract signed",
                implementation_status: "In operation (production)",
                intended_size: 0,
                contract_size: 5137,
                production_size: 3884,
                url: "/deal/3497/",
              },
            ],
            involvement: {
              dir: "parent",
              type: "parent",
              percentage: 100,
              investment_type: "",
              loans_amount: null,
              loans_currency: "None",
              loans_date: null,
              parent_relation: null,
              comment: null,
            },
          },
          {
            id: "I37575",
            type: "investor",
            name: "PT Hindoli",
            status: "active",
            is_root: false,
            identifier: 37575,
            country: "Indonesia",
            country_code: "ID",
            classification: "Private company",
            homepage: null,
            opencorporates_link: null,
            comment: null,
            url: "/investor/37575/",
            investors: [],
            deals: [
              {
                id: "D3499",
                type: "deal",
                name: "3499",
                status: "overwritten",
                identifier: 3499,
                country: "Indonesia",
                country_code: "ID",
                intention: "Agriculture unspecified",
                nature: "Concession",
                negotiation_status: "Contract signed",
                implementation_status: "In operation (production)",
                intended_size: 0,
                contract_size: 9555,
                production_size: 9479,
                url: "/deal/3499/",
              },
            ],
            involvement: {
              dir: "parent",
              type: "parent",
              percentage: 100,
              investment_type: "",
              loans_amount: null,
              loans_currency: "None",
              loans_date: null,
              parent_relation: null,
              comment: null,
            },
          },
          {
            id: "I39776",
            type: "investor",
            name: "Unknown (Cargill Cameroon)",
            status: "active",
            is_root: false,
            identifier: 39776,
            country: "Cameroon",
            country_code: "CM",
            classification: "Private company",
            homepage: null,
            opencorporates_link: null,
            comment: null,
            url: "/investor/39776/",
            investors: [],
            deals: [
              {
                id: "D3202",
                type: "deal",
                name: "3202",
                status: "overwritten",
                identifier: 3202,
                country: "Cameroon",
                country_code: "CM",
                intention: "Agriculture unspecified",
                nature: "Lease",
                negotiation_status: "Negotiations failed",
                implementation_status: null,
                intended_size: 50000,
                contract_size: 0,
                production_size: 0,
                url: "/deal/3202/",
              },
            ],
            involvement: {
              dir: "parent",
              type: "parent",
              percentage: 100,
              investment_type: "",
              loans_amount: null,
              loans_currency: "None",
              loans_date: null,
              parent_relation: null,
              comment: null,
            },
          },
          {
            id: "I39777",
            type: "investor",
            name: "Telcar Cocoa Ltd",
            status: "active",
            is_root: false,
            identifier: 39777,
            country: "Cameroon",
            country_code: "CM",
            classification: "Private company",
            homepage: null,
            opencorporates_link: null,
            comment: null,
            url: "/investor/39777/",
            investors: [
              {
                id: "I5006",
                type: "investor",
                name: "Kate Kanyi Fotso Tometi",
                status: "active",
                is_root: false,
                identifier: 5006,
                country: "Cameroon",
                country_code: "CM",
                classification: "Individual entrepreneur",
                homepage: null,
                opencorporates_link: null,
                comment: null,
                url: "/investor/5006/",
                investors: [],
                deals: [],
                involvement: {
                  dir: "child",
                  type: "parent",
                  percentage: null,
                  investment_type: "",
                  loans_amount: null,
                  loans_currency: "None",
                  loans_date: null,
                  parent_relation: null,
                  comment: null,
                },
              },
            ],
            deals: [
              {
                id: "D6000",
                type: "deal",
                name: "6000",
                status: "active",
                identifier: 6000,
                country: "Cameroon",
                country_code: "CM",
                intention: "Food crops",
                nature: null,
                negotiation_status: "Contract signed",
                implementation_status: "Startup phase (no production)",
                intended_size: 0,
                contract_size: 0,
                production_size: 0,
                url: "/deal/6000/",
              },
            ],
            involvement: {
              dir: "parent",
              type: "parent",
              percentage: null,
              investment_type: "",
              loans_amount: null,
              loans_currency: "None",
              loans_date: null,
              parent_relation: null,
              comment: null,
            },
          },
          {
            id: "I40901",
            type: "investor",
            name: "Colombia Agro SAS",
            status: "overwritten",
            is_root: false,
            identifier: 40901,
            country: "Colombia",
            country_code: "CO",
            classification: "Private company",
            homepage: "",
            opencorporates_link: "",
            comment: "",
            url: "/investor/40901/",
            investors: [
              {
                id: "I40904",
                type: "investor",
                name: "Unknown_Cargill",
                status: "overwritten",
                is_root: false,
                identifier: 40904,
                country: "Colombia",
                country_code: "CO",
                classification: "Private company",
                homepage: "",
                opencorporates_link: "",
                comment:
                  'Cargill, being advised by the law firm Brigard & Urrutia, created a "fictional" firm to acquire land that was previously allocated to landless peasants by the state under law 160 of 1994. To circumvent local legislation, they created a firm for every plot they bought and let them liquidate later, after they had made long-term renting agreements with the superior companies. Source 14 - Deal 3107',
                url: "/investor/40904/",
                investors: [],
                deals: [],
                involvement: {
                  dir: "parent",
                  type: "parent",
                  percentage: null,
                  investment_type: "",
                  loans_amount: null,
                  loans_currency: "None",
                  loans_date: "",
                  parent_relation: null,
                  comment: "",
                },
              },
            ],
            deals: [],
            involvement: {
              dir: "parent",
              type: "parent",
              percentage: null,
              investment_type: "",
              loans_amount: null,
              loans_currency: "None",
              loans_date: "",
              parent_relation: null,
              comment: "",
            },
          },
          {
            id: "I40902",
            type: "investor",
            name: "Cargill Trading Colombia",
            status: "overwritten",
            is_root: false,
            identifier: 40902,
            country: "Colombia",
            country_code: "CO",
            classification: "Private company",
            homepage: "",
            opencorporates_link: "",
            comment: "",
            url: "/investor/40902/",
            investors: [
              {
                id: "I40904",
                type: "investor",
                name: "Unknown_Cargill",
                status: "overwritten",
                is_root: false,
                identifier: 40904,
                country: "Colombia",
                country_code: "CO",
                classification: "Private company",
                homepage: "",
                opencorporates_link: "",
                comment:
                  'Cargill, being advised by the law firm Brigard & Urrutia, created a "fictional" firm to acquire land that was previously allocated to landless peasants by the state under law 160 of 1994. To circumvent local legislation, they created a firm for every plot they bought and let them liquidate later, after they had made long-term renting agreements with the superior companies. Source 14 - Deal 3107',
                url: "/investor/40904/",
                investors: [],
                deals: [],
                involvement: {
                  dir: "parent",
                  type: "parent",
                  percentage: null,
                  investment_type: "",
                  loans_amount: null,
                  loans_currency: "None",
                  loans_date: "",
                  parent_relation: null,
                  comment: "",
                },
              },
            ],
            deals: [],
            involvement: {
              dir: "parent",
              type: "parent",
              percentage: null,
              investment_type: "",
              loans_amount: null,
              loans_currency: "None",
              loans_date: "",
              parent_relation: null,
              comment: "",
            },
          },
          {
            id: "I40903",
            type: "investor",
            name: "Cargill de Colombia",
            status: "overwritten",
            is_root: false,
            identifier: 40903,
            country: "Colombia",
            country_code: "CO",
            classification: "Private company",
            homepage: "",
            opencorporates_link:
              "https://www.bloomberg.com/research/stocks/private/snapshot.asp?privcapId=323641301",
            comment: "",
            url: "/investor/40903/",
            investors: [
              {
                id: "I40904",
                type: "investor",
                name: "Unknown_Cargill",
                status: "overwritten",
                is_root: false,
                identifier: 40904,
                country: "Colombia",
                country_code: "CO",
                classification: "Private company",
                homepage: "",
                opencorporates_link: "",
                comment:
                  'Cargill, being advised by the law firm Brigard & Urrutia, created a "fictional" firm to acquire land that was previously allocated to landless peasants by the state under law 160 of 1994. To circumvent local legislation, they created a firm for every plot they bought and let them liquidate later, after they had made long-term renting agreements with the superior companies. Source 14 - Deal 3107',
                url: "/investor/40904/",
                investors: [],
                deals: [],
                involvement: {
                  dir: "parent",
                  type: "parent",
                  percentage: null,
                  investment_type: "",
                  loans_amount: null,
                  loans_currency: "None",
                  loans_date: "",
                  parent_relation: null,
                  comment: "",
                },
              },
            ],
            deals: [],
            involvement: {
              dir: "parent",
              type: "parent",
              percentage: null,
              investment_type: "",
              loans_amount: null,
              loans_currency: "None",
              loans_date: "",
              parent_relation: null,
              comment: "",
            },
          },
          {
            id: "I41752",
            type: "investor",
            name: "PT. MAYA AGRO INVESTAMA",
            status: "active",
            is_root: false,
            identifier: 41752,
            country: "Indonesia",
            country_code: "ID",
            classification: "Private company",
            homepage: null,
            opencorporates_link: "https://www.cargill.co.id",
            comment: "",
            url: "/investor/41752/",
            investors: [],
            deals: [
              {
                id: "D7507",
                type: "deal",
                name: "7507",
                status: "active",
                identifier: 7507,
                country: "Indonesia",
                country_code: "ID",
                intention: "Non-food agricultural commodities",
                nature: "Concession",
                negotiation_status: "Contract signed",
                implementation_status: "In operation (production)",
                intended_size: 0,
                contract_size: 12948,
                production_size: 7426,
                url: "/deal/7507/",
              },
            ],
            involvement: {
              dir: "parent",
              type: "parent",
              percentage: null,
              investment_type: "",
              loans_amount: null,
              loans_currency: "None",
              loans_date: null,
              parent_relation: null,
              comment: "",
            },
          },
          {
            id: "I41799",
            type: "investor",
            name: "PT. Andes Agro Investama",
            status: "active",
            is_root: false,
            identifier: 41799,
            country: "Indonesia",
            country_code: "ID",
            classification: "Private company",
            homepage: null,
            opencorporates_link: "https://www.cargill.co.id/",
            comment: "",
            url: "/investor/41799/",
            investors: [],
            deals: [
              {
                id: "D7583",
                type: "deal",
                name: "7583",
                status: "active",
                identifier: 7583,
                country: "Indonesia",
                country_code: "ID",
                intention: "Agriculture unspecified",
                nature: "Concession",
                negotiation_status: "Contract signed",
                implementation_status: "In operation (production)",
                intended_size: 0,
                contract_size: 13310,
                production_size: 10609,
                url: "/deal/7583/",
              },
            ],
            involvement: {
              dir: "parent",
              type: "parent",
              percentage: null,
              investment_type: "",
              loans_amount: null,
              loans_currency: "None",
              loans_date: null,
              parent_relation: "Subsidiary of parent company",
              comment: "",
            },
          },
          {
            id: "I42443",
            type: "investor",
            name: "PT. Harapan Hibrida Kalbar",
            status: "active",
            is_root: false,
            identifier: 42443,
            country: "Indonesia",
            country_code: "ID",
            classification: "Private company",
            homepage: null,
            opencorporates_link: null,
            comment: "",
            url: "/investor/42443/",
            investors: [],
            deals: [
              {
                id: "D7933",
                type: "deal",
                name: "7933",
                status: "active",
                identifier: 7933,
                country: "Indonesia",
                country_code: "ID",
                intention: "Non-food agricultural commodities",
                nature: "Lease",
                negotiation_status: "Contract signed",
                implementation_status: "In operation (production)",
                intended_size: 0,
                contract_size: 9849,
                production_size: 0,
                url: "/deal/7933/",
              },
            ],
            involvement: {
              dir: "parent",
              type: "parent",
              percentage: null,
              investment_type: "",
              loans_amount: null,
              loans_currency: "None",
              loans_date: null,
              parent_relation: null,
              comment: "",
            },
          },
        ],
        deals: [],
        involvement: {
          dir: "child",
          type: "parent",
          percentage: null,
          investment_type: "",
          loans_amount: null,
          loans_currency: "None",
          loans_date: null,
          parent_relation: null,
          comment: null,
        },
      },
      {
        id: "I40904",
        type: "investor",
        name: "Unknown_Cargill",
        status: "overwritten",
        is_root: false,
        identifier: 40904,
        country: "Colombia",
        country_code: "CO",
        classification: "Private company",
        homepage: "",
        opencorporates_link: "",
        comment:
          'Cargill, being advised by the law firm Brigard & Urrutia, created a "fictional" firm to acquire land that was previously allocated to landless peasants by the state under law 160 of 1994. To circumvent local legislation, they created a firm for every plot they bought and let them liquidate later, after they had made long-term renting agreements with the superior companies. Source 14 - Deal 3107',
        url: "/investor/40904/",
        investors: [],
        deals: [
          {
            id: "D3107",
            type: "deal",
            name: "3107",
            status: "overwritten",
            identifier: 3107,
            country: "Colombia",
            country_code: "CO",
            intention: "Non-food agricultural commodities",
            nature: "Outright Purchase",
            negotiation_status: "Contract signed",
            implementation_status: "Startup phase (no production)",
            intended_size: 0,
            contract_size: 52576,
            production_size: 0,
            url: "/deal/3107/",
          },
        ],
        involvement: {
          dir: "parent",
          type: "parent",
          percentage: null,
          investment_type: "",
          loans_amount: null,
          loans_currency: "None",
          loans_date: "",
          parent_relation: null,
          comment: "",
        },
      },
    ],
    deals: [
      {
        id: "D3890",
        type: "deal",
        name: "3890",
        status: "overwritten",
        identifier: 3890,
        country: "Colombia",
        country_code: "CO",
        intention: "Food crops",
        nature: "Outright Purchase",
        negotiation_status: "Contract signed",
        implementation_status: "In operation (production)",
        intended_size: 0,
        contract_size: 52570,
        production_size: 52570,
        url: "/deal/3890/",
      },
    ],
  };
  // return {
  //   id: `I${investor.id}`,
  //   type: "investor",
  //   name: "Black River Asset Management",
  //   status: "overwritten",
  //   is_root: true,
  //   identifier: 36759,
  //   country: "Colombia",
  //   country_code: "CO",
  //   classification: "Private company",
  //   homepage: null,
  //   opencorporates_link: null,
  //   comment: null,
  //   url: "/investor/36759/",
  //   investors: [],
  //   deals: [],
  // };
}
