# Generated by Django 2.2.17 on 2020-12-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcms', '0001_squashed_0017_auto_20201225_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observatorypage',
            name='introduction_text',
            field=models.CharField(blank=True, help_text="Introduction before 'Read more'", max_length=700),
        ),
        migrations.AlterField(
            model_name='observatorypage',
            name='twitter_username',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
