# Generated by Django 4.2.3 on 2023-10-16 11:22

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcms', '0003_remove_chartdescriptionssettings_site_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartdescriptionssettings',
            name='global_web_of_investments',
            field=wagtail.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chartdescriptionssettings',
            name='global_web_of_investments_en',
            field=wagtail.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='chartdescriptionssettings',
            name='global_web_of_investments_es',
            field=wagtail.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='chartdescriptionssettings',
            name='global_web_of_investments_fr',
            field=wagtail.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='chartdescriptionssettings',
            name='global_web_of_investments_ru',
            field=wagtail.fields.RichTextField(null=True),
        ),
    ]
