# Generated by Django 4.2.7 on 2023-11-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcms', '0004_chartdescriptionssettings_global_web_of_investments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observatorypage',
            name='twitter_username',
            field=models.CharField(blank=True),
        ),
    ]
