# Generated by Django 2.2.14 on 2020-09-28 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcms', '0004_auto_20200928_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionpage',
            name='region',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='landmatrix.Region'),
        ),
    ]
