# Generated by Django 2.2.16 on 2020-10-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcms', '0005_auto_20200928_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrypage',
            name='short_description',
            field=models.CharField(blank=True, help_text='Displayed in sidebar of map', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='regionpage',
            name='short_description',
            field=models.CharField(blank=True, help_text='Displayed in sidebar of map', max_length=200, null=True),
        ),
    ]
