# Generated by Django 4.2.6 on 2023-10-18 08:53

import apps.wagtailcms.blocks
from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('wagtailcms', '0005_homepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('image_text_block', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('subtitle', wagtail.blocks.CharBlock(required=False)), ('text', apps.wagtailcms.blocks.RichTextBlock(required=False)), ('link', wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(label='Interne Seite', required=False)), ('external_url', wagtail.blocks.URLBlock(help_text='Die externe URL wird nur verwendet, wenn keine interne Seite im vorigen Feld gesetzt ist', label='Externe URL', required=False)), ('text', wagtail.blocks.CharBlock(default='click here', label='Button-Text', required=False))], required=False)), ('image', apps.wagtailcms.blocks.ImageBlock())])), ('latest_resources', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('subtitle', wagtail.blocks.CharBlock(required=False)), ('categories', wagtail.blocks.ListBlock(wagtail.snippets.blocks.SnippetChooserBlock('blog.BlogCategory')))])), ('data_teaser', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('subtitle', wagtail.blocks.CharBlock(required=False)), ('cards', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=200, required=False)), ('teaser', wagtail.blocks.CharBlock(max_length=200, required=False)), ('link', wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(label='Interne Seite', required=False)), ('external_url', wagtail.blocks.URLBlock(help_text='Die externe URL wird nur verwendet, wenn keine interne Seite im vorigen Feld gesetzt ist', label='Externe URL', required=False)), ('text', wagtail.blocks.CharBlock(default='click here', label='Button-Text', required=False))], required=False))]), help_text='Icons: 1.Maps, 2.Charts, 3.Tables', max_num=3, min_num=3))])), ('dealcount', wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock(default="It's a big deal"))]))], use_json_field=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body_en',
            field=wagtail.fields.StreamField([('image_text_block', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('subtitle', wagtail.blocks.CharBlock(required=False)), ('text', apps.wagtailcms.blocks.RichTextBlock(required=False)), ('link', wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(label='Interne Seite', required=False)), ('external_url', wagtail.blocks.URLBlock(help_text='Die externe URL wird nur verwendet, wenn keine interne Seite im vorigen Feld gesetzt ist', label='Externe URL', required=False)), ('text', wagtail.blocks.CharBlock(default='click here', label='Button-Text', required=False))], required=False)), ('image', apps.wagtailcms.blocks.ImageBlock())])), ('latest_resources', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('subtitle', wagtail.blocks.CharBlock(required=False)), ('categories', wagtail.blocks.ListBlock(wagtail.snippets.blocks.SnippetChooserBlock('blog.BlogCategory')))])), ('data_teaser', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('subtitle', wagtail.blocks.CharBlock(required=False)), ('cards', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=200, required=False)), ('teaser', wagtail.blocks.CharBlock(max_length=200, required=False)), ('link', wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(label='Interne Seite', required=False)), ('external_url', wagtail.blocks.URLBlock(help_text='Die externe URL wird nur verwendet, wenn keine interne Seite im vorigen Feld gesetzt ist', label='Externe URL', required=False)), ('text', wagtail.blocks.CharBlock(default='click here', label='Button-Text', required=False))], required=False))]), help_text='Icons: 1.Maps, 2.Charts, 3.Tables', max_num=3, min_num=3))])), ('dealcount', wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock(default="It's a big deal"))]))], null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body_es',
            field=wagtail.fields.StreamField([('image_text_block', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('subtitle', wagtail.blocks.CharBlock(required=False)), ('text', apps.wagtailcms.blocks.RichTextBlock(required=False)), ('link', wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(label='Interne Seite', required=False)), ('external_url', wagtail.blocks.URLBlock(help_text='Die externe URL wird nur verwendet, wenn keine interne Seite im vorigen Feld gesetzt ist', label='Externe URL', required=False)), ('text', wagtail.blocks.CharBlock(default='click here', label='Button-Text', required=False))], required=False)), ('image', apps.wagtailcms.blocks.ImageBlock())])), ('latest_resources', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('subtitle', wagtail.blocks.CharBlock(required=False)), ('categories', wagtail.blocks.ListBlock(wagtail.snippets.blocks.SnippetChooserBlock('blog.BlogCategory')))])), ('data_teaser', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('subtitle', wagtail.blocks.CharBlock(required=False)), ('cards', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=200, required=False)), ('teaser', wagtail.blocks.CharBlock(max_length=200, required=False)), ('link', wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(label='Interne Seite', required=False)), ('external_url', wagtail.blocks.URLBlock(help_text='Die externe URL wird nur verwendet, wenn keine interne Seite im vorigen Feld gesetzt ist', label='Externe URL', required=False)), ('text', wagtail.blocks.CharBlock(default='click here', label='Button-Text', required=False))], required=False))]), help_text='Icons: 1.Maps, 2.Charts, 3.Tables', max_num=3, min_num=3))])), ('dealcount', wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock(default="It's a big deal"))]))], null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body_fr',
            field=wagtail.fields.StreamField([('image_text_block', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('subtitle', wagtail.blocks.CharBlock(required=False)), ('text', apps.wagtailcms.blocks.RichTextBlock(required=False)), ('link', wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(label='Interne Seite', required=False)), ('external_url', wagtail.blocks.URLBlock(help_text='Die externe URL wird nur verwendet, wenn keine interne Seite im vorigen Feld gesetzt ist', label='Externe URL', required=False)), ('text', wagtail.blocks.CharBlock(default='click here', label='Button-Text', required=False))], required=False)), ('image', apps.wagtailcms.blocks.ImageBlock())])), ('latest_resources', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('subtitle', wagtail.blocks.CharBlock(required=False)), ('categories', wagtail.blocks.ListBlock(wagtail.snippets.blocks.SnippetChooserBlock('blog.BlogCategory')))])), ('data_teaser', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('subtitle', wagtail.blocks.CharBlock(required=False)), ('cards', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=200, required=False)), ('teaser', wagtail.blocks.CharBlock(max_length=200, required=False)), ('link', wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(label='Interne Seite', required=False)), ('external_url', wagtail.blocks.URLBlock(help_text='Die externe URL wird nur verwendet, wenn keine interne Seite im vorigen Feld gesetzt ist', label='Externe URL', required=False)), ('text', wagtail.blocks.CharBlock(default='click here', label='Button-Text', required=False))], required=False))]), help_text='Icons: 1.Maps, 2.Charts, 3.Tables', max_num=3, min_num=3))])), ('dealcount', wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock(default="It's a big deal"))]))], null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body_ru',
            field=wagtail.fields.StreamField([('image_text_block', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('subtitle', wagtail.blocks.CharBlock(required=False)), ('text', apps.wagtailcms.blocks.RichTextBlock(required=False)), ('link', wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(label='Interne Seite', required=False)), ('external_url', wagtail.blocks.URLBlock(help_text='Die externe URL wird nur verwendet, wenn keine interne Seite im vorigen Feld gesetzt ist', label='Externe URL', required=False)), ('text', wagtail.blocks.CharBlock(default='click here', label='Button-Text', required=False))], required=False)), ('image', apps.wagtailcms.blocks.ImageBlock())])), ('latest_resources', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('subtitle', wagtail.blocks.CharBlock(required=False)), ('categories', wagtail.blocks.ListBlock(wagtail.snippets.blocks.SnippetChooserBlock('blog.BlogCategory')))])), ('data_teaser', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('subtitle', wagtail.blocks.CharBlock(required=False)), ('cards', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=200, required=False)), ('teaser', wagtail.blocks.CharBlock(max_length=200, required=False)), ('link', wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(label='Interne Seite', required=False)), ('external_url', wagtail.blocks.URLBlock(help_text='Die externe URL wird nur verwendet, wenn keine interne Seite im vorigen Feld gesetzt ist', label='Externe URL', required=False)), ('text', wagtail.blocks.CharBlock(default='click here', label='Button-Text', required=False))], required=False))]), help_text='Icons: 1.Maps, 2.Charts, 3.Tables', max_num=3, min_num=3))])), ('dealcount', wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock(default="It's a big deal"))]))], null=True, use_json_field=True),
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('DONORS', 'Donors'), ('PARTNERS', 'Partners')])),
                ('homepage', models.URLField(blank=True)),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Partner, Förderer, Unterstützer',
                'verbose_name_plural': 'Partner, Förderer, Unterstützer',
            },
        ),
    ]
