# Generated by Django 2.2.16 on 2020-10-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcms', '0006_auto_20201008_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrypage',
            name='short_description_en',
            field=models.CharField(blank=True, help_text='Displayed in sidebar of map', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='countrypage',
            name='short_description_es',
            field=models.CharField(blank=True, help_text='Displayed in sidebar of map', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='countrypage',
            name='short_description_fr',
            field=models.CharField(blank=True, help_text='Displayed in sidebar of map', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='regionpage',
            name='short_description_en',
            field=models.CharField(blank=True, help_text='Displayed in sidebar of map', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='regionpage',
            name='short_description_es',
            field=models.CharField(blank=True, help_text='Displayed in sidebar of map', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='regionpage',
            name='short_description_fr',
            field=models.CharField(blank=True, help_text='Displayed in sidebar of map', max_length=200, null=True),
        ),
    ]
