# Generated by Django 2.2.16 on 2020-10-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcms', '0007_auto_20201008_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrypage',
            name='introduction_text',
            field=models.TextField(blank=True, help_text="Introduction before 'Read more'", max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='countrypage',
            name='introduction_text_en',
            field=models.TextField(blank=True, help_text="Introduction before 'Read more'", max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='countrypage',
            name='introduction_text_es',
            field=models.TextField(blank=True, help_text="Introduction before 'Read more'", max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='countrypage',
            name='introduction_text_fr',
            field=models.TextField(blank=True, help_text="Introduction before 'Read more'", max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='regionpage',
            name='introduction_text',
            field=models.TextField(blank=True, help_text="Introduction before 'Read more'", max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='regionpage',
            name='introduction_text_en',
            field=models.TextField(blank=True, help_text="Introduction before 'Read more'", max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='regionpage',
            name='introduction_text_es',
            field=models.TextField(blank=True, help_text="Introduction before 'Read more'", max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='regionpage',
            name='introduction_text_fr',
            field=models.TextField(blank=True, help_text="Introduction before 'Read more'", max_length=700, null=True),
        ),
    ]
