# Generated by Django 4.2.7 on 2023-11-14 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcms', '0007_alter_wagtailrootpage_body_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePage',
        ),
    ]
