# Generated by Django 2.2.16 on 2020-10-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcms', '0009_regionpage_twitter_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrypage',
            name='twitter_username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
