# Generated by Django 5.0 on 2024-01-05 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcms', '0009_alter_wagtailpage_body_alter_wagtailpage_body_en_and_more'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['sort_order']},
        ),
        migrations.RemoveField(
            model_name='partner',
            name='category',
        ),
        migrations.AddField(
            model_name='partner',
            name='role',
            field=models.CharField(choices=[('PARTNER', 'Partner'), ('DONOR', 'Donor')], default='PARTNER'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='homepage',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
