# Generated by Django 2.2.17 on 2020-11-30 14:50

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0041_group_collection_permissions_verbose_name_plural"),
        ("wagtailcms", "0011_observatoryindexpage_observatorypage"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChartDescriptionsSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("web_of_transnational_deals", wagtail.core.fields.RichTextField()),
                ("dynamics_overview", wagtail.core.fields.RichTextField()),
                ("produce_info_map", wagtail.core.fields.RichTextField()),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.Site",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
