# Generated by Django 2.2.17 on 2020-12-05 11:37

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcms", "0013_auto_20201204_1215"),
    ]

    operations = [
        migrations.AddField(
            model_name="chartdescriptionssettings",
            name="dynamics_overview_en",
            field=wagtail.core.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name="chartdescriptionssettings",
            name="dynamics_overview_es",
            field=wagtail.core.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name="chartdescriptionssettings",
            name="dynamics_overview_fr",
            field=wagtail.core.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name="chartdescriptionssettings",
            name="produce_info_map_en",
            field=wagtail.core.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name="chartdescriptionssettings",
            name="produce_info_map_es",
            field=wagtail.core.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name="chartdescriptionssettings",
            name="produce_info_map_fr",
            field=wagtail.core.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name="chartdescriptionssettings",
            name="web_of_transnational_deals_en",
            field=wagtail.core.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name="chartdescriptionssettings",
            name="web_of_transnational_deals_es",
            field=wagtail.core.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name="chartdescriptionssettings",
            name="web_of_transnational_deals_fr",
            field=wagtail.core.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name="observatorypage",
            name="country",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="observatory_page_id",
                to="landmatrix.Country",
            ),
        ),
        migrations.AlterField(
            model_name="observatorypage",
            name="region",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="observatory_page_id",
                to="landmatrix.Region",
            ),
        ),
    ]
