# Generated by Django 2.2.17 on 2020-12-25 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcms', '0016_auto_20201214_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wagtailrootpage',
            name='data_introduction',
        ),
        migrations.RemoveField(
            model_name='wagtailrootpage',
            name='data_introduction_en',
        ),
        migrations.RemoveField(
            model_name='wagtailrootpage',
            name='data_introduction_es',
        ),
        migrations.RemoveField(
            model_name='wagtailrootpage',
            name='data_introduction_fr',
        ),
        migrations.RemoveField(
            model_name='wagtailrootpage',
            name='footer_column_1',
        ),
        migrations.RemoveField(
            model_name='wagtailrootpage',
            name='footer_column_1_en',
        ),
        migrations.RemoveField(
            model_name='wagtailrootpage',
            name='footer_column_1_es',
        ),
        migrations.RemoveField(
            model_name='wagtailrootpage',
            name='footer_column_1_fr',
        ),
        migrations.RemoveField(
            model_name='wagtailrootpage',
            name='footer_column_2',
        ),
        migrations.RemoveField(
            model_name='wagtailrootpage',
            name='footer_column_2_en',
        ),
        migrations.RemoveField(
            model_name='wagtailrootpage',
            name='footer_column_2_es',
        ),
        migrations.RemoveField(
            model_name='wagtailrootpage',
            name='footer_column_2_fr',
        ),
        migrations.RemoveField(
            model_name='wagtailrootpage',
            name='footer_column_3',
        ),
        migrations.RemoveField(
            model_name='wagtailrootpage',
            name='footer_column_3_en',
        ),
        migrations.RemoveField(
            model_name='wagtailrootpage',
            name='footer_column_3_es',
        ),
        migrations.RemoveField(
            model_name='wagtailrootpage',
            name='footer_column_3_fr',
        ),
        migrations.RemoveField(
            model_name='wagtailrootpage',
            name='footer_column_4',
        ),
        migrations.RemoveField(
            model_name='wagtailrootpage',
            name='footer_column_4_en',
        ),
        migrations.RemoveField(
            model_name='wagtailrootpage',
            name='footer_column_4_es',
        ),
        migrations.RemoveField(
            model_name='wagtailrootpage',
            name='footer_column_4_fr',
        ),
        migrations.RemoveField(
            model_name='wagtailrootpage',
            name='map_introduction',
        ),
        migrations.RemoveField(
            model_name='wagtailrootpage',
            name='map_introduction_en',
        ),
        migrations.RemoveField(
            model_name='wagtailrootpage',
            name='map_introduction_es',
        ),
        migrations.RemoveField(
            model_name='wagtailrootpage',
            name='map_introduction_fr',
        ),
    ]
