# Generated by Django 3.2.14 on 2022-07-16 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0001_squashed_0057_auto_20220617_2213'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='confidential_reason',
        ),
        migrations.AlterField(
            model_name='deal',
            name='annual_leasing_fee_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='landmatrix.currency', verbose_name='Annual leasing fee currency'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='purchase_price_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='landmatrix.currency', verbose_name='Purchase price currency'),
        ),
    ]
