# Generated by Django 3.2.14 on 2022-08-21 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0002_auto_20220716_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='fk_region',
            new_name='region',
        ),
    ]
