# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-31 12:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0002_auto_20170525_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='fully_updated',
            new_name='fully_updated_date',
        ),
    ]
