# Generated by Django 4.0.7 on 2022-09-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0003_rename_fk_region_country_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealworkflowinfo',
            old_name='processed_by_receiver',
            new_name='resolved',
        ),
        migrations.RenameField(
            model_name='investorworkflowinfo',
            old_name='processed_by_receiver',
            new_name='resolved',
        ),
        migrations.AddField(
            model_name='dealworkflowinfo',
            name='replies',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investorworkflowinfo',
            name='replies',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='top_investors',
            field=models.ManyToManyField(related_name='+', to='landmatrix.investor', verbose_name='Top parent companies'),
        ),
    ]
