# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-13 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0004_auto_20170608_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='top_investors',
        ),
        migrations.AddField(
            model_name='activity',
            name='top_investors',
            field=models.TextField(blank=True, verbose_name='Top parent companies'),
        ),
    ]
