# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-28 20:39
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0005_auto_20170613_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorActivitySize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_size', models.IntegerField(verbose_name='Deal size')),
            ],
            options={
                'verbose_name': 'Investor activity size',
                'verbose_name_plural': 'Investor activity sizes',
            },
        ),
        migrations.AlterField(
            model_name='activity',
            name='fully_updated_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fully updated date'),
        ),
        migrations.AlterField(
            model_name='activitychangeset',
            name='fk_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='landmatrix.Country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='historicalinvestor',
            name='classification',
            field=models.CharField(blank=True, choices=[('10', 'Private company'), ('20', 'Stock-exchange listed company'), ('30', 'Individual entrepreneur'), ('40', 'Investment fund'), ('50', 'Semi state-owned company'), ('60', 'State-/government (owned) company'), ('70', 'Other (please specify in comment field)'), ('110', 'Government'), ('120', 'Government institution'), ('130', 'Multilateral Development Bank (MDB)'), ('140', 'Bilateral Development Bank / Development Finance Institution'), ('150', 'Commercial Bank'), ('160', 'Investment Bank'), ('170', 'Investment Fund (all types incl. pension, hedge, mutual, private equity funds etc.)'), ('180', 'Insurance firm'), ('190', 'Private equity firm'), ('200', 'Asset management firm'), ('210', 'Non - Profit organization (e.g. Church, University etc.)')], max_length=3, null=True, verbose_name='Classification'),
        ),
        migrations.AlterField(
            model_name='historicalinvestor',
            name='investor_identifier',
            field=models.IntegerField(db_index=True, default=2147483647, verbose_name='Investor ID'),
        ),
        migrations.AlterField(
            model_name='historicalinvestor',
            name='parent_relation',
            field=models.CharField(blank=True, choices=[('Subsidiary', 'Subsidiary of parent company'), ('Local branch', 'Local branch of parent company'), ('Joint venture', 'Joint venture of parent companies')], max_length=255, null=True, verbose_name='Parent relation'),
        ),
        migrations.AlterField(
            model_name='investor',
            name='classification',
            field=models.CharField(blank=True, choices=[('10', 'Private company'), ('20', 'Stock-exchange listed company'), ('30', 'Individual entrepreneur'), ('40', 'Investment fund'), ('50', 'Semi state-owned company'), ('60', 'State-/government (owned) company'), ('70', 'Other (please specify in comment field)'), ('110', 'Government'), ('120', 'Government institution'), ('130', 'Multilateral Development Bank (MDB)'), ('140', 'Bilateral Development Bank / Development Finance Institution'), ('150', 'Commercial Bank'), ('160', 'Investment Bank'), ('170', 'Investment Fund (all types incl. pension, hedge, mutual, private equity funds etc.)'), ('180', 'Insurance firm'), ('190', 'Private equity firm'), ('200', 'Asset management firm'), ('210', 'Non - Profit organization (e.g. Church, University etc.)')], max_length=3, null=True, verbose_name='Classification'),
        ),
        migrations.AlterField(
            model_name='investor',
            name='investor_identifier',
            field=models.IntegerField(db_index=True, default=2147483647, verbose_name='Investor ID'),
        ),
        migrations.AlterField(
            model_name='investor',
            name='parent_relation',
            field=models.CharField(blank=True, choices=[('Subsidiary', 'Subsidiary of parent company'), ('Local branch', 'Local branch of parent company'), ('Joint venture', 'Joint venture of parent companies')], max_length=255, null=True, verbose_name='Parent relation'),
        ),
        migrations.AlterField(
            model_name='investorventureinvolvement',
            name='fk_investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investors', to='landmatrix.Investor', verbose_name='Investor ID Upstream'),
        ),
        migrations.AlterField(
            model_name='investorventureinvolvement',
            name='fk_venture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venture_involvements', to='landmatrix.Investor', verbose_name='Investor ID Downstream'),
        ),
        migrations.AlterField(
            model_name='investorventureinvolvement',
            name='role',
            field=models.CharField(choices=[('ST', 'Parent company'), ('IN', 'Tertiary investor/lendor')], max_length=2, verbose_name='Relation type'),
        ),
        migrations.AddField(
            model_name='investoractivitysize',
            name='fk_activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landmatrix.Activity', verbose_name='Activity'),
        ),
        migrations.AddField(
            model_name='investoractivitysize',
            name='fk_investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landmatrix.Investor', verbose_name='Investor'),
        ),
    ]
