# Generated by Django 4.2.3 on 2023-10-15 08:43

import apps.landmatrix.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0007_alter_deal_current_intention_of_investment'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='carbon_sequestration',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='carbon_sequestration_comment',
            field=models.TextField(blank=True, verbose_name='Comment on carbon sequestration'),
        ),
        migrations.AddField(
            model_name='deal',
            name='current_carbon_sequestration',
            field=apps.landmatrix.models.fields.ArrayField(base_field=models.CharField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='deal',
            name='current_electricity_generation',
            field=apps.landmatrix.models.fields.ArrayField(base_field=models.CharField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='deal',
            name='electricity_generation',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='electricity_generation_comment',
            field=models.TextField(blank=True, verbose_name='Comment on electricity generation'),
        ),
    ]
