# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-19 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0007_auto_20171001_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtercondition',
            name='operator',
            field=models.CharField(choices=[('is', 'is'), ('in', 'in'), ('not_in', 'not_in'), ('gte', 'gte'), ('gt', 'gt'), ('lte', 'lte'), ('lt', 'lt'), ('contains', 'contains'), ('not_contains', 'not_contains'), ('is_empty', 'is_empty')], max_length=20, verbose_name='Operator'),
        ),
    ]
