# Generated by Django 4.2.3 on 2023-10-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0008_deal_carbon_sequestration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(choices=[('DEAL', 'Deal'), ('INVESTOR', 'Investor')])),
                ('field', models.CharField()),
                ('short_description', models.TextField()),
                ('long_description', models.TextField(blank=True)),
                ('editor_description', models.TextField(blank=True)),
            ],
        ),
    ]
