# Generated by Django 4.2.6 on 2023-10-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0009_fielddefinition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fielddefinition',
            name='model',
            field=models.CharField(choices=[('deal', 'Deal'), ('investor', 'Investor')]),
        ),
    ]
