# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-29 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0009_auto_20180726_2034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalinvestoractivityinvolvement',
            options={'ordering': ['-id'], 'verbose_name': 'Historical Investor Activity Involvement', 'verbose_name_plural': 'Historical Investor Activity Involvements'},
        ),
        migrations.AlterModelOptions(
            name='historicalinvestorventureinvolvement',
            options={'get_latest_by': '-id', 'verbose_name': 'Historical Investor Venture Involvement', 'verbose_name_plural': 'Historical Investor Venture Involvements'},
        ),
        migrations.AlterModelOptions(
            name='investoractivityinvolvement',
            options={'ordering': ('-id',), 'verbose_name': 'Investor Activity Involvement', 'verbose_name_plural': 'Investor Activity Involvements'},
        ),
        migrations.AlterModelOptions(
            name='investorventureinvolvement',
            options={'ordering': ('-id',), 'verbose_name': 'Investor Venture Involvement', 'verbose_name_plural': 'Investor Venture Involvements'},
        ),
        migrations.RemoveField(
            model_name='historicalinvestor',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='historicalinvestoractivityinvolvement',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='historicalinvestorventureinvolvement',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='investoractivityinvolvement',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='investorventureinvolvement',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='historicalinvestor',
            name='investor_identifier',
            field=models.IntegerField(db_index=True, default=2147483647, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='investor',
            name='investor_identifier',
            field=models.IntegerField(db_index=True, default=2147483647, verbose_name='ID'),
        ),
    ]
