# Generated by Django 4.2.6 on 2023-10-31 09:25

import apps.landmatrix.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0011_fielddefinition_editor_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='current_intention_of_investment',
            field=apps.landmatrix.models.fields.ArrayField(base_field=models.CharField(choices=[('BIOFUELS', 'Biomass for biofuels'), ('BIOMASS_ENERGY_GENERATION', 'Biomass for energy generation'), ('FODDER', 'Fodder'), ('FOOD_CROPS', 'Food crops'), ('LIVESTOCK', 'Livestock'), ('NON_FOOD_AGRICULTURE', 'Non-food agricultural commodities'), ('AGRICULTURE_UNSPECIFIED', 'Agriculture unspecified'), ('BIOMASS_ENERGY_PRODUCTION', 'Biomass for energy generation'), ('CARBON', 'For carbon sequestration/REDD'), ('FOREST_LOGGING', 'Forest logging / management for wood and fiber'), ('TIMBER_PLANTATION', 'Timber plantation for wood and fiber'), ('FORESTRY_UNSPECIFIED', 'Forestry unspecified'), ('SOLAR_PARK', 'Solar park'), ('WIND_FARM', 'Wind farm'), ('RENEWABLE_ENERGY', 'Renewable energy unspecified'), ('CONVERSATION', 'Conservation'), ('INDUSTRY', 'Industry'), ('LAND_SPECULATION', 'Land speculation'), ('MINING', 'Mining'), ('OIL_GAS_EXTRACTION', 'Oil / Gas extraction'), ('TOURISM', 'Tourism'), ('OTHER', 'Other')], max_length=100), blank=True, null=True, size=None),
        ),
    ]
