# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-07 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0012_auto_20180907_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='contract_size',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Current size under contract'),
        ),
        migrations.AddField(
            model_name='activity',
            name='production_size',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Current size in operation'),
        ),
    ]
