# Generated by Django 4.2.7 on 2023-11-06 12:49

import apps.landmatrix.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0012_alter_deal_current_intention_of_investment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='symbol',
            field=models.CharField(verbose_name='Symbol'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='annual_leasing_fee_type',
            field=models.CharField(blank=True, choices=[('PER_HA', 'per ha'), ('PER_AREA', 'for specified area')], null=True, verbose_name='Annual leasing fee area type'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='community_consultation',
            field=models.CharField(blank=True, choices=[('NOT_CONSULTED', 'Not consulted'), ('LIMITED_CONSULTATION', 'Limited consultation'), ('FPIC', 'Free, Prior and Informed Consent (FPIC)'), ('OTHER', 'Other')], null=True, verbose_name='Community consultation'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='community_reaction',
            field=models.CharField(blank=True, choices=[('CONSENT', 'Consent'), ('MIXED_REACTION', 'Mixed reaction'), ('REJECTION', 'Rejection')], null=True, verbose_name='Community reaction'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='current_animals',
            field=apps.landmatrix.models.fields.ArrayField(base_field=models.CharField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='deal',
            name='current_crops',
            field=apps.landmatrix.models.fields.ArrayField(base_field=models.CharField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='deal',
            name='current_implementation_status',
            field=models.CharField(blank=True, choices=[('PROJECT_NOT_STARTED', 'Project not started'), ('STARTUP_PHASE', 'Startup phase (no production)'), ('IN_OPERATION', 'In operation (production)'), ('PROJECT_ABANDONED', 'Project abandoned')], null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='current_intention_of_investment',
            field=apps.landmatrix.models.fields.ArrayField(base_field=models.CharField(choices=[('BIOFUELS', 'Biomass for biofuels'), ('BIOMASS_ENERGY_GENERATION', 'Biomass for energy generation'), ('FODDER', 'Fodder'), ('FOOD_CROPS', 'Food crops'), ('LIVESTOCK', 'Livestock'), ('NON_FOOD_AGRICULTURE', 'Non-food agricultural commodities'), ('AGRICULTURE_UNSPECIFIED', 'Agriculture unspecified'), ('BIOMASS_ENERGY_PRODUCTION', 'Biomass for energy generation'), ('CARBON', 'For carbon sequestration/REDD'), ('FOREST_LOGGING', 'Forest logging / management for wood and fiber'), ('TIMBER_PLANTATION', 'Timber plantation for wood and fiber'), ('FORESTRY_UNSPECIFIED', 'Forestry unspecified'), ('SOLAR_PARK', 'Solar park'), ('WIND_FARM', 'Wind farm'), ('RENEWABLE_ENERGY', 'Renewable energy unspecified'), ('CONVERSATION', 'Conservation'), ('INDUSTRY', 'Industry'), ('LAND_SPECULATION', 'Land speculation'), ('MINING', 'Mining'), ('OIL_GAS_EXTRACTION', 'Oil / Gas extraction'), ('TOURISM', 'Tourism'), ('OTHER', 'Other')]), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='deal',
            name='current_mineral_resources',
            field=apps.landmatrix.models.fields.ArrayField(base_field=models.CharField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='deal',
            name='current_negotiation_status',
            field=models.CharField(blank=True, choices=[('EXPRESSION_OF_INTEREST', 'Intended (Expression of interest)'), ('UNDER_NEGOTIATION', 'Intended (Under negotiation)'), ('MEMORANDUM_OF_UNDERSTANDING', 'Intended (Memorandum of understanding)'), ('ORAL_AGREEMENT', 'Concluded (Oral Agreement)'), ('CONTRACT_SIGNED', 'Concluded (Contract signed)'), ('CHANGE_OF_OWNERSHIP', 'Concluded (Change of ownership)'), ('NEGOTIATIONS_FAILED', 'Failed (Negotiations failed)'), ('CONTRACT_CANCELED', 'Failed (Contract cancelled)'), ('CONTRACT_EXPIRED', 'Contract expired')], null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='former_land_cover',
            field=apps.landmatrix.models.fields.ArrayField(base_field=models.CharField(choices=[('CROPLAND', 'Cropland'), ('FOREST_LAND', 'Forest land'), ('PASTURE', 'Pasture'), ('RANGELAND', 'Shrub land/Grassland (Rangeland)'), ('MARGINAL_LAND', 'Marginal land'), ('WETLAND', 'Wetland'), ('OTHER_LAND', 'Other land (e.g. developed land – specify in comment field)')]), blank=True, null=True, size=None, verbose_name='Former land cover'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='former_land_owner',
            field=apps.landmatrix.models.fields.ArrayField(base_field=models.CharField(choices=[('STATE', 'State'), ('PRIVATE_SMALLHOLDERS', 'Private (smallholders)'), ('PRIVATE_LARGE_SCALE', 'Private (large-scale farm)'), ('COMMUNITY', 'Community'), ('INDIGENOUS_PEOPLE', 'Indigenous people'), ('OTHER', 'Other')]), blank=True, null=True, size=None, verbose_name='Former land owner'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='former_land_use',
            field=apps.landmatrix.models.fields.ArrayField(base_field=models.CharField(choices=[('COMMERCIAL_AGRICULTURE', 'Commercial (large-scale) agriculture'), ('SMALLHOLDER_AGRICULTURE', 'Smallholder agriculture'), ('SHIFTING_CULTIVATION', 'Shifting cultivation'), ('PASTORALISM', 'Pastoralism'), ('HUNTING_GATHERING', 'Hunting/Gathering'), ('FORESTRY', 'Forestry'), ('CONSERVATION', 'Conservation'), ('OTHER', 'Other')]), blank=True, null=True, size=None, verbose_name='Former land use'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='materialized_benefits',
            field=apps.landmatrix.models.fields.ArrayField(base_field=models.CharField(choices=[('HEALTH', 'Health'), ('EDUCATION', 'Education'), ('PRODUCTIVE_INFRASTRUCTURE', 'Productive infrastructure (e.g. irrigation, tractors, machinery...)'), ('ROADS', 'Roads'), ('CAPACITY_BUILDING', 'Capacity building'), ('FINANCIAL_SUPPORT', 'Financial support'), ('COMMUNITY_SHARES', 'Community shares in the investment project'), ('OTHER', 'Other')]), blank=True, null=True, size=None, verbose_name='Materialized benefits for local communities'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='name_of_community',
            field=apps.landmatrix.models.fields.ArrayField(base_field=models.CharField(blank=True), blank=True, null=True, size=None, verbose_name='Name of community'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='name_of_indigenous_people',
            field=apps.landmatrix.models.fields.ArrayField(base_field=models.CharField(blank=True), blank=True, null=True, size=None, verbose_name='Name of indigenous people'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='nature_of_deal',
            field=apps.landmatrix.models.fields.ArrayField(base_field=models.CharField(choices=[('OUTRIGHT_PURCHASE', 'Outright purchase'), ('LEASE', 'Lease'), ('CONCESSION', 'Concession'), ('EXPLOITATION_PERMIT', 'Exploitation permit / license / concession (for mineral resources)'), ('PURE_CONTRACT_FARMING', 'Pure contract farming'), ('OTHER', 'Other')]), blank=True, null=True, size=None, verbose_name='Nature of the deal'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='negative_impacts',
            field=apps.landmatrix.models.fields.ArrayField(base_field=models.CharField(choices=[('ENVIRONMENTAL_DEGRADATION', 'Environmental degradation'), ('SOCIO_ECONOMIC', 'Socio-economic'), ('CULTURAL_LOSS', 'Cultural loss'), ('EVICTION', 'Eviction'), ('DISPLACEMENT', 'Displacement'), ('VIOLENCE', 'Violence'), ('OTHER', 'Other')]), blank=True, null=True, size=None, verbose_name='Negative impacts for local communities'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='not_public_reason',
            field=models.CharField(blank=True, choices=[('CONFIDENTIAL', 'Confidential flag'), ('NO_COUNTRY', 'No country'), ('HIGH_INCOME_COUNTRY', 'High-income country'), ('NO_DATASOURCES', 'No datasources'), ('NO_OPERATING_COMPANY', 'No operating company'), ('NO_KNOWN_INVESTOR', 'No known investor')]),
        ),
        migrations.AlterField(
            model_name='deal',
            name='project_name',
            field=models.CharField(blank=True, verbose_name='Name of investment project'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='promised_benefits',
            field=apps.landmatrix.models.fields.ArrayField(base_field=models.CharField(choices=[('HEALTH', 'Health'), ('EDUCATION', 'Education'), ('PRODUCTIVE_INFRASTRUCTURE', 'Productive infrastructure (e.g. irrigation, tractors, machinery...)'), ('ROADS', 'Roads'), ('CAPACITY_BUILDING', 'Capacity building'), ('FINANCIAL_SUPPORT', 'Financial support'), ('COMMUNITY_SHARES', 'Community shares in the investment project'), ('OTHER', 'Other')]), blank=True, null=True, size=None, verbose_name='Promised benefits for local communities'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='purchase_price_type',
            field=models.CharField(blank=True, choices=[('PER_HA', 'per ha'), ('PER_AREA', 'for specified area')], null=True, verbose_name='Purchase price area type'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='recognition_status',
            field=apps.landmatrix.models.fields.ArrayField(base_field=models.CharField(choices=[('INDIGENOUS_RIGHTS_RECOGNIZED', 'Indigenous Peoples traditional or customary rights recognized by government'), ('INDIGENOUS_RIGHTS_NOT_RECOGNIZED', 'Indigenous Peoples traditional or customary rights not recognized by government'), ('COMMUNITY_RIGHTS_RECOGNIZED', 'Community traditional or customary rights recognized by government'), ('COMMUNITY_RIGHTS_NOT_RECOGNIZED', 'Community traditional or customary rights not recognized by government')]), blank=True, null=True, size=None, verbose_name='Recognition status of community land tenure'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='source_of_water_extraction',
            field=apps.landmatrix.models.fields.ArrayField(base_field=models.CharField(choices=[('GROUNDWATER', 'Groundwater'), ('SURFACE_WATER', 'Surface water'), ('RIVER', 'River'), ('LAKE', 'Lake')]), blank=True, null=True, size=None, verbose_name='Source of water extraction'),
        ),
        migrations.AddField(
            model_name='deal',
            name='carbon_offset_project',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='carbon_offset_project_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='classification',
            field=models.CharField(blank=True, choices=[('GOVERNMENT', 'Government'), ('GOVERNMENT_INSTITUTION', 'Government institution'), ('STATE_OWNED_COMPANY', 'State-/government (owned) company'), ('SEMI_STATE_OWNED_COMPANY', 'Semi state-owned company'), ('ASSET_MANAGEMENT_FIRM', 'Asset management firm'), ('BILATERAL_DEVELOPMENT_BANK', 'Bilateral Development Bank / Development Finance Institution'), ('STOCK_EXCHANGE_LISTED_COMPANY', 'Stock-exchange listed company'), ('COMMERCIAL_BANK', 'Commercial Bank'), ('INSURANCE_FIRM', 'Insurance firm'), ('INVESTMENT_BANK', 'Investment Bank'), ('INVESTMENT_FUND', 'Investment fund'), ('MULTILATERAL_DEVELOPMENT_BANK', 'Multilateral Development Bank (MDB)'), ('PRIVATE_COMPANY', 'Private company'), ('PRIVATE_EQUITY_FIRM', 'Private equity firm'), ('INDIVIDUAL_ENTREPRENEUR', 'Individual entrepreneur'), ('NON_PROFIT', 'Non - Profit organization (e.g. Church, University etc.)'), ('OTHER', 'Other (please specify in comment field)')], null=True, verbose_name='Classification'),
        ),
        migrations.AlterField(
            model_name='investor',
            name='name',
            field=models.CharField(verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='investorventureinvolvement',
            name='investment_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('EQUITY', 'Shares/Equity'), ('DEBT_FINANCING', 'Debt financing')]), blank=True, null=True, size=None, verbose_name='Investment type'),
        ),
        migrations.AlterField(
            model_name='investorventureinvolvement',
            name='parent_relation',
            field=models.CharField(blank=True, choices=[('SUBSIDIARY', 'Subsidiary of parent company'), ('LOCAL_BRANCH', 'Local branch of parent company'), ('JOINT_VENTURE', 'Joint venture of parent companies')], null=True, verbose_name='Parent relation'),
        ),
        migrations.AlterField(
            model_name='investorventureinvolvement',
            name='role',
            field=models.CharField(choices=[('PARENT', 'Parent company'), ('LENDER', 'Tertiary investor/lender')], verbose_name='Relation type'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(verbose_name='Name'),
        ),
    ]
