# Generated by Django 5.0.2 on 2024-02-23 13:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0013_alter_country_name_alter_currency_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DealWorkflowInfo',
            new_name='DealWorkflowInfoOld',
        ),
        migrations.RenameModel(
            old_name='InvestorWorkflowInfo',
            new_name='InvestorWorkflowInfoOld',
        ),
        migrations.RenameModel(
            old_name='Deal',
            new_name='DealOld',
        ),
        migrations.RenameModel(
            old_name='DealVersion',
            new_name='DealVersionOld',
        ),
        migrations.RenameModel(
            old_name='Investor',
            new_name='InvestorOld',
        ),
        migrations.CreateModel(
            name='DealOldParentCompanies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'landmatrix_dealold_parent_companies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DealOldTopInvestors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'landmatrix_dealold_top_investors',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='DealParentCompanies',
        ),
        migrations.DeleteModel(
            name='DealTopInvestors',
        ),
    ]
