# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-01-23 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0013_auto_20180907_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvestor',
            name='action_comment',
            field=models.TextField(null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='production_size',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Current size in operation (production)'),
        ),
        migrations.AlterField(
            model_name='historicalinvestor',
            name='investor_identifier',
            field=models.IntegerField(db_index=True, default=2147483647, verbose_name='Investor ID'),
        ),
        migrations.AlterField(
            model_name='investor',
            name='investor_identifier',
            field=models.IntegerField(db_index=True, default=2147483647, verbose_name='Investor ID'),
        ),
    ]
