# Generated by Django 5.0.2 on 2024-02-23 13:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0013_alter_country_name_alter_currency_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DealWorkflowInfo',
            new_name='DealWorkflowInfoOld',
        ),
        migrations.RenameModel(
            old_name='InvestorWorkflowInfo',
            new_name='InvestorWorkflowInfoOld',
        )
    ]
