# Generated by Django 4.2.7 on 2023-12-16 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0013_alter_country_name_alter_currency_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='oldmodel_deals', to='landmatrix.country', verbose_name='Target country'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='operating_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oldmodel_deals', to='landmatrix.investor'),
        ),
    ]
