# Generated by Django 5.0.2 on 2024-02-23 13:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0013_alter_country_name_alter_currency_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DealWorkflowInfo',
            new_name='DealWorkflowInfoOld',
        ),
        # migrations.RemoveIndex()
        migrations.RunSQL("alter index landmatrix_dealworkflowinfo_pkey rename to landmatrix_dealworkflowinfo_pkey_old",""),
        migrations.RunSQL("alter index landmatrix_dealworkflowinfo_deal_id_59d53681 rename to landmatrix_dealworkflowinfo_deal_id_59d53681_old",""),
        migrations.RunSQL("alter index landmatrix_dealworkflowinfo_deal_version_id_efd6a313 rename to landmatrix_dealworkflowinfo_deal_version_id_efd6a313_old",""),
        migrations.RunSQL("alter index landmatrix_dealworkflowinfo_from_user_id_74b34a00 rename to landmatrix_dealworkflowinfo_from_user_id_74b34a00_old",""),
        migrations.RunSQL("alter index landmatrix_dealworkflowinfo_to_user_id_ea51b4c9 rename to landmatrix_dealworkflowinfo_to_user_id_ea51b4c9_old",""),
        migrations.RenameModel(
            old_name='InvestorWorkflowInfo',
            new_name='InvestorWorkflowInfoOld',
        ),
        migrations.RunSQL("alter index landmatrix_investorworkflowinfo_pkey rename to landmatrix_investorworkflowinfo_pkey_old",""),
        migrations.RunSQL("alter index landmatrix_investorworkflowinfo_from_user_id_588a065c rename to landmatrix_investorworkflowinfo_from_user_id_588a065c_old",""),
        migrations.RunSQL("alter index landmatrix_investorworkflowinfo_investor_id_ec893144 rename to landmatrix_investorworkflowinfo_investor_id_ec893144_old",""),
        migrations.RunSQL("alter index landmatrix_investorworkflowinfo_investor_version_id_28a454c2 rename to landmatrix_investorworkflowinfo_investor_version_id_28a454c2_old",""),
        migrations.RunSQL("alter index landmatrix_investorworkflowinfo_to_user_id_d3fbae65 rename to landmatrix_investorworkflowinfo_to_user_id_d3fbae65_old",""),
        migrations.RenameModel(
            old_name='Deal',
            new_name='DealOld',
        ),
        migrations.RenameModel(
            old_name='DealVersion',
            new_name='DealVersionOld',
        ),
        migrations.RunSQL("alter index landmatrix_dealversion_pkey rename to landmatrix_dealversion_pkey_old",""),
        migrations.RunSQL("alter index landmatrix_dealversion_created_at_b892b117 rename to landmatrix_dealversion_created_at_b892b117_old",""),
        migrations.RunSQL("alter index landmatrix_dealversion_created_by_id_6b750335 rename to landmatrix_dealversion_created_by_id_6b750335_old",""),
        migrations.RunSQL("alter index landmatrix_dealversion_modified_by_id_7d7b0ebe rename to landmatrix_dealversion_modified_by_id_7d7b0ebe_old",""),
        migrations.RunSQL("alter index landmatrix_dealversion_object_id_bed74e5d rename to landmatrix_dealversion_object_id_bed74e5d_old",""),
        migrations.RenameModel(
            old_name='Investor',
            new_name='InvestorOld',
        ),
        migrations.RenameModel(
            old_name='InvestorVersion',
            new_name='InvestorVersionOld',
        ),
        migrations.RunSQL("alter index landmatrix_investorversion_pkey rename to landmatrix_investorversion_pkey_old",""),
        migrations.RunSQL("alter index landmatrix_investorversion_created_at_a166a092 rename to landmatrix_investorversion_created_at_a166a092_old",""),
        migrations.RunSQL("alter index landmatrix_investorversion_created_by_id_3a0420a0 rename to landmatrix_investorversion_created_by_id_3a0420a0_old",""),
        migrations.RunSQL("alter index landmatrix_investorversion_modified_by_id_c9192e8f rename to landmatrix_investorversion_modified_by_id_c9192e8f_old",""),
        migrations.RunSQL("alter index landmatrix_investorversion_object_id_cb0d6261 rename to landmatrix_investorversion_object_id_cb0d6261_old",""),
        migrations.CreateModel(
            name='DealOldParentCompanies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'landmatrix_dealold_parent_companies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DealOldTopInvestors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'landmatrix_dealold_top_investors',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='DealParentCompanies',
        ),
        migrations.DeleteModel(
            name='DealTopInvestors',
        ),
    ]
