# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-02-07 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0014_auto_20190123_1744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investor',
            options={'ordering': ('name',), 'permissions': (('review_investor', 'Can review investor changes'),), 'verbose_name': 'Investor', 'verbose_name_plural': 'Investors'},
        ),
        migrations.RemoveField(
            model_name='historicalinvestor',
            name='parent_relation',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='parent_relation',
        ),
        migrations.AddField(
            model_name='historicalinvestorventureinvolvement',
            name='parent_relation',
            field=models.CharField(blank=True, choices=[('Subsidiary', 'Subsidiary of parent company'), ('Local branch', 'Local branch of parent company'), ('Joint venture', 'Joint venture of parent companies')], max_length=255, null=True, verbose_name='Parent relation'),
        ),
        migrations.AddField(
            model_name='investorventureinvolvement',
            name='parent_relation',
            field=models.CharField(blank=True, choices=[('Subsidiary', 'Subsidiary of parent company'), ('Local branch', 'Local branch of parent company'), ('Joint venture', 'Joint venture of parent companies')], max_length=255, null=True, verbose_name='Parent relation'),
        ),
    ]
