# Generated by Django 5.0.3 on 2024-03-05 21:03

import apps.landmatrix.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0015_dealtopinvestors_alter_dealold_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealold',
            name='carbon_offset_project',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dealold',
            name='carbon_offset_project_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dealversion',
            name='carbon_offset_project',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dealversion',
            name='carbon_offset_project_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dealold',
            name='current_intention_of_investment',
            field=apps.landmatrix.models.fields.ArrayField(base_field=models.CharField(choices=[('BIOFUELS', 'Biomass for biofuels'), ('BIOMASS_ENERGY_GENERATION', 'Biomass for energy generation (agriculture)'), ('FODDER', 'Fodder'), ('FOOD_CROPS', 'Food crops'), ('LIVESTOCK', 'Livestock'), ('NON_FOOD_AGRICULTURE', 'Non-food agricultural commodities'), ('AGRICULTURE_UNSPECIFIED', 'Agriculture unspecified'), ('BIOMASS_ENERGY_PRODUCTION', 'Biomass for energy generation (forestry)'), ('CARBON', 'For carbon sequestration/REDD'), ('FOREST_LOGGING', 'Forest logging / management for wood and fiber'), ('TIMBER_PLANTATION', 'Timber plantation for wood and fiber'), ('FORESTRY_UNSPECIFIED', 'Forestry unspecified'), ('SOLAR_PARK', 'Solar park'), ('WIND_FARM', 'Wind farm'), ('RENEWABLE_ENERGY', 'Renewable energy unspecified'), ('CONVERSATION', 'Conservation'), ('INDUSTRY', 'Industry'), ('LAND_SPECULATION', 'Land speculation'), ('MINING', 'Mining'), ('OIL_GAS_EXTRACTION', 'Oil / Gas extraction'), ('TOURISM', 'Tourism'), ('OTHER', 'Other')]), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='current_intention_of_investment',
            field=apps.landmatrix.models.fields.ChoiceArrayField(base_field=models.CharField(choices=[('BIOFUELS', 'Biomass for biofuels'), ('BIOMASS_ENERGY_GENERATION', 'Biomass for energy generation (agriculture)'), ('FODDER', 'Fodder'), ('FOOD_CROPS', 'Food crops'), ('LIVESTOCK', 'Livestock'), ('NON_FOOD_AGRICULTURE', 'Non-food agricultural commodities'), ('AGRICULTURE_UNSPECIFIED', 'Agriculture unspecified'), ('BIOMASS_ENERGY_PRODUCTION', 'Biomass for energy generation (forestry)'), ('CARBON', 'For carbon sequestration/REDD'), ('FOREST_LOGGING', 'Forest logging / management for wood and fiber'), ('TIMBER_PLANTATION', 'Timber plantation for wood and fiber'), ('FORESTRY_UNSPECIFIED', 'Forestry unspecified'), ('SOLAR_PARK', 'Solar park'), ('WIND_FARM', 'Wind farm'), ('RENEWABLE_ENERGY', 'Renewable energy unspecified'), ('CONVERSATION', 'Conservation'), ('INDUSTRY', 'Industry'), ('LAND_SPECULATION', 'Land speculation'), ('MINING', 'Mining'), ('OIL_GAS_EXTRACTION', 'Oil / Gas extraction'), ('TOURISM', 'Tourism'), ('OTHER', 'Other')]), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='involvement',
            name='child_investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parent_investors', to='landmatrix.investorhull', verbose_name='Venture Company'),
        ),
        migrations.AlterField(
            model_name='involvement',
            name='parent_investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='child_investors', to='landmatrix.investorhull', verbose_name='Investor'),
        ),
    ]
