# Generated by Django 5.0 on 2023-12-22 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0015_dealhull_dealversion2_investorhull_investorversion2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealhull',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='dealhull',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='investorhull',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='investorhull',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='deal',
            name='operating_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='landmatrix.investor'),
        ),
        migrations.AlterField(
            model_name='dealversion2',
            name='created_at',
            field=models.DateTimeField(verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='dealversion2',
            name='operating_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealversions', to='landmatrix.investorhull'),
        ),
        migrations.AlterField(
            model_name='dealversion2',
            name='parent_companies',
            field=models.ManyToManyField(blank=True, related_name='child_deals', to='landmatrix.investorhull', verbose_name='Parent companies'),
        ),
        migrations.AlterField(
            model_name='dealversion2',
            name='top_investors',
            field=models.ManyToManyField(blank=True, related_name='+', to='landmatrix.investorhull', verbose_name='Top parent companies'),
        ),
        migrations.AlterField(
            model_name='investorversion2',
            name='created_at',
            field=models.DateTimeField(verbose_name='Created at'),
        ),
    ]
