# Generated by Django 5.0 on 2023-12-22 12:28

import apps.landmatrix.models.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0016_remove_dealhull_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='involvement',
            name='loans_date',
            field=apps.landmatrix.models.fields.LooseDateField(blank=True, max_length=10, null=True, verbose_name='Loan date'),
        ),
        migrations.AlterField(
            model_name='involvement',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Ownership share'),
        ),
    ]
