# Generated by Django 2.1.11 on 2019-08-27 15:05

from django.db import migrations


def migrate_comments(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0016_auto_20190425_0004'),
    ]

    operations = [
        migrations.RunPython(migrate_comments),
    ]
