# Generated by Django 5.0.4 on 2024-04-08 12:15

import apps.landmatrix.models.schema
import django.core.serializers.json
import django_pydantic_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0017_alter_dealversion_animals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealversion',
            name='animals',
            field=django_pydantic_field.fields.PydanticSchemaField(blank=True, config=None, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, schema=apps.landmatrix.models.schema.ExportsAnimals),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='carbon_sequestration',
            field=django_pydantic_field.fields.PydanticSchemaField(blank=True, config=None, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, schema=apps.landmatrix.models.schema.CarbonSequestrationSchema),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='contract_farming_animals',
            field=django_pydantic_field.fields.PydanticSchemaField(blank=True, config=None, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, schema=apps.landmatrix.models.schema.CurrentDateAreaChoicesAnimals),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='contract_farming_crops',
            field=django_pydantic_field.fields.PydanticSchemaField(blank=True, config=None, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, schema=apps.landmatrix.models.schema.CurrentDateAreaChoicesCrops),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='contract_size',
            field=django_pydantic_field.fields.PydanticSchemaField(blank=True, config=None, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, schema=apps.landmatrix.models.schema.CurrentDateAreaSchema),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='crops',
            field=django_pydantic_field.fields.PydanticSchemaField(blank=True, config=None, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, schema=apps.landmatrix.models.schema.ExportsCrops),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='domestic_jobs_current',
            field=django_pydantic_field.fields.PydanticSchemaField(blank=True, config=None, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, schema=apps.landmatrix.models.schema.JobsSchema),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='electricity_generation',
            field=django_pydantic_field.fields.PydanticSchemaField(blank=True, config=None, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, schema=apps.landmatrix.models.schema.ElectricityGenerationSchema),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='foreign_jobs_current',
            field=django_pydantic_field.fields.PydanticSchemaField(blank=True, config=None, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, schema=apps.landmatrix.models.schema.JobsSchema),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='implementation_status',
            field=django_pydantic_field.fields.PydanticSchemaField(blank=True, config=None, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, schema=apps.landmatrix.models.schema.CurrentDateChoiceImplementationStatus),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='intention_of_investment',
            field=django_pydantic_field.fields.PydanticSchemaField(blank=True, config=None, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, schema=apps.landmatrix.models.schema.CurrentDateAreaChoicesIOI),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='involved_actors',
            field=django_pydantic_field.fields.PydanticSchemaField(blank=True, config=None, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, schema=apps.landmatrix.models.schema.ActorsSchema),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='mineral_resources',
            field=django_pydantic_field.fields.PydanticSchemaField(blank=True, config=None, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, schema=apps.landmatrix.models.schema.ExportsMineralResources),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='negotiation_status',
            field=django_pydantic_field.fields.PydanticSchemaField(blank=True, config=None, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, schema=apps.landmatrix.models.schema.CurrentDateChoiceNegotiationStatus),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='off_the_lease',
            field=django_pydantic_field.fields.PydanticSchemaField(blank=True, config=None, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, schema=apps.landmatrix.models.schema.LeaseSchema),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='on_the_lease',
            field=django_pydantic_field.fields.PydanticSchemaField(blank=True, config=None, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, schema=apps.landmatrix.models.schema.LeaseSchema),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='production_size',
            field=django_pydantic_field.fields.PydanticSchemaField(blank=True, config=None, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, schema=apps.landmatrix.models.schema.CurrentDateAreaSchema),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='total_jobs_current',
            field=django_pydantic_field.fields.PydanticSchemaField(blank=True, config=None, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, schema=apps.landmatrix.models.schema.JobsSchema),
        ),
    ]
