# Generated by Django 2.1.11 on 2019-08-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0017_migrate_comments'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='activity',
            index_together=set(),
        ),
        migrations.RemoveField(
            model_name='activity',
            name='fk_status',
        ),
        migrations.RemoveField(
            model_name='activityattribute',
            name='fk_activity',
        ),
        migrations.RemoveField(
            model_name='activityattribute',
            name='fk_group',
        ),
        migrations.RemoveField(
            model_name='activityattribute',
            name='fk_language',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='fk_country',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='fk_status',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='subinvestors',
        ),
        migrations.RemoveField(
            model_name='investoractivityinvolvement',
            name='fk_activity',
        ),
        migrations.RemoveField(
            model_name='investoractivityinvolvement',
            name='fk_investor',
        ),
        migrations.RemoveField(
            model_name='investoractivityinvolvement',
            name='fk_status',
        ),
        migrations.RemoveField(
            model_name='investorventureinvolvement',
            name='fk_investor',
        ),
        migrations.RemoveField(
            model_name='investorventureinvolvement',
            name='fk_status',
        ),
        migrations.RemoveField(
            model_name='investorventureinvolvement',
            name='fk_venture',
        ),
        migrations.RemoveField(
            model_name='investorventureinvolvement',
            name='loans_currency',
        ),
        migrations.AlterModelOptions(
            name='activitychangeset',
            options={'get_latest_by': 'timestamp', 'ordering': ('-timestamp',)},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='fk_activity',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='fk_activity_attribute_group',
        ),
        migrations.RemoveField(
            model_name='historicalactivity',
            name='public_version',
        ),
        migrations.AlterField(
            model_name='historicalinvestorventureinvolvement',
            name='role',
            field=models.CharField(choices=[('ST', 'Parent company'), ('IN', 'Tertiary investor/lender')], max_length=2, verbose_name='Relation type'),
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='ActivityAttribute',
        ),
        migrations.DeleteModel(
            name='Investor',
        ),
        migrations.DeleteModel(
            name='InvestorActivityInvolvement',
        ),
        migrations.DeleteModel(
            name='InvestorVentureInvolvement',
        ),
    ]
