# Generated by Django 2.1.11 on 2019-08-27 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0018_auto_20190823_1938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalactivity',
            options={'get_latest_by': 'id', 'ordering': ('-history_date',), 'permissions': (('review_historicalactivity', 'Can review activity changes'),), 'verbose_name': 'Historical activity', 'verbose_name_plural': 'Historical activities'},
        ),
        migrations.AlterModelOptions(
            name='historicalinvestor',
            options={'get_latest_by': 'history_date', 'ordering': ['-history_date'], 'permissions': (('review_historicalinvestor', 'Can review investor changes'),), 'verbose_name': 'Historical investor', 'verbose_name_plural': 'Historical investors'},
        ),
    ]
