# Generated by Django 5.0 on 2024-01-16 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0018_alter_deal_former_land_owner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealTopInvestors2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'landmatrix_dealversion2_top_investors',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='dealhull',
            name='active_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_active_for', to='landmatrix.dealversion2'),
        ),
        migrations.AlterField(
            model_name='dealhull',
            name='draft_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_draft_for', to='landmatrix.dealversion2'),
        ),
        migrations.AlterField(
            model_name='investorhull',
            name='active_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_active_for', to='landmatrix.investorversion2'),
        ),
        migrations.AlterField(
            model_name='investorhull',
            name='draft_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_draft_for', to='landmatrix.investorversion2'),
        ),
    ]
