# Generated by Django 5.0.4 on 2024-06-08 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0018_alter_dealversion_animals_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='dealdatasource',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='investordatasource',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='involvement',
            options={'ordering': ['id'], 'verbose_name': 'Investor Venture Involvement', 'verbose_name_plural': 'Investor Venture Involvements'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['id']},
        ),
    ]
