# Generated by Django 2.2.17 on 2021-01-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0018_auto_20190823_1938_squashed_0034_auto_20201226_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealParentCompanies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'landmatrix_deal_parent_companies',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='historicalinvestoractivityinvolvement',
            options={'ordering': ['-id'], 'verbose_name': 'Historical Investor Activity Involvement', 'verbose_name_plural': 'Historical Investor Activity Involvements'},
        ),
        migrations.AlterModelOptions(
            name='historicalinvestorventureinvolvement',
            options={'get_latest_by': '-id', 'verbose_name': 'Historical Investor Venture Involvement', 'verbose_name_plural': 'Historical Investor Venture Involvements'},
        ),
        migrations.AddField(
            model_name='deal',
            name='parent_companies',
            field=models.ManyToManyField(related_name='_deal_parent_companies_+', to='landmatrix.Investor', verbose_name='Parent companies'),
        ),
    ]
