# Generated by Django 2.2.12 on 2020-06-03 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0019_auto_20190827_1705'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BrowseCondition',
        ),
        migrations.DeleteModel(
            name='BrowseRule',
        ),
    ]
