# Generated by Django 5.0 on 2024-01-16 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0019_dealtopinvestors2_alter_dealhull_active_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealhull',
            name='active_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='landmatrix.dealversion2'),
        ),
        migrations.AlterField(
            model_name='dealhull',
            name='draft_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='landmatrix.dealversion2'),
        ),
        migrations.AlterField(
            model_name='investorhull',
            name='active_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='landmatrix.investorversion2'),
        ),
        migrations.AlterField(
            model_name='investorhull',
            name='draft_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='landmatrix.investorversion2'),
        ),
    ]
