# Generated by Django 2.2.17 on 2021-01-18 15:47

import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0019_auto_20210106_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='current_contract_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='current_production_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='deal_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='domestic_use',
            field=models.FloatField(blank=True, help_text='%', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Domestic use'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='export',
            field=models.FloatField(blank=True, help_text='%', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Export'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='export_country1_ratio',
            field=models.FloatField(blank=True, help_text='%', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Country 1 ratio'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='export_country2_ratio',
            field=models.FloatField(blank=True, help_text='%', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Country 2 ratio'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='export_country3_ratio',
            field=models.FloatField(blank=True, help_text='%', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Country 3 ratio'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='involved_actors',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, choices=[('GOVERNMENT_OR_STATE_INSTITUTIONS', 'Government / State institutions (government, ministries, departments, agencies etc.)'), ('TRADITIONAL_LAND_OWNERS_OR_COMMUNITIES', 'Traditional land-owners / communities'), ('TRADITIONAL_LOCAL_AUTHORITY', 'Traditional local authority (e.g. Chiefdom council / Chiefs)'), ('BROKER', 'Broker'), ('INTERMEDIARY', 'Intermediary'), ('OTHER', 'Other (please specify)')], null=True, verbose_name='Actors involved in the negotiation / admission process'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='parent_companies',
            field=models.ManyToManyField(related_name='child_deals', to='landmatrix.Investor', verbose_name='Parent companies'),
        ),
    ]
