# Generated by Django 5.0.4 on 2024-06-12 07:49
from django.db.models import Model
from nanoid import generate

import apps.landmatrix.models.fields
from django.db import migrations


def generate_nid(model: Model) -> str:
    nid = generate(size=8)

    while model.objects.filter(nid=nid).exists():
        nid = generate(size=8)

    return nid


def populate_nid_field(apps, _schema_editor):
    Area = apps.get_model("landmatrix", "Area")

    for area in Area.objects.all():
        area.nid = generate_nid(Area)
        area.save()


def nullify_nid_field(apps, _schema_editor):
    Area = apps.get_model("landmatrix", "Area")

    Area.objects.update(nid=None)


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0019_alter_area_options_alter_contract_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='nid',
            field=apps.landmatrix.models.fields.NanoIDField(db_index=True, max_length=15, null=True, verbose_name='ID'),
        ),
        migrations.RunPython(populate_nid_field, nullify_nid_field),
        migrations.AlterField(
            model_name='area',
            name='nid',
            field=apps.landmatrix.models.fields.NanoIDField(db_index=True, max_length=15, verbose_name='ID'),
        ),
    ]
