# Generated by Django 5.0.4 on 2024-06-12 07:49
import apps.landmatrix.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('landmatrix', '0019_alter_area_options_alter_contract_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='nid',
            field=apps.landmatrix.models.fields.NanoIDField(db_index=True, max_length=15, null=True, verbose_name='ID'),
        ),
    ]
