# Generated by Django 5.0 on 2024-01-16 20:30

import apps.landmatrix.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0020_alter_dealhull_active_version_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dealhull',
            name='first_created_at',
            field=models.DateTimeField(default='1970-01-01', verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dealhull',
            name='first_created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investorhull',
            name='first_created_at',
            field=models.DateTimeField(default='1970-01-01', verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investorhull',
            name='first_created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deal',
            name='intended_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Intended size'),
        ),
        migrations.AlterField(
            model_name='dealversion2',
            name='intended_size',
            field=apps.landmatrix.models.fields.DecimalIntField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Intended size'),
        ),
    ]
