# Generated by Django 2.2.17 on 2021-01-27 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0020_auto_20210118_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deal',
            old_name='on_the_lease',
            new_name='on_the_lease_state',
        ),
        migrations.RenameField(
            model_name='deal',
            old_name='off_the_lease',
            new_name='off_the_lease_state',
        ),
    ]
