# Generated by Django 5.0.1 on 2024-01-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0021_dealhull_first_created_at_dealhull_first_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealdatasource',
            name='type',
            field=models.CharField(blank=True, choices=[('MEDIA_REPORT', 'Media report'), ('RESEARCH_PAPER_OR_POLICY_REPORT', 'Research Paper / Policy Report'), ('GOVERNMENT_SOURCES', 'Government sources'), ('COMPANY_SOURCES', 'Company sources'), ('CONTRACT', 'Contract'), ('CONTRACT_FARMING_AGREEMENT', 'Contract (contract farming agreement)'), ('PERSONAL_INFORMATION', 'Personal information'), ('CROWDSOURCING', 'Crowdsourcing'), ('OTHER', 'Other')], verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='dealhull',
            name='deleted_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dealhull',
            name='first_created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='investordatasource',
            name='type',
            field=models.CharField(blank=True, choices=[('MEDIA_REPORT', 'Media report'), ('RESEARCH_PAPER_OR_POLICY_REPORT', 'Research Paper / Policy Report'), ('GOVERNMENT_SOURCES', 'Government sources'), ('COMPANY_SOURCES', 'Company sources'), ('CONTRACT', 'Contract'), ('CONTRACT_FARMING_AGREEMENT', 'Contract (contract farming agreement)'), ('PERSONAL_INFORMATION', 'Personal information'), ('CROWDSOURCING', 'Crowdsourcing'), ('OTHER', 'Other')], verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='investorhull',
            name='deleted_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='investorhull',
            name='first_created_at',
            field=models.DateTimeField(),
        ),
    ]
