# Generated by Django 2.2.17 on 2021-01-27 10:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0021_auto_20210127_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='domestic_jobs_current_daily_workers',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='domestic_jobs_current_employees',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='foreign_jobs_current_daily_workers',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='foreign_jobs_current_employees',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='off_the_lease_area',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='off_the_lease_farmers',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='off_the_lease_households',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='on_the_lease_area',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='on_the_lease_farmers',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='on_the_lease_households',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='total_jobs_current_daily_workers',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='total_jobs_current_employees',
        ),
        migrations.AddField(
            model_name='deal',
            name='off_the_lease',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='ha', null=True, verbose_name='Not on leased area/farmers/households (out-grower)'),
        ),
        migrations.AddField(
            model_name='deal',
            name='on_the_lease',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='On leased area/farmers/households'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='domestic_jobs_current',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Current domestic number of jobs/employees/ daily/seasonal workers'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='foreign_jobs_current',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Current foreign number of jobs/employees/ daily/seasonal workers'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='off_the_lease_state',
            field=models.NullBooleanField(verbose_name='Not on leased / purchased (out-grower)'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='on_the_lease_state',
            field=models.NullBooleanField(verbose_name='On leased / purchased'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='total_jobs_current',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Current total number of jobs/employees/ daily/seasonal workers'),
        ),
    ]
