# Generated by Django 5.0.4 on 2024-07-24 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0022_remove_dealold_annual_leasing_fee_currency_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='involvement',
            unique_together={('parent_investor', 'child_investor')},
        ),
    ]
