# Generated by Django 5.0.1 on 2024-02-08 11:17

import apps.landmatrix.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0022_alter_dealdatasource_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='former_land_cover',
            field=apps.landmatrix.models.fields.ArrayField(base_field=models.CharField(choices=[('CROPLAND', 'Cropland'), ('FOREST_LAND', 'Forest land'), ('PASTURE', 'Pasture'), ('RANGELAND', 'Shrub land/Grassland (Rangeland)'), ('MARGINAL_LAND', 'Marginal land'), ('WETLAND', 'Wetland'), ('OTHER_LAND', 'Other land (e.g. developed land)')]), blank=True, null=True, size=None, verbose_name='Former land cover'),
        ),
        migrations.AlterField(
            model_name='dealversion2',
            name='former_land_cover',
            field=apps.landmatrix.models.fields.ChoiceArrayField(base_field=models.CharField(choices=[('CROPLAND', 'Cropland'), ('FOREST_LAND', 'Forest land'), ('PASTURE', 'Pasture'), ('RANGELAND', 'Shrub land/Grassland (Rangeland)'), ('MARGINAL_LAND', 'Marginal land'), ('WETLAND', 'Wetland'), ('OTHER_LAND', 'Other land (e.g. developed land)')]), blank=True, default=list, size=None, verbose_name='Former land cover'),
        ),
    ]
