# Generated by Django 5.0.7 on 2024-08-14 11:00

from django.db import migrations


def forward_carbon_sequ(apps, _schema_editor):
    DealVersion = apps.get_model("landmatrix", "DealVersion")
    for dv in DealVersion.objects.all():
        changed = False
        for entry in dv.carbon_sequestration:
            changed = True
            # print(entry)
            if 'date' in entry:
                entry['start_date'] = entry.pop("date")
            entry['end_date'] = None
            entry['project_proponents'] = ""
            if entry.get("certification_standard_name"):
                entry['certification_standard_name'] = [entry["certification_standard_name"]]
        if changed:
            dv.save()


def reverse_carbon_sequ(apps, _schema_editor):
    DealVersion = apps.get_model("landmatrix", "DealVersion")
    for dv in DealVersion.objects.all():
        changed = False
        for entry in dv.carbon_sequestration:
            changed = True
            if 'start_date' in entry:
                entry['date'] = entry.pop("start_date")
            del entry['end_date']
            del entry['project_proponents']
            if entry.get("certification_standard_name"):
                entry['certification_standard_name'] = entry["certification_standard_name"][0]
        if changed:
            dv.save()


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0023_alter_dealversion_animals_and_more'),
    ]

    operations = [
        migrations.RunPython(forward_carbon_sequ, reverse_carbon_sequ),
    ]
