# Generated by Django 5.0.2 on 2024-02-21 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0023_alter_deal_former_land_cover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investordatasource',
            name='investorversion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasources', to='landmatrix.investorversion2'),
        ),
        migrations.AlterField(
            model_name='investorversion2',
            name='involvements_snapshot',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
