# Generated by Django 2.2.14 on 2020-08-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0023_auto_20200826_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='forest_concession',
            field=models.BooleanField(default=False),
        ),
    ]
