# Generated by Django 2.2.17 on 2021-03-24 20:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0023_auto_20210228_1153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ('name',), 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterField(
            model_name='country',
            name='fk_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='landmatrix.Region', verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='mineral_resources',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Mineral resources area/yield/export'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='mineral_resources_comment',
            field=models.TextField(blank=True, verbose_name='Comment on mineral resources'),
        ),
    ]
