# Generated by Django 5.0.7 on 2024-08-01 13:22

import apps.landmatrix.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("landmatrix", "0023_alter_involvement_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="involvement",
            name="nid",
            field=apps.landmatrix.models.fields.NanoIDField(
                db_index=True, max_length=15, null=True, verbose_name="ID"
            ),
        ),
    ]
