# Generated by Django 2.2.17 on 2021-05-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0025_deal_has_known_investor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='open_land_contracts_id',
            field=models.CharField(blank=True, max_length=500, verbose_name='Open Contracting ID'),
        ),
    ]
