# Generated by Django 2.2.22 on 2021-05-16 09:29

import apps.landmatrix.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0026_auto_20210510_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractversion',
            name='revision',
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='deal',
        ),
        migrations.RemoveField(
            model_name='datasourceversion',
            name='revision',
        ),
        migrations.RemoveField(
            model_name='location',
            name='deal',
        ),
        migrations.RemoveField(
            model_name='locationversion',
            name='revision',
        ),
        migrations.AddField(
            model_name='deal',
            name='contracts',
            field=apps.landmatrix.models.fields.ContractsField(blank=True, null=True, verbose_name='Contracts'),
        ),
        migrations.AddField(
            model_name='deal',
            name='datasources',
            field=apps.landmatrix.models.fields.DatasourcesField(blank=True, null=True, verbose_name='Data sources'),
        ),
        migrations.AddField(
            model_name='deal',
            name='locations',
            field=apps.landmatrix.models.fields.LocationsField(blank=True, null=True, verbose_name='Locations'),
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.DeleteModel(
            name='ContractVersion',
        ),
        migrations.DeleteModel(
            name='DataSource',
        ),
        migrations.DeleteModel(
            name='DataSourceVersion',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='LocationVersion',
        ),
    ]
