# Generated by Django 5.0.7 on 2024-08-01 13:31

import apps.landmatrix.models.fields
from django.db import migrations

from apps.landmatrix.nid import populate_nid_field, nullify_nid_field


def up(_apps, _schema_editor):
    Area = _apps.get_model("landmatrix", "Involvement")
    populate_nid_field(Area)


def down(_apps, _schema_editor):
    Area = _apps.get_model("landmatrix", "Involvement")
    nullify_nid_field(Area)


class Migration(migrations.Migration):

    dependencies = [
        ("landmatrix", "0026_involvement_nid"),
    ]

    operations = [
        migrations.RunPython(up, down),
        migrations.AlterField(
            model_name="involvement",
            name="nid",
            field=apps.landmatrix.models.fields.NanoIDField(
                db_index=True, max_length=15, verbose_name="ID"
            ),
        ),
    ]
