# Generated by Django 2.2.16 on 2020-10-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0026_auto_20200928_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='top_investors',
            field=models.ManyToManyField(related_name='_deal_top_investors_+', to='landmatrix.Investor'),
        ),
    ]
