# Generated by Django 2.2.16 on 2020-10-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0027_deal_top_investors'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealTopInvestors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'landmatrix_deal_top_investors',
                'managed': False,
            },
        ),
    ]
