# Generated by Django 2.2.22 on 2021-05-31 15:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0027_auto_20210516_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='displaced_households',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Number of households actually displaced'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='displaced_households_from_fields',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Number of households displaced "only" from their agricultural fields'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='displaced_people',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Number of people actually displaced'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='displaced_people_from_community_land',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Number of people displaced out of their community land'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='displaced_people_on_completion',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Number of people facing displacement once project is fully implemented'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='displaced_people_within_community_land',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Number of people displaced staying on community land'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='domestic_jobs_planned',
            field=models.IntegerField(blank=True, help_text='jobs', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Planned number of jobs (domestic)'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='domestic_jobs_planned_daily_workers',
            field=models.IntegerField(blank=True, help_text='workers', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Planned daily/seasonal workers (domestic)'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='domestic_jobs_planned_employees',
            field=models.IntegerField(blank=True, help_text='employees', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Planned employees (domestic)'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='foreign_jobs_planned',
            field=models.IntegerField(blank=True, help_text='jobs', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Planned number of jobs (foreign)'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='foreign_jobs_planned_daily_workers',
            field=models.IntegerField(blank=True, help_text='workers', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Planned daily/seasonal workers (foreign)'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='foreign_jobs_planned_employees',
            field=models.IntegerField(blank=True, help_text='employees', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Planned employees (foreign)'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='total_jobs_planned',
            field=models.IntegerField(blank=True, help_text='jobs', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Planned number of jobs (total)'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='total_jobs_planned_daily_workers',
            field=models.IntegerField(blank=True, help_text='workers', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Planned daily/seasonal workers (total)'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='total_jobs_planned_employees',
            field=models.IntegerField(blank=True, help_text='employees', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Planned employees (total)'),
        ),
    ]
