# Generated by Django 5.0.7 on 2024-08-19 16:32

import apps.landmatrix.models.schema
import django.core.serializers.json
import django_pydantic_jsonfield
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0027_alter_involvement_nid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dealworkflowinfo',
            options={'ordering': ('-timestamp',)},
        ),
        migrations.AlterModelOptions(
            name='investorworkflowinfo',
            options={'ordering': ('-timestamp',)},
        ),
        migrations.AlterField(
            model_name='dealworkflowinfo',
            name='replies',
            field=django_pydantic_jsonfield.PydanticJSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, validators=[django_pydantic_jsonfield.SchemaValidator(schema=apps.landmatrix.models.schema.WFIReplySchema)]),
        ),
        migrations.AlterField(
            model_name='investorworkflowinfo',
            name='replies',
            field=django_pydantic_jsonfield.PydanticJSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, validators=[django_pydantic_jsonfield.SchemaValidator(schema=apps.landmatrix.models.schema.WFIReplySchema)]),
        ),
    ]
