# Generated by Django 2.2.22 on 2021-05-17 15:46

import apps.landmatrix.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0027_auto_20210516_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='contracts',
            field=apps.landmatrix.models.fields.ContractsField(default=list, verbose_name='Contracts'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='datasources',
            field=apps.landmatrix.models.fields.DatasourcesField(default=list, verbose_name='Data sources'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='locations',
            field=apps.landmatrix.models.fields.LocationsField(default=list, verbose_name='Locations'),
        ),
    ]
