# Generated by Django 5.0.7 on 2024-08-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0028_alter_dealworkflowinfo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ('name',), 'verbose_name_plural': 'Regions'},
        ),
        migrations.AlterField(
            model_name='country',
            name='point_lat',
            field=models.DecimalField(decimal_places=12, max_digits=18, verbose_name='Latitude of central point'),
        ),
        migrations.AlterField(
            model_name='country',
            name='point_lat_max',
            field=models.DecimalField(decimal_places=12, max_digits=18, verbose_name='Latitude of northernmost point'),
        ),
        migrations.AlterField(
            model_name='country',
            name='point_lat_min',
            field=models.DecimalField(decimal_places=12, max_digits=18, verbose_name='Latitude of southernmost point'),
        ),
        migrations.AlterField(
            model_name='country',
            name='point_lon',
            field=models.DecimalField(decimal_places=12, max_digits=18, verbose_name='Longitude of central point'),
        ),
        migrations.AlterField(
            model_name='country',
            name='point_lon_max',
            field=models.DecimalField(decimal_places=12, max_digits=18, verbose_name='Longitude of easternmost point'),
        ),
        migrations.AlterField(
            model_name='country',
            name='point_lon_min',
            field=models.DecimalField(decimal_places=12, max_digits=18, verbose_name='Longitude of westernmost point'),
        ),
        migrations.AlterField(
            model_name='region',
            name='point_lat_max',
            field=models.DecimalField(decimal_places=12, max_digits=18, verbose_name='Latitude of northernmost point'),
        ),
        migrations.AlterField(
            model_name='region',
            name='point_lat_min',
            field=models.DecimalField(decimal_places=12, max_digits=18, verbose_name='Latitude of southernmost point'),
        ),
        migrations.AlterField(
            model_name='region',
            name='point_lon_max',
            field=models.DecimalField(decimal_places=12, max_digits=18, verbose_name='Longitude of easternmost point'),
        ),
        migrations.AlterField(
            model_name='region',
            name='point_lon_min',
            field=models.DecimalField(decimal_places=12, max_digits=18, verbose_name='Longitude of westernmost point'),
        ),
    ]
