# Generated by Django 2.2.17 on 2020-11-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0028_dealtopinvestors'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deal',
            name='not_public_reason',
            field=models.CharField(blank=True, choices=[('CONFIDENTIAL', 'Confidential Flag'), ('NO_COUNTRY', 'No Country'), ('HIGH_INCOME_COUNTRY', 'High-Income Country'), ('NO_DATASOURCES', 'No Datasources'), ('NO_OPERATING_COMPANY', 'No Operating Company'), ('NO_KNOWN_INVESTOR', 'No Known Investor')], max_length=100),
        ),
    ]
