# Generated by Django 2.2.22 on 2021-06-02 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0028_auto_20210531_1702'),
    ]

    operations = [
        migrations.RunSQL(
            "SELECT pg_catalog.setval(pg_get_serial_sequence('landmatrix_deal', 'id'), (SELECT MAX(id) FROM landmatrix_deal))"
        ),
        migrations.RunSQL(
            "SELECT pg_catalog.setval(pg_get_serial_sequence('landmatrix_investor', 'id'), (SELECT MAX(id) FROM landmatrix_investor))"
        ),
    ]
