# Generated by Django 5.0.7 on 2024-08-20 16:21

import apps.landmatrix.models.fields
import apps.landmatrix.models.schema
import django.core.serializers.json
import django.core.validators
import django.db.models.deletion
import django_pydantic_jsonfield
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0029_alter_region_options_alter_country_point_lat_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dealversion',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='investorversion',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='dealhull',
            name='active_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='landmatrix.dealversion', verbose_name='Active version'),
        ),
        migrations.AlterField(
            model_name='dealhull',
            name='confidential',
            field=models.BooleanField(default=False, verbose_name='Confidential'),
        ),
        migrations.AlterField(
            model_name='dealhull',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AlterField(
            model_name='dealhull',
            name='deleted_comment',
            field=models.TextField(blank=True, verbose_name='Comment on deletion'),
        ),
        migrations.AlterField(
            model_name='dealhull',
            name='draft_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='landmatrix.dealversion', verbose_name='Draft version'),
        ),
        migrations.AlterField(
            model_name='dealhull',
            name='first_created_at',
            field=models.DateTimeField(verbose_name='First created at'),
        ),
        migrations.AlterField(
            model_name='dealhull',
            name='first_created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='First created by'),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='activated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Activated by'),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='animals',
            field=django_pydantic_jsonfield.PydanticJSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, validators=[django_pydantic_jsonfield.SchemaValidator(apps.landmatrix.models.schema.ExportsAnimals)], verbose_name='Livestock area/yield/export'),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='annual_leasing_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Annual leasing fee'),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='annual_leasing_fee_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Annual leasing fee area'),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='carbon_offset_project',
            field=models.BooleanField(blank=True, null=True, verbose_name='Carbon offset project'),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='carbon_offset_project_comment',
            field=models.TextField(blank=True, verbose_name='Comment on carbon offset project'),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='carbon_sequestration',
            field=django_pydantic_jsonfield.PydanticJSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, validators=[django_pydantic_jsonfield.SchemaValidator(apps.landmatrix.models.schema.CarbonSequestrationSchema)], verbose_name='Carbon sequestration/offsetting'),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='carbon_sequestration_comment',
            field=models.TextField(blank=True, verbose_name='Comment on carbon sequestration/offsetting'),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='contract_farming',
            field=models.BooleanField(blank=True, null=True, verbose_name='Contract farming'),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='contract_farming_animals',
            field=django_pydantic_jsonfield.PydanticJSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, validators=[django_pydantic_jsonfield.SchemaValidator(apps.landmatrix.models.schema.CurrentDateAreaChoicesAnimals)], verbose_name='Contract farming livestock'),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='contract_farming_crops',
            field=django_pydantic_jsonfield.PydanticJSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, validators=[django_pydantic_jsonfield.SchemaValidator(apps.landmatrix.models.schema.CurrentDateAreaChoicesCrops)], verbose_name='Contract farming crops'),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='contract_size',
            field=django_pydantic_jsonfield.PydanticJSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, validators=[django_pydantic_jsonfield.SchemaValidator(apps.landmatrix.models.schema.CurrentDateAreaSchema)], verbose_name='Contract size'),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='crops',
            field=django_pydantic_jsonfield.PydanticJSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, validators=[django_pydantic_jsonfield.SchemaValidator(apps.landmatrix.models.schema.ExportsCrops)], verbose_name='Crops area/yield/export'),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='current_animals',
            field=apps.landmatrix.models.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None, verbose_name='Current livestock'),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='current_carbon_sequestration',
            field=apps.landmatrix.models.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None, verbose_name='Current carbon sequestration/offsetting'),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='current_contract_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Current contract size'),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='current_crops',
            field=apps.landmatrix.models.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None, verbose_name='Current crops'),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='current_electricity_generation',
            field=apps.landmatrix.models.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None, verbose_name='Current electricity generation'),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='current_implementation_status',
            field=models.CharField(blank=True, choices=[('PROJECT_NOT_STARTED', 'Project not started'), ('STARTUP_PHASE', 'Startup phase (no production)'), ('IN_OPERATION', 'In operation (production)'), ('PROJECT_ABANDONED', 'Project abandoned')], null=True, verbose_name='Current implementation status'),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='current_intention_of_investment',
            field=apps.landmatrix.models.fields.ChoiceArrayField(base_field=models.CharField(choices=[('BIOFUELS', 'Biomass for biofuels'), ('BIOMASS_ENERGY_GENERATION', 'Biomass for energy generation (agriculture)'), ('FODDER', 'Fodder'), ('FOOD_CROPS', 'Food crops'), ('LIVESTOCK', 'Livestock'), ('NON_FOOD_AGRICULTURE', 'Non-food agricultural commodities'), ('AGRICULTURE_UNSPECIFIED', 'Agriculture unspecified'), ('BIOMASS_ENERGY_PRODUCTION', 'Biomass for energy generation (forestry)'), ('CARBON', 'For carbon sequestration/REDD'), ('FOREST_LOGGING', 'Forest logging / management for wood and fiber'), ('TIMBER_PLANTATION', 'Timber plantation for wood and fiber'), ('FORESTRY_UNSPECIFIED', 'Forestry unspecified'), ('SOLAR_PARK', 'Solar park'), ('WIND_FARM', 'Wind farm'), ('RENEWABLE_ENERGY', 'Renewable energy unspecified'), ('CONVERSATION', 'Conservation'), ('INDUSTRY', 'Industry'), ('LAND_SPECULATION', 'Land speculation'), ('MINING', 'Mining'), ('OIL_GAS_EXTRACTION', 'Oil / Gas extraction'), ('TOURISM', 'Tourism'), ('OTHER', 'Other')]), blank=True, default=list, size=None, verbose_name='Current intention of investment'),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='current_mineral_resources',
            field=apps.landmatrix.models.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None, verbose_name='Current mineral resources'),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='current_negotiation_status',
            field=models.CharField(blank=True, choices=[('EXPRESSION_OF_INTEREST', 'Intended (Expression of interest)'), ('UNDER_NEGOTIATION', 'Intended (Under negotiation)'), ('MEMORANDUM_OF_UNDERSTANDING', 'Intended (Memorandum of understanding)'), ('ORAL_AGREEMENT', 'Concluded (Oral Agreement)'), ('CONTRACT_SIGNED', 'Concluded (Contract signed)'), ('CHANGE_OF_OWNERSHIP', 'Concluded (Change of ownership)'), ('NEGOTIATIONS_FAILED', 'Failed (Negotiations failed)'), ('CONTRACT_CANCELED', 'Failed (Contract cancelled)'), ('CONTRACT_EXPIRED', 'Contract expired')], null=True, verbose_name='Current negotiation status'),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='current_production_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Current production size'),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='landmatrix.dealhull', verbose_name='Deal'),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='deal_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Deal size'),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='displacement_of_people',
            field=models.BooleanField(blank=True, null=True, verbose_name='Displacement of people'),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='domestic_jobs_created',
            field=models.BooleanField(blank=True, null=True, verbose_name='Jobs created (domestic)'),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='domestic_jobs_current',
            field=django_pydantic_jsonfield.PydanticJSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, validators=[django_pydantic_jsonfield.SchemaValidator(apps.landmatrix.models.schema.JobsSchema)], verbose_name='Current domestic number of jobs/employees/ daily/seasonal workers'),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='electricity_generation',
            field=django_pydantic_jsonfield.PydanticJSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, validators=[django_pydantic_jsonfield.SchemaValidator(apps.landmatrix.models.schema.ElectricityGenerationSchema)], verbose_name='Electricity generation'),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='foreign_jobs_created',
            field=models.BooleanField(blank=True, null=True, verbose_name='Jobs created (foreign)'),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='foreign_jobs_current',
            field=django_pydantic_jsonfield.PydanticJSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, validators=[django_pydantic_jsonfield.SchemaValidator(apps.landmatrix.models.schema.JobsSchema)], verbose_name='Current foreign number of jobs/employees/ daily/seasonal workers'),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='forest_concession',
            field=models.BooleanField(default=False, verbose_name='Forest concession'),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='fully_updated',
            field=models.BooleanField(default=False, verbose_name='Fully updated'),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='has_domestic_use',
            field=models.BooleanField(blank=True, null=True, verbose_name='Has domestic use'),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='has_export',
            field=models.BooleanField(blank=True, null=True, verbose_name='Has export'),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='has_known_investor',
            field=models.BooleanField(default=False, verbose_name='Has known investor'),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='implementation_status',
            field=django_pydantic_jsonfield.PydanticJSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, validators=[django_pydantic_jsonfield.SchemaValidator(apps.landmatrix.models.schema.CurrentDateChoiceImplementationStatus)], verbose_name='Implementation status'),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='in_country_processing',
            field=models.BooleanField(blank=True, null=True, verbose_name='In country processing of produce'),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='initiation_year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1970)], verbose_name='Initiation year'),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='intended_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Intended size'),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='intention_of_investment',
            field=django_pydantic_jsonfield.PydanticJSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, validators=[django_pydantic_jsonfield.SchemaValidator(apps.landmatrix.models.schema.CurrentDateAreaChoicesIOI)], verbose_name='Intention of investment'),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='involved_actors',
            field=django_pydantic_jsonfield.PydanticJSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, validators=[django_pydantic_jsonfield.SchemaValidator(apps.landmatrix.models.schema.ActorsSchema)], verbose_name='Actors involved in the negotiation / admission process'),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Is public'),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='land_conflicts',
            field=models.BooleanField(blank=True, null=True, verbose_name='Presence of land conflicts'),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='mineral_resources',
            field=django_pydantic_jsonfield.PydanticJSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, validators=[django_pydantic_jsonfield.SchemaValidator(apps.landmatrix.models.schema.ExportsMineralResources)], verbose_name='Mineral resources area/yield/export'),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='negotiation_status',
            field=django_pydantic_jsonfield.PydanticJSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, validators=[django_pydantic_jsonfield.SchemaValidator(apps.landmatrix.models.schema.CurrentDateChoiceNegotiationStatus)], verbose_name='Negotiation status'),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='off_the_lease',
            field=django_pydantic_jsonfield.PydanticJSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, validators=[django_pydantic_jsonfield.SchemaValidator(apps.landmatrix.models.schema.LeaseSchema)], verbose_name='Not on leased area/farmers/households (out-grower)'),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='off_the_lease_state',
            field=models.BooleanField(blank=True, null=True, verbose_name='Not on leased / purchased (out-grower)'),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='on_the_lease',
            field=django_pydantic_jsonfield.PydanticJSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, validators=[django_pydantic_jsonfield.SchemaValidator(apps.landmatrix.models.schema.LeaseSchema)], verbose_name='On leased area/farmers/households'),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='on_the_lease_state',
            field=models.BooleanField(blank=True, null=True, verbose_name='On leased / purchased'),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='operating_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealversions', to='landmatrix.investorhull', verbose_name='Operating company'),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='production_size',
            field=django_pydantic_jsonfield.PydanticJSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, validators=[django_pydantic_jsonfield.SchemaValidator(apps.landmatrix.models.schema.CurrentDateAreaSchema)], verbose_name='Production size'),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Purchase price'),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='purchase_price_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Purchase price area'),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='sent_to_activation_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Sent to activation at'),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='sent_to_activation_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Sent to activation by'),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='sent_to_review_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Sent to review by'),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('REVIEW', 'Review'), ('ACTIVATION', 'Activation'), ('ACTIVATED', 'Activated')], default='DRAFT', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='total_jobs_created',
            field=models.BooleanField(blank=True, null=True, verbose_name='Jobs created (total)'),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='total_jobs_current',
            field=django_pydantic_jsonfield.PydanticJSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, validators=[django_pydantic_jsonfield.SchemaValidator(apps.landmatrix.models.schema.JobsSchema)], verbose_name='Current total number of jobs/employees/ daily/seasonal workers'),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='transnational',
            field=models.BooleanField(blank=True, null=True, verbose_name='Transnational'),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='use_of_irrigation_infrastructure',
            field=models.BooleanField(blank=True, null=True, verbose_name='Use of irrigation infrastructure'),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='water_extraction_envisaged',
            field=models.BooleanField(blank=True, null=True, verbose_name='Water extraction envisaged'),
        ),
        migrations.AlterField(
            model_name='investorhull',
            name='active_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='landmatrix.investorversion', verbose_name='Active version'),
        ),
        migrations.AlterField(
            model_name='investorhull',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AlterField(
            model_name='investorhull',
            name='deleted_comment',
            field=models.TextField(blank=True, verbose_name='Comment on deletion'),
        ),
        migrations.AlterField(
            model_name='investorhull',
            name='draft_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='landmatrix.investorversion', verbose_name='Draft version'),
        ),
        migrations.AlterField(
            model_name='investorhull',
            name='first_created_at',
            field=models.DateTimeField(verbose_name='First created at'),
        ),
        migrations.AlterField(
            model_name='investorhull',
            name='first_created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='First created by'),
        ),
        migrations.AlterField(
            model_name='investorversion',
            name='activated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Activated by'),
        ),
        migrations.AlterField(
            model_name='investorversion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='investorversion',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='landmatrix.investorhull', verbose_name='Investor'),
        ),
        migrations.AlterField(
            model_name='investorversion',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
        migrations.AlterField(
            model_name='investorversion',
            name='sent_to_activation_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Sent to activation at'),
        ),
        migrations.AlterField(
            model_name='investorversion',
            name='sent_to_activation_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Sent to activation by'),
        ),
        migrations.AlterField(
            model_name='investorversion',
            name='sent_to_review_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Sent to review by'),
        ),
        migrations.AlterField(
            model_name='investorversion',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('REVIEW', 'Review'), ('ACTIVATION', 'Activation'), ('ACTIVATED', 'Activated')], default='DRAFT', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='involvement',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Comment on involvement'),
        ),
    ]
