# Generated by Django 2.2.17 on 2020-12-05 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("landmatrix", "0030_auto_20201122_2136"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deal",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deals",
                to="landmatrix.Country",
                verbose_name="Target Country",
            ),
        ),
    ]
