# Generated by Django 5.0.7 on 2024-09-30 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0030_fix_field_validation'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorQISnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DealQISnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('subset_key', models.CharField(null=True)),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='landmatrix.region')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
