# Generated by Django 2.2.17 on 2020-12-07 16:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("landmatrix", "0031_auto_20201205_1237"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deal",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Created"
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="fully_updated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Last full update"
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="modified_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Last update"
            ),
        ),
        migrations.AlterField(
            model_name="investor",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Created"
            ),
        ),
        migrations.AlterField(
            model_name="investor",
            name="modified_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Last update"
            ),
        ),
    ]
