# Generated by Django 2.2.17 on 2020-12-25 20:58

import apps.landmatrix.models.deal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0032_auto_20201207_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='nature_of_deal',
            field=apps.landmatrix.models.deal.ArrayField(base_field=models.CharField(max_length=100, verbose_name='Nature of the deal'), blank=True, choices=[('OUTRIGHT_PURCHASE', 'Outright Purchase'), ('LEASE', 'Lease'), ('CONCESSION', 'Concession'), ('EXPLOITATION_PERMIT', 'Exploitation permit / license / concession (for mineral resources)'), ('PURE_CONTRACT_FARMING', 'Pure contract farming'), ('OTHER', 'Other')], null=True, size=None),
        ),
    ]
