# Generated by Django 5.0.10 on 2025-01-08 13:15

from apps.landmatrix.models.schema import QuotationsSchema
from django.core.serializers.json import DjangoJSONEncoder
from django_pydantic_jsonfield import SchemaValidator, PydanticJSONField
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("landmatrix", "0032_contexthelp")]

    operations = [
        migrations.AddField(
            model_name="dealversion",
            name="ds_quotations",
            field=PydanticJSONField(
                default=dict,
                encoder=DjangoJSONEncoder,
                validators=[SchemaValidator(QuotationsSchema)],
                verbose_name="Data Source Quotations",
            ),
        ),
        migrations.AddField(
            model_name="investorversion",
            name="ds_quotations",
            field=PydanticJSONField(
                default=dict,
                encoder=DjangoJSONEncoder,
                validators=[SchemaValidator(QuotationsSchema)],
                verbose_name="Data Source Quotations",
            ),
        ),
    ]
