# Generated by Django 2.2.17 on 2020-12-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0033_auto_20201225_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='top_investors',
            field=models.ManyToManyField(related_name='_deal_top_investors_+', to='landmatrix.Investor', verbose_name='Top parent companies'),
        ),
    ]
