# Generated by Django 5.0.11 on 2025-01-22 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0033_dealversion_ds_quotations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FieldDefinition',
        ),
    ]
