# Generated by Django 2.2.22 on 2021-06-16 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0034_auto_20210614_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealworkflowinfo',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landmatrix.Deal'),
        ),
    ]
