# Generated by Django 5.0.12 on 2025-02-19 14:58

from apps.landmatrix.models.schema import DataSourceQuotationSchema
from django.core.serializers.json import DjangoJSONEncoder
from django_pydantic_jsonfield import SchemaValidator, PydanticJSONField
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("landmatrix", "0035_alter_dealversion_annual_leasing_fee_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="investorversion",
            name="ds_quotations",
            field=PydanticJSONField(
                blank=True,
                default=dict,
                encoder=DjangoJSONEncoder,
                validators=[SchemaValidator(DataSourceQuotationSchema)],
                verbose_name="Data Source Quotations",
            ),
        ),
    ]
