# Generated by Django 2.2.22 on 2021-07-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0036_auto_20210620_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorventureinvolvement',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='investorventureinvolvement',
            name='loans_date',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Loan date'),
        ),
    ]
