# Generated by Django 2.2.22 on 2021-07-13 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0038_investorworkflowinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investorworkflowinfo',
            old_name='deal',
            new_name='investor',
        ),
        migrations.RenameField(
            model_name='investorworkflowinfo',
            old_name='deal_version',
            new_name='investor_version',
        ),
    ]
