# Generated by Django 2.2.22 on 2021-08-18 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0043_auto_20210818_1439'),
    ]

    operations = [
        migrations.RemoveField(model_name='Deal', name='current_draft'),
        migrations.DeleteModel('DealWorkflowInfo'),
        migrations.DeleteModel('DealVersion'),
        migrations.RemoveField(model_name='Investor', name='current_draft'),
        migrations.DeleteModel('InvestorWorkflowInfo'),
        migrations.DeleteModel('InvestorVersion'),
    ]
