# Generated by Django 3.2.6 on 2021-08-25 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0046_auto_20210824_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='animals',
            field=models.JSONField(blank=True, null=True, verbose_name='Livestock area/yield/export'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='contract_farming',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='contract_farming_animals',
            field=models.JSONField(blank=True, help_text='ha', null=True, verbose_name='Contract farming livestock'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='contract_farming_crops',
            field=models.JSONField(blank=True, help_text='ha', null=True, verbose_name='Contract farming crops'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='contract_size',
            field=models.JSONField(blank=True, help_text='ha', null=True, verbose_name='Size under contract (leased or purchased area, in ha)'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='crops',
            field=models.JSONField(blank=True, null=True, verbose_name='Crops area/yield/export'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='displacement_of_people',
            field=models.BooleanField(null=True, verbose_name='Displacement of people'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='domestic_jobs_created',
            field=models.BooleanField(null=True, verbose_name='Jobs created (domestic)'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='domestic_jobs_current',
            field=models.JSONField(blank=True, null=True, verbose_name='Current domestic number of jobs/employees/ daily/seasonal workers'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='foreign_jobs_created',
            field=models.BooleanField(null=True, verbose_name='Jobs created (foreign)'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='foreign_jobs_current',
            field=models.JSONField(blank=True, null=True, verbose_name='Current foreign number of jobs/employees/ daily/seasonal workers'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='geojson',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='has_domestic_use',
            field=models.BooleanField(null=True, verbose_name='Has domestic use'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='has_export',
            field=models.BooleanField(null=True, verbose_name='Has export'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='implementation_status',
            field=models.JSONField(blank=True, choices=[('PROJECT_NOT_STARTED', 'Project not started'), ('STARTUP_PHASE', 'Startup phase (no production)'), ('IN_OPERATION', 'In operation (production)'), ('PROJECT_ABANDONED', 'Project abandoned')], null=True, verbose_name='Implementation status'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='in_country_processing',
            field=models.BooleanField(null=True, verbose_name='In country processing of produce'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='intention_of_investment',
            field=models.JSONField(blank=True, choices=[('Agriculture', (('BIOFUELS', 'Biofuels'), ('FOOD_CROPS', 'Food crops'), ('FODDER', 'Fodder'), ('LIVESTOCK', 'Livestock'), ('NON_FOOD_AGRICULTURE', 'Non-food agricultural commodities'), ('AGRICULTURE_UNSPECIFIED', 'Agriculture unspecified'))), ('Forestry', (('TIMBER_PLANTATION', 'Timber plantation'), ('FOREST_LOGGING', 'Forest logging / management'), ('CARBON', 'For carbon sequestration/REDD'), ('FORESTRY_UNSPECIFIED', 'Forestry unspecified'))), ('Other', (('MINING', 'Mining'), ('OIL_GAS_EXTRACTION', 'Oil / Gas extraction'), ('TOURISM', 'Tourism'), ('INDUSTRY', 'Industry'), ('CONVERSATION', 'Conservation'), ('LAND_SPECULATION', 'Land speculation'), ('RENEWABLE_ENERGY', 'Renewable energy'), ('OTHER', 'Other')))], null=True, verbose_name='Intention of investment'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='involved_actors',
            field=models.JSONField(blank=True, choices=[('GOVERNMENT_OR_STATE_INSTITUTIONS', 'Government / state institutions (government, ministries, departments, agencies etc.)'), ('TRADITIONAL_LAND_OWNERS_OR_COMMUNITIES', 'Traditional land-owners / communities'), ('TRADITIONAL_LOCAL_AUTHORITY', 'Traditional local authority (e.g. Chiefdom council / Chiefs)'), ('BROKER', 'Broker'), ('INTERMEDIARY', 'Intermediary'), ('OTHER', 'Other (please specify)')], null=True, verbose_name='Actors involved in the negotiation / admission process'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='land_conflicts',
            field=models.BooleanField(null=True, verbose_name='Presence of land conflicts'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='mineral_resources',
            field=models.JSONField(blank=True, null=True, verbose_name='Mineral resources area/yield/export'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='negotiation_status',
            field=models.JSONField(blank=True, choices=[('Intended', (('EXPRESSION_OF_INTEREST', 'Expression of interest'), ('UNDER_NEGOTIATION', 'Under negotiation'), ('MEMORANDUM_OF_UNDERSTANDING', 'Memorandum of understanding'))), ('Concluded', (('ORAL_AGREEMENT', 'Oral agreement'), ('CONTRACT_SIGNED', 'Contract signed'))), ('Failed', (('NEGOTIATIONS_FAILED', 'Negotiations failed'), ('CONTRACT_CANCELED', 'Contract canceled'))), ('CONTRACT_EXPIRED', 'Contract expired'), ('CHANGE_OF_OWNERSHIP', 'Change of ownership')], null=True, verbose_name='Negotiation status'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='off_the_lease',
            field=models.JSONField(blank=True, help_text='ha', null=True, verbose_name='Not on leased area/farmers/households (out-grower)'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='off_the_lease_state',
            field=models.BooleanField(null=True, verbose_name='Not on leased / purchased (out-grower)'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='on_the_lease',
            field=models.JSONField(blank=True, null=True, verbose_name='On leased area/farmers/households'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='on_the_lease_state',
            field=models.BooleanField(null=True, verbose_name='On leased / purchased'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='production_size',
            field=models.JSONField(blank=True, help_text='ha', null=True, verbose_name='Size in operation (production, in ha)'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='total_jobs_created',
            field=models.BooleanField(null=True, verbose_name='Jobs created (total)'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='total_jobs_current',
            field=models.JSONField(blank=True, null=True, verbose_name='Current total number of jobs/employees/ daily/seasonal workers'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='transnational',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='use_of_irrigation_infrastructure',
            field=models.BooleanField(null=True, verbose_name='Use of irrigation infrastructure'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='water_extraction_envisaged',
            field=models.BooleanField(null=True, verbose_name='Water extraction envisaged'),
        ),
        migrations.AlterField(
            model_name='dealversion',
            name='serialized_data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='investorversion',
            name='serialized_data',
            field=models.JSONField(),
        ),
    ]
