# Generated by Django 3.2.12 on 2022-02-24 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0048_auto_20210929_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filterpreset',
            name='group',
        ),
        migrations.DeleteModel(
            name='FilterCondition',
        ),
        migrations.DeleteModel(
            name='FilterPreset',
        ),
        migrations.DeleteModel(
            name='FilterPresetGroup',
        ),
    ]
