# Generated by Django 3.2.13 on 2022-05-09 18:53

import apps.landmatrix.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0051_auto_20220321_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='current_intention_of_investment',
            field=apps.landmatrix.models.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, choices=[('BIOFUELS', 'Biofuels'), ('FOOD_CROPS', 'Food crops'), ('FODDER', 'Fodder'), ('LIVESTOCK', 'Livestock'), ('NON_FOOD_AGRICULTURE', 'Non-food agricultural commodities'), ('AGRICULTURE_UNSPECIFIED', 'Agriculture unspecified'), ('TIMBER_PLANTATION', 'Timber plantation'), ('FOREST_LOGGING', 'Forest logging / management'), ('CARBON', 'For carbon sequestration/REDD'), ('FORESTRY_UNSPECIFIED', 'Forestry unspecified'), ('MINING', 'Mining'), ('OIL_GAS_EXTRACTION', 'Oil / Gas extraction'), ('TOURISM', 'Tourism'), ('INDUSTRY', 'Industry'), ('CONVERSATION', 'Conservation'), ('LAND_SPECULATION', 'Land speculation'), ('RENEWABLE_ENERGY', 'Renewable energy'), ('OTHER', 'Other')], null=True, size=None),
        ),
        migrations.AlterField(
            model_name='deal',
            name='current_negotiation_status',
            field=models.CharField(blank=True, choices=[('EXPRESSION_OF_INTEREST', 'Expression of interest'), ('UNDER_NEGOTIATION', 'Under negotiation'), ('MEMORANDUM_OF_UNDERSTANDING', 'Memorandum of understanding'), ('ORAL_AGREEMENT', 'Oral agreement'), ('CONTRACT_SIGNED', 'Contract signed'), ('NEGOTIATIONS_FAILED', 'Negotiations failed'), ('CONTRACT_CANCELED', 'Contract canceled'), ('CONTRACT_EXPIRED', 'Contract expired'), ('CHANGE_OF_OWNERSHIP', 'Change of ownership')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='intention_of_investment',
            field=models.JSONField(blank=True, choices=[('BIOFUELS', 'Biofuels'), ('FOOD_CROPS', 'Food crops'), ('FODDER', 'Fodder'), ('LIVESTOCK', 'Livestock'), ('NON_FOOD_AGRICULTURE', 'Non-food agricultural commodities'), ('AGRICULTURE_UNSPECIFIED', 'Agriculture unspecified'), ('TIMBER_PLANTATION', 'Timber plantation'), ('FOREST_LOGGING', 'Forest logging / management'), ('CARBON', 'For carbon sequestration/REDD'), ('FORESTRY_UNSPECIFIED', 'Forestry unspecified'), ('MINING', 'Mining'), ('OIL_GAS_EXTRACTION', 'Oil / Gas extraction'), ('TOURISM', 'Tourism'), ('INDUSTRY', 'Industry'), ('CONVERSATION', 'Conservation'), ('LAND_SPECULATION', 'Land speculation'), ('RENEWABLE_ENERGY', 'Renewable energy'), ('OTHER', 'Other')], null=True, verbose_name='Intention of investment'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='nature_of_deal',
            field=apps.landmatrix.models.fields.ArrayField(base_field=models.CharField(max_length=100, verbose_name='Nature of the deal'), blank=True, choices=[('OUTRIGHT_PURCHASE', 'Outright purchase'), ('LEASE', 'Lease'), ('CONCESSION', 'Concession'), ('EXPLOITATION_PERMIT', 'Exploitation permit / license / concession (for mineral resources)'), ('PURE_CONTRACT_FARMING', 'Pure contract farming'), ('OTHER', 'Other')], null=True, size=None, verbose_name='Nature of the deal'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='negotiation_status',
            field=models.JSONField(blank=True, choices=[('EXPRESSION_OF_INTEREST', 'Expression of interest'), ('UNDER_NEGOTIATION', 'Under negotiation'), ('MEMORANDUM_OF_UNDERSTANDING', 'Memorandum of understanding'), ('ORAL_AGREEMENT', 'Oral agreement'), ('CONTRACT_SIGNED', 'Contract signed'), ('NEGOTIATIONS_FAILED', 'Negotiations failed'), ('CONTRACT_CANCELED', 'Contract canceled'), ('CONTRACT_EXPIRED', 'Contract expired'), ('CHANGE_OF_OWNERSHIP', 'Change of ownership')], null=True, verbose_name='Negotiation status'),
        ),
    ]
