# Generated by Django 3.2.13 on 2022-05-09 21:08

import apps.landmatrix.models.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0052_auto_20220509_2053'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Animal',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='fk_user',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='fk_agricultural_produce',
        ),
        migrations.DeleteModel(
            name='Mineral',
        ),
        migrations.AlterField(
            model_name='deal',
            name='contract_farming_animals',
            field=models.JSONField(blank=True, null=True, verbose_name='Contract farming livestock'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='contract_farming_crops',
            field=models.JSONField(blank=True, null=True, verbose_name='Contract farming crops'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='contracts',
            field=apps.landmatrix.models.fields.ContractsField(blank=True, default=list, verbose_name='Contracts'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='current_intention_of_investment',
            field=apps.landmatrix.models.fields.ArrayField(base_field=models.CharField(choices=[('BIOFUELS', 'Biofuels'), ('FOOD_CROPS', 'Food crops'), ('FODDER', 'Fodder'), ('LIVESTOCK', 'Livestock'), ('NON_FOOD_AGRICULTURE', 'Non-food agricultural commodities'), ('AGRICULTURE_UNSPECIFIED', 'Agriculture unspecified'), ('TIMBER_PLANTATION', 'Timber plantation'), ('FOREST_LOGGING', 'Forest logging / management'), ('CARBON', 'For carbon sequestration/REDD'), ('FORESTRY_UNSPECIFIED', 'Forestry unspecified'), ('MINING', 'Mining'), ('OIL_GAS_EXTRACTION', 'Oil / Gas extraction'), ('TOURISM', 'Tourism'), ('INDUSTRY', 'Industry'), ('CONVERSATION', 'Conservation'), ('LAND_SPECULATION', 'Land speculation'), ('RENEWABLE_ENERGY', 'Renewable energy'), ('OTHER', 'Other')], max_length=100), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='deal',
            name='current_negotiation_status',
            field=models.CharField(blank=True, choices=[('EXPRESSION_OF_INTEREST', 'Intended (Expression of interest)'), ('UNDER_NEGOTIATION', 'Intended (Under negotiation)'), ('MEMORANDUM_OF_UNDERSTANDING', 'Intended (Memorandum of understanding)'), ('ORAL_AGREEMENT', 'Concluded (Oral Agreement)'), ('CONTRACT_SIGNED', 'Concluded (Contract signed)'), ('NEGOTIATIONS_FAILED', 'Failed (Negotiations failed)'), ('CONTRACT_CANCELED', 'Failed (Contract cancelled)'), ('CONTRACT_EXPIRED', 'Contract expired'), ('CHANGE_OF_OWNERSHIP', 'Change of ownership')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='datasources',
            field=apps.landmatrix.models.fields.DatasourcesField(blank=True, default=list, verbose_name='Data sources'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='former_land_cover',
            field=apps.landmatrix.models.fields.ArrayField(base_field=models.CharField(choices=[('CROPLAND', 'Cropland'), ('FOREST_LAND', 'Forest land'), ('PASTURE', 'Pasture'), ('RANGELAND', 'Shrub land/Grassland (Rangeland)'), ('MARGINAL_LAND', 'Marginal land'), ('WETLAND', 'Wetland'), ('OTHER_LAND', 'Other land (e.g. developed land – specify in comment field)')], max_length=100), blank=True, null=True, size=None, verbose_name='Former land cover'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='former_land_owner',
            field=apps.landmatrix.models.fields.ArrayField(base_field=models.CharField(choices=[('STATE', 'State'), ('PRIVATE_SMALLHOLDERS', 'Private (smallholders)'), ('PRIVATE_LARGE_SCALE', 'Private (large-scale farm)'), ('COMMUNITY', 'Community'), ('INDIGENOUS_PEOPLE', 'Indigenous people'), ('OTHER', 'Other')], max_length=100), blank=True, null=True, size=None, verbose_name='Former land owner'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='former_land_use',
            field=apps.landmatrix.models.fields.ArrayField(base_field=models.CharField(choices=[('COMMERCIAL_AGRICULTURE', 'Commercial (large-scale) agriculture'), ('SMALLHOLDER_AGRICULTURE', 'Smallholder agriculture'), ('SHIFTING_CULTIVATION', 'Shifting cultivation'), ('PASTORALISM', 'Pastoralism'), ('HUNTING_GATHERING', 'Hunting/Gathering'), ('FORESTRY', 'Forestry'), ('CONSERVATION', 'Conservation'), ('OTHER', 'Other')], max_length=100), blank=True, null=True, size=None, verbose_name='Former land use'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='implementation_status',
            field=models.JSONField(blank=True, null=True, verbose_name='Implementation status'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='intention_of_investment',
            field=models.JSONField(blank=True, null=True, verbose_name='Intention of investment'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='involved_actors',
            field=models.JSONField(blank=True, null=True, verbose_name='Actors involved in the negotiation / admission process'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='locations',
            field=apps.landmatrix.models.fields.LocationsField(blank=True, default=list, verbose_name='Locations'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='materialized_benefits',
            field=apps.landmatrix.models.fields.ArrayField(base_field=models.CharField(choices=[('HEALTH', 'Health'), ('EDUCATION', 'Education'), ('PRODUCTIVE_INFRASTRUCTURE', 'Productive infrastructure (e.g. irrigation, tractors, machinery...)'), ('ROADS', 'Roads'), ('CAPACITY_BUILDING', 'Capacity building'), ('FINANCIAL_SUPPORT', 'Financial support'), ('COMMUNITY_SHARES', 'Community shares in the investment project'), ('OTHER', 'Other')], max_length=100), blank=True, null=True, size=None, verbose_name='Materialized benefits for local communities'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='name_of_community',
            field=apps.landmatrix.models.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None, verbose_name='Name of community'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='name_of_indigenous_people',
            field=apps.landmatrix.models.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None, verbose_name='Name of indigenous people'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='nature_of_deal',
            field=apps.landmatrix.models.fields.ArrayField(base_field=models.CharField(choices=[('OUTRIGHT_PURCHASE', 'Outright purchase'), ('LEASE', 'Lease'), ('CONCESSION', 'Concession'), ('EXPLOITATION_PERMIT', 'Exploitation permit / license / concession (for mineral resources)'), ('PURE_CONTRACT_FARMING', 'Pure contract farming'), ('OTHER', 'Other')], max_length=100), blank=True, null=True, size=None, verbose_name='Nature of the deal'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='negative_impacts',
            field=apps.landmatrix.models.fields.ArrayField(base_field=models.CharField(choices=[('ENVIRONMENTAL_DEGRADATION', 'Environmental degradation'), ('SOCIO_ECONOMIC', 'Socio-economic'), ('CULTURAL_LOSS', 'Cultural loss'), ('EVICTION', 'Eviction'), ('DISPLACEMENT', 'Displacement'), ('VIOLENCE', 'Violence'), ('OTHER', 'Other')], max_length=100), blank=True, null=True, size=None, verbose_name='Negative impacts for local communities'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='negotiation_status',
            field=models.JSONField(blank=True, null=True, verbose_name='Negotiation status'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='promised_benefits',
            field=apps.landmatrix.models.fields.ArrayField(base_field=models.CharField(choices=[('HEALTH', 'Health'), ('EDUCATION', 'Education'), ('PRODUCTIVE_INFRASTRUCTURE', 'Productive infrastructure (e.g. irrigation, tractors, machinery...)'), ('ROADS', 'Roads'), ('CAPACITY_BUILDING', 'Capacity building'), ('FINANCIAL_SUPPORT', 'Financial support'), ('COMMUNITY_SHARES', 'Community shares in the investment project'), ('OTHER', 'Other')], max_length=100), blank=True, null=True, size=None, verbose_name='Promised benefits for local communities'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='recognition_status',
            field=apps.landmatrix.models.fields.ArrayField(base_field=models.CharField(choices=[('INDIGENOUS_RIGHTS_RECOGNIZED', 'Indigenous Peoples traditional or customary rights recognized by government'), ('INDIGENOUS_RIGHTS_NOT_RECOGNIZED', 'Indigenous Peoples traditional or customary rights not recognized by government'), ('COMMUNITY_RIGHTS_RECOGNIZED', 'Community traditional or customary rights recognized by government'), ('COMMUNITY_RIGHTS_NOT_RECOGNIZED', 'Community traditional or customary rights not recognized by government')], max_length=100), blank=True, null=True, size=None, verbose_name='Recognition status of community land tenure'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='source_of_water_extraction',
            field=apps.landmatrix.models.fields.ArrayField(base_field=models.CharField(choices=[('GROUNDWATER', 'Groundwater'), ('SURFACE_WATER', 'Surface water'), ('RIVER', 'River'), ('LAKE', 'Lake')], max_length=100), blank=True, null=True, size=None, verbose_name='Source of water extraction'),
        ),
        migrations.DeleteModel(
            name='AgriculturalProduce',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Crop',
        ),
    ]
