# Generated by Django 3.2.13 on 2022-05-20 11:48

import apps.landmatrix.models.fields
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0053_auto_20220509_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='datasources',
            field=apps.landmatrix.models.fields.DatasourcesField(blank=True, default=list, verbose_name='Data sources'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='animals',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='contract_farming_animals',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='contract_farming_crops',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='contract_size',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='crops',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='domestic_jobs_current',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='domestic_jobs_planned',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Planned number of jobs (domestic)'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='domestic_jobs_planned_daily_workers',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Planned daily/seasonal workers (domestic)'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='domestic_jobs_planned_employees',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Planned employees (domestic)'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='domestic_use',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Domestic use'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='export',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Export'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='export_country1_ratio',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Country 1 ratio'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='export_country2_ratio',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Country 2 ratio'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='export_country3_ratio',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Country 3 ratio'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='foreign_jobs_current',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='foreign_jobs_planned',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Planned number of jobs (foreign)'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='foreign_jobs_planned_daily_workers',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Planned daily/seasonal workers (foreign)'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='foreign_jobs_planned_employees',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Planned employees (foreign)'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='implementation_status',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='intended_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Intended size (in ha)'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='intention_of_investment',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='involved_actors',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='mineral_resources',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='negotiation_status',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='off_the_lease',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='on_the_lease',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='production_size',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='total_jobs_current',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='total_jobs_planned',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Planned number of jobs (total)'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='total_jobs_planned_daily_workers',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Planned daily/seasonal workers (total)'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='total_jobs_planned_employees',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Planned employees (total)'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='water_extraction_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Water extraction amount'),
        ),
        migrations.AlterField(
            model_name='investorventureinvolvement',
            name='investment_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('EQUITY', 'Shares/Equity'), ('DEBT_FINANCING', 'Debt financing')], max_length=100), blank=True, null=True, size=None, verbose_name='Investment type'),
        ),
    ]
