# Generated by Django 3.2.13 on 2022-06-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0055_auto_20220604_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='current_negotiation_status',
            field=models.CharField(blank=True, choices=[('EXPRESSION_OF_INTEREST', 'Intended (Expression of interest)'), ('UNDER_NEGOTIATION', 'Intended (Under negotiation)'), ('MEMORANDUM_OF_UNDERSTANDING', 'Intended (Memorandum of understanding)'), ('ORAL_AGREEMENT', 'Concluded (Oral Agreement)'), ('CONTRACT_SIGNED', 'Concluded (Contract signed)'), ('CHANGE_OF_OWNERSHIP', 'Concluded (Change of ownership)'), ('NEGOTIATIONS_FAILED', 'Failed (Negotiations failed)'), ('CONTRACT_CANCELED', 'Failed (Contract cancelled)'), ('CONTRACT_EXPIRED', 'Contract expired')], max_length=100, null=True),
        ),
    ]
