# Generated by Django 3.2.13 on 2022-06-17 20:13

import apps.landmatrix.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmatrix', '0056_alter_deal_current_negotiation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='current_contract_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Current contract size'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='name_of_community',
            field=apps.landmatrix.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, null=True, size=None, verbose_name='Name of community'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='name_of_indigenous_people',
            field=apps.landmatrix.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, null=True, size=None, verbose_name='Name of indigenous people'),
        ),
    ]
