from django.conf.urls import url

from rest_framework_swagger.views import get_swagger_view

from api.views import *
from api.views.list_views import PolygonGeomView

schema_view = get_swagger_view(title='Land Matrix API')

urlpatterns = [
    url(r'^agricultural-produce\.json',
        AgriculturalProduceListView.as_view(),
        name='agricultural_produce_api'),
    url(r'^contract-farming\.json',
        ContractFarmingView.as_view(),
        name='contract_farming_api'),
    url(r'^countries-geom\.json',
        CountryGeomView.as_view(),
        name='countries_geom_api'),
    url(r'^target-countries\.json',
        TargetCountryListView.as_view(),
        name='target_countries_api'),
    url(r'^countries\.json',
        CountryListView.as_view(),
        name='countries_api'),
    url(r'^country_deals\.json',
        CountryDealsView.as_view(),
        name='country_deals_api'),
    url(r'^deal_detail/(?P<deal_id>\d+)\.json',
        DealDetailView.as_view(),
        name='api_deal_detail'),
    url(r'^deals\.json',
        GlobalDealsView.as_view(),
        name='deals_api'),
    url(r'^filter\.json',
        FilterListView.as_view(),
        name='api_filter'),
    url(r'^filter/add/default/',
        SetDefaultFiltersView.as_view(),
        name='api_filter'),
    url(r'^filter/add/',
        FilterCreateView.as_view(),
        name='api_filter'),
    url(r'^filter/delete/',
        FilterDeleteView.as_view(),
        name='api_filter'),
    url(r'^filter/clear/',
        FilterClearView.as_view(),
        name='api_filter'),
    url(r'^filter_preset\.json',
        FilterPresetView.as_view(),
        name='api_dashboard_filter_preset'),
    url(r'^hectares\.json',
        HectaresView.as_view(),
        name='hectares_api'),
    url(r'^implementation_status\.json',
        ImplementationStatusListView.as_view(),
        name='implementation_status_api'),
    url(r'^intention\.json',
        InvestmentIntentionListView.as_view(),
        name='intention'),
    url(r'^investor_countries_for_target_country\.json',
        InvestorCountriesForTargetCountryView.as_view(),
        name='investor_countries_for_target_country_api'),
    url(r'^investor_country_summaries\.json',
        InvestorCountrySummaryView.as_view(),
        name='investor_country_summaries_api'),
    url(r'^investor_network\.json',
        InvestorNetworkView.as_view(),
        name='api_investor_network'),
    url(r'^investors\.json',
        InvestorListView.as_view(),
        name='investors_api'),
    url(r'^logging\.json',
        LoggingView.as_view(),
        name='logging_api'),
    url(r'^negotiation_status\.json',
        NegotiationStatusListView.as_view(),
        name='negotiation_status_api'),
    url(r'^polygons/(?P<polygon_field>[^/]+)\.json',
        PolygonGeomView.as_view(),
        name='polygon_geom_api'),
    url(r'^produce-info\.json',
        ProduceInfoView.as_view(),
        name='produce_info_api'),
    url(r'^transnational_deals\.json',
        TransnationalDealListView.as_view(),
        name='transnational_deals_api'),
    url(r'^top-10-countries\.json',
        Top10CountriesView.as_view(),
        name='top_10_countries_api'),
    url(r'^transnational_deals_by_country\.json',
        TransnationalDealsByCountryView.as_view(),
        name='transnational_deals_by_country_api'),
    url(r'^target_country_summaries\.json',
        TargetCountrySummaryView.as_view(),
        name='target_country_summaries_api'),
    url(r'^target_countries_for_investor_country\.json',
        TargetCountrySummaryView.as_view(),
        name='target_countries_for_investor_country_api'),
    url(r'^users\.json',
        UserListView.as_view(),
        name='users_api'),
    url(r'^regions\.json',
        RegionListView.as_view(),
        name='regions_api'),
    url(r'^resource-extraction\.json',
        ResourceExtractionView.as_view(),
        name='resource_extraction_api'),
    url(r'^statistics\.json', StatisticsView.as_view(), name='statistics_api'),
    url(r'^latest_changes\.json', LatestChangesView.as_view(), name='latest_changes_api'),
    url(r'^$', schema_view)
]
